/* SKETCHBENCH 0.1.0 — Copyright 2026 Green Shoe Garage. GPL-3.0-only. */
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],{V}=K;
const VERSION='1.0.0-rc.3',KEY='sketchbench-v1:'+((location.pathname||'/').replace(/[^/]*$/,'')),id=()=>crypto.randomUUID?crypto.randomUUID():'o'+Date.now()+Math.random().toString(16).slice(2),clone=x=>JSON.parse(JSON.stringify(x)),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let doc={app:'SKETCHBENCH',schema:1,version:VERSION,name:'Untitled model',units:'mm',objects:[]},selected=new Set(),selectedFace=null,tool='select',points=[],hover=null,gesture=null,history=[],future=[],dirty=false,db=null,saveTimer,saveQueue=Promise.resolve(),savedSnapshot=null,conflict=false;
let prefs={theme:'light',advanced:false,plane:'xy',elevation:0,grid:10,snap:true,color:'#70b69b',panel:innerWidth>760},camera={az:.75,el:.6,scale:2.8,target:[0,0,0]},renderMode='shaded',measure=null;
try{Object.assign(prefs,JSON.parse(localStorage.getItem(KEY+'-prefs')||localStorage.getItem('sketchbench-v1-prefs')||'{}'));}catch{}
if(!['light','dark','contrast'].includes(prefs.theme))prefs.theme='light';
if(!['xy','xz','yz'].includes(prefs.plane))prefs.plane='xy';
if(!Number.isFinite(prefs.grid)||prefs.grid<.1||prefs.grid>1000)prefs.grid=10;
if(!Number.isFinite(prefs.elevation)||Math.abs(prefs.elevation)>100000)prefs.elevation=0;
if(!/^#[a-f\d]{6}$/i.test(prefs.color))prefs.color='#70b69b';
const stage=$('#stage'),canvas=$('#view'),overlay=$('#overlay'),ctx=overlay.getContext('2d');let lastNavigationDrag=false;let gl=null,gpu=null,fallback=null,width=1,height=1,dpr=1,drawn=[],edgeHits=[],lastPointer=[0,0],spaceDown=false;
const toolDefs=[['select','Select','V','M5 3 18 13 12 14 10 21Z'],['orbit','Orbit','O','M4 10C4 3 20 3 20 10S4 18 4 10 M5 3 4 10 11 8 M12 2V22'],['pan','Pan','H','M12 3V21 M3 12H21 M9 6 12 3 15 6 M6 9 3 12 6 15 M9 18 12 21 15 18 M18 9 21 12 18 15'],['rectangle','Rectangle','R','M4 5H20V19H4Z'],['circle','Circle','C','M21 12A9 9 0 1 1 3 12A9 9 0 1 1 21 12 M12 12H21'],['polygon','Profile','G','M3 18 5 5 14 3 21 10 17 21Z'],['line','Line','L','M4 20 20 4 M3 18V21H6 M18 3H21V6'],['pushpull','Push/pull','P','M4 12 12 8 20 12 20 21 12 24 4 20Z M12 16V2 M8 6 12 2 16 6'],['move','Move','M','M12 2V22 M2 12H22 M9 5 12 2 15 5 M5 9 2 12 5 15 M9 19 12 22 15 19 M19 9 22 12 19 15'],['measure','Measure','T','M3 16 16 3 22 9 9 22Z M8 12 11 15 M12 8 15 11 M16 4 19 7']];
const hints={select:'Click an object or face. Shift-click adds to selection.',orbit:'Drag for full 360° orbit, over or under the model. Scroll to zoom.',pan:'Drag to pan the view. Scroll to zoom.',rectangle:'Click opposite corners on the work plane. Then Push/pull.',circle:'Click the center, then the radius on the work plane.',polygon:'Click vertices. Click the first point or press Enter to close.',line:'Click points. Double-click or Enter to finish an open line.',pushpull:'Drag a face to extrude. Or select a face and enter a distance.',move:'Drag a selected object along the work plane; use X/Y/Z for precision.',measure:'Click two points. Vertices snap within 12 pixels.'};
$('#tools').innerHTML=toolDefs.map(([key,name,shortcut,path],i)=>`${i===3||i===7?'<hr>':''}<button data-tool="${key}" title="${name} (${shortcut})" aria-label="${name} tool" aria-pressed="false"><svg viewBox="0 0 24 26" aria-hidden="true"><path d="${path}"/></svg>${name}</button>`).join('');
$('#swatches').innerHTML=['#70b69b','#d5b27b','#eb906a','#748fbb','#e5dfc8','#a687b8','#3c5751','#f0bd3f'].map(c=>`<button style="--swatch:${c}" data-color="${c}" aria-label="Apply ${c}"></button>`).join('');
function toast(s,ms=4000){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),ms);}
function savePrefs(){try{localStorage.setItem(KEY+'-prefs',JSON.stringify(prefs));}catch{}}
function applyPrefs(){document.body.dataset.theme=prefs.theme;document.body.classList.toggle('advancedMode',prefs.advanced);document.body.classList.toggle('panelClosed',!prefs.panel);$('#mode').textContent=prefs.advanced?'Advanced':'Easy';$('#mode').setAttribute('aria-pressed',String(prefs.advanced));$('#plane').value=prefs.plane;$('#elevation').value=prefs.elevation;$('#gridSize').value=prefs.grid;$('#snap').checked=prefs.snap;$('#newColor').value=prefs.color;$('#panelToggle').setAttribute('aria-expanded',String(prefs.panel));resize();}
function snapshot(){return JSON.stringify(doc);}
function edit(fn){const before=snapshot(),oldSelected=[...selected],oldFace=clone(selectedFace);try{fn();if(doc.objects.length>1000||doc.objects.reduce((s,o)=>s+o.vertices.length,0)>150000)throw Error('Model size limit reached: 1,000 objects or 150,000 vertices.');history.push(before);if(history.length>50)history.shift();future=[];changed();return true;}catch(e){doc=JSON.parse(before);selected=new Set(oldSelected);selectedFace=oldFace;toast(e.message,7000);sync();return false;}}
function changed(){doc.version=VERSION;dirty=true;$('#saveState').textContent='Unsaved';$('#saveState').className='dirty';clearTimeout(saveTimer);saveTimer=setTimeout(save,250);sync();}
function sync(){selected=new Set([...selected].filter(i=>doc.objects.some(o=>o.id===i&&objectVisible(o))));if(!selected.size)selectedFace=null;$('#projectName').value=doc.name;$('#objectCount').textContent=doc.objects.length+' object'+(doc.objects.length===1?'':'s');$('#empty').hidden=doc.objects.length>0||tool!=='select';$('[data-action=undo]').disabled=!history.length;$('[data-action=redo]').disabled=!future.length;updateObjects();updateInspector();render();}
function makeObject(name,mesh,color=prefs.color){return {id:id(),name,color,visible:true,locked:false,group:null,...mesh};}
function addObject(name,mesh,color){const o=makeObject(name,mesh,color);doc.objects.push(o);selected=new Set([o.id]);selectedFace=mesh.faces.length?{id:o.id,face:0}:null;return o;}
function chosen(){return doc.objects.filter(o=>selected.has(o.id));}
function editable(){return chosen().filter(o=>!o.locked);}
function undo(redo=false){const from=redo?future:history,to=redo?history:future;if(!from.length)return;to.push(snapshot());doc=JSON.parse(from.pop());selected.clear();selectedFace=null;points=[];changed();toast(redo?'Redone':'Undone');}
function transaction(mode,fn){return new Promise((resolve,reject)=>{const tx=db.transaction('models',mode);fn(tx.objectStore('models'));tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}
async function save(){if(!dirty)return;if(conflict){$('#saveState').textContent='Another tab saved · export a backup';$('#saveState').className='error';return;}const data=clone(doc),json=JSON.stringify(data);$('#saveState').textContent='Saving…';saveQueue=saveQueue.catch(()=>{}).then(async()=>{try{if(db){await transaction('readwrite',store=>{if(savedSnapshot)store.put(savedSnapshot,'recovery');store.put(data,'current');});}else{if(savedSnapshot)localStorage.setItem(KEY+'-recovery',JSON.stringify(savedSnapshot));localStorage.setItem(KEY, json);}savedSnapshot=data;if(snapshot()===json)dirty=false;$('#saveState').textContent=dirty?'Unsaved':'Saved locally';$('#saveState').className=dirty?'dirty':'saved';try{localStorage.setItem(KEY+'-ping',Date.now()+':'+tabId);}catch{}}catch(e){$('#saveState').textContent='Save failed · export project';$('#saveState').className='error';toast('Browser storage could not save. Export your project now to keep your work.',8000);}});await saveQueue;}
const tabId=id();window.addEventListener('storage',e=>{if(e.key!==KEY+'-ping'||!e.newValue)return;try{const p=JSON.parse(e.newValue);if(p.tab!==tabId&&p.project===doc.projectId){conflict=true;$('#saveState').textContent='Other tab changed this project';$('#saveState').className='error';toast('Another tab saved this project. Export your changes, then reload before editing further.',10000);}}catch{}});
window.addEventListener('beforeunload',e=>{if(dirty){save();e.preventDefault();e.returnValue='';}});document.addEventListener('visibilitychange',()=>{if(document.hidden)save();});
function validateProject(d){if(d?.app!=='SKETCHBENCH'||d.schema!==1||d.units!=='mm'||!Array.isArray(d.objects)||d.objects.length>1000)throw Error('This is not a supported SKETCHBENCH schema 1 project in millimeters.');let total=0;const ids=new Set();const objects=d.objects.map(o=>{K.validateMesh(o);total+=o.vertices.length;if(total>150000)throw Error('Project exceeds 150,000 vertices.');const oid=typeof o.id==='string'&&o.id.length<100&&!ids.has(o.id)?o.id:id();ids.add(oid);return {id:oid,name:String(o.name||'Object').slice(0,80),color:/^#[a-f\d]{6}$/i.test(o.color)?o.color:'#70b69b',visible:o.visible!==false,locked:!!o.locked,group:typeof o.group==='string'?o.group.slice(0,100):null,vertices:clone(o.vertices),faces:clone(o.faces),edges:clone(o.edges||[])};});return {app:'SKETCHBENCH',schema:1,version:VERSION,name:String(d.name||'Imported model').slice(0,80),units:'mm',objects};}
async function load(){try{db=await new Promise((resolve,reject)=>{const req=indexedDB.open(KEY,1);req.onupgradeneeded=()=>req.result.createObjectStore('models');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);req.onblocked=()=>reject(Error('Storage blocked'));});}catch{db=null;}try{const value=db?await readStore('current'):JSON.parse(localStorage.getItem(KEY)||'null');if(value){doc=validateProject(value);savedSnapshot=clone(doc);fit();}}catch(e){toast('Saved model could not be opened. File → Restore previous save may recover it.',12000);$('#saveState').textContent='Recovery needed';$('#saveState').className='error';}applyPrefs();setTool('select');sync();}
function readStore(key){return new Promise((resolve,reject)=>{const q=db.transaction('models').objectStore('models').get(key);q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error);});}
// Wrap complete turns without clamping pitch; the basis stays continuous at either pole.
function wrapOrbitAngle(angle){const turn=2*Math.PI;return ((angle+Math.PI)%turn+turn)%turn-Math.PI;}
function basis(){const back=[Math.sin(camera.az)*Math.cos(camera.el),Math.cos(camera.az)*Math.cos(camera.el),Math.sin(camera.el)],right=[Math.cos(camera.az),-Math.sin(camera.az),0],up=V.cross(back,right);return {back,right,up};}
function project(p){const q=V.sub(p,camera.target),b=basis();return [width/2+V.dot(q,b.right)*camera.scale,height/2-V.dot(q,b.up)*camera.scale,V.dot(q,b.back)];}
function planePoint(x,y){const b=basis(),q=V.add(camera.target,V.add(V.mul(b.right,(x-width/2)/camera.scale),V.mul(b.up,-(y-height/2)/camera.scale))),axis=prefs.plane==='xy'?2:prefs.plane==='xz'?1:0;if(Math.abs(b.back[axis])<.0001)return null;return V.add(q,V.mul(b.back,(prefs.elevation-q[axis])/b.back[axis]));}
function pointerPoint(x,y,vertices=true){if(vertices&&prefs.snap){let best=null,d=12;for(const o of doc.objects.filter(o=>objectVisible(o)))for(const p of o.vertices){const s=project(p),dist=Math.hypot(s[0]-x,s[1]-y);if(dist<d){d=dist;best=p;}}if(best)return best.slice();}let p=planePoint(x,y);if(p&&prefs.snap)p=p.map((v,i)=>i===(prefs.plane==='xy'?2:prefs.plane==='xz'?1:0)?prefs.elevation:Math.round(v/prefs.grid)*prefs.grid);return p;}
function planeAxes(){return prefs.plane==='xy'?[0,1]:prefs.plane==='xz'?[0,2]:[1,2];}
function planeNormal(){return prefs.plane==='xy'?[0,0,1]:prefs.plane==='xz'?[0,-1,0]:[1,0,0];}
function resize(){const r=stage.getBoundingClientRect();width=r.width;height=r.height;dpr=Math.min(devicePixelRatio||1,2);for(const c of [canvas,overlay]){c.width=width*dpr;c.height=height*dpr;}ctx.setTransform(dpr,0,0,dpr,0,0);if(gl)gl.viewport(0,0,canvas.width,canvas.height);render();}
function initGL(){try{gl=canvas.getContext('webgl',{antialias:true,preserveDrawingBuffer:true,alpha:false});if(!gl)throw Error();const vs='attribute vec3 p;attribute vec3 c;varying vec3 col;void main(){gl_Position=vec4(p,1.0);col=c;}',fs='precision mediump float;varying vec3 col;void main(){gl_FragColor=vec4(col,1.0);}';const program=gl.createProgram();for(const [type,src]of[[gl.VERTEX_SHADER,vs],[gl.FRAGMENT_SHADER,fs]]){const sh=gl.createShader(type);gl.shaderSource(sh,src);gl.compileShader(sh);if(!gl.getShaderParameter(sh,gl.COMPILE_STATUS))throw Error('Shader failed');gl.attachShader(program,sh);}gl.linkProgram(program);gl.useProgram(program);gpu={program,buffer:gl.createBuffer(),p:gl.getAttribLocation(program,'p'),c:gl.getAttribLocation(program,'c')};gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();toast('3D display paused. Export your project, then reload to restore the graphics context.',10000);});canvas.addEventListener('webglcontextrestored',()=>location.reload());}catch{gl=null;fallback=canvas.getContext('2d');}}
function rgb(hex){return [1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255);}
function hexColor(name){return getComputedStyle(document.body).getPropertyValue(name).trim();}
function line2(c,a,b,color,w=1){c.strokeStyle=color;c.lineWidth=w;c.beginPath();c.moveTo(a[0],a[1]);c.lineTo(b[0],b[1]);c.stroke();}
function batchGL(arr,type){if(!arr.length)return;gl.bindBuffer(gl.ARRAY_BUFFER,gpu.buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(arr),gl.DYNAMIC_DRAW);gl.enableVertexAttribArray(gpu.p);gl.vertexAttribPointer(gpu.p,3,gl.FLOAT,false,24,0);gl.enableVertexAttribArray(gpu.c);gl.vertexAttribPointer(gpu.c,3,gl.FLOAT,false,24,12);gl.drawArrays(type,0,arr.length/6);}
function render(){if(!width||!height)return;const b=basis(),bg=hexColor('--stage'),dark=prefs.theme!=='light',gridColor=dark?'#3d4c42':'#d5dbcf',tri=[],lines=[],depth=Math.max(10000, V.len(K.bounds(doc.objects).size)+V.len(camera.target))*3;drawn=[];edgeHits=[];
function vert(p,col,arr){const s=project(p);arr.push((s[0]/width)*2-1,1-s[1]/height*2,-s[2]/depth,...col);}
function addLine(a,c,color){const cc=rgb(color);vert(a,cc,lines);vert(c,cc,lines);if(fallback)line2(fallback,project(a),project(c),color);}
if(gl){const cc=rgb(bg);gl.clearColor(...cc,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);}if(fallback){fallback.setTransform(dpr,0,0,dpr,0,0);fallback.fillStyle=bg;fallback.fillRect(0,0,width,height);}
const grid=Math.max(prefs.grid,Math.pow(10,Math.ceil(Math.log10(18/camera.scale)))),range=Math.min(100000,Math.max(width,height)/camera.scale*1.2),wf=workFrame(),ct=K.local(camera.target,wf),startI=Math.floor((ct[0]-range)/grid)*grid,endI=ct[0]+range,startJ=Math.floor((ct[1]-range)/grid)*grid,endJ=ct[1]+range;
for(let i=startI;i<endI;i+=grid)addLine(K.world([i,startJ,0],wf),K.world([i,endJ,0],wf),gridColor);
for(let j=startJ;j<endJ;j+=grid)addLine(K.world([startI,j,0],wf),K.world([endI,j,0],wf),gridColor);
for(let axis=0;axis<3;axis++){let a=[0,0,0],c=[0,0,0];a[axis]=-range;c[axis]=range;addLine(a,c,['#c97669','#6c9d78','#7095bc'][axis]);}// Workplane guides are a backdrop, including when viewed from below or through a face plane.
// Do not let their depth prevent opaque model fragments from covering them.
if(gl){gl.depthMask(false);batchGL(lines,gl.LINES);gl.depthMask(true);lines.length=0;}
const visible=doc.objects.filter(o=>objectVisible(o));for(const o of visible){let color=rgb(o.color);for(const t of K.triangles(o)){const ps=t.points.map(project),n=K.normal(o.vertices,o.faces[t.face]),light=renderMode==='solid'?1:.5+.5*Math.max(0,V.dot(n,V.unit([.4,-.6,1])));const col=color.map(c=>Math.min(1,c*light));drawn.push({o,face:t.face,ps,depth:ps.reduce((s,p)=>s+p[2],0)/3,color:col});if(renderMode!=='wire')for(const p of t.points)vert(p,col,tri);}for(const [a,c]of K.edges(o)){const aa=project(o.vertices[a]),bb=project(o.vertices[c]);edgeHits.push({o,a:aa,b:bb});if(gl){vert(o.vertices[a],rgb(selected.has(o.id)?'#df824c':dark?'#b6cbb5':'#3e5448'),lines);vert(o.vertices[c],rgb(selected.has(o.id)?'#df824c':dark?'#b6cbb5':'#3e5448'),lines);}}}
if(gl){gl.enable(gl.POLYGON_OFFSET_FILL);gl.polygonOffset(1,1);batchGL(tri,gl.TRIANGLES);gl.disable(gl.POLYGON_OFFSET_FILL);batchGL(lines,gl.LINES);}else if(fallback){drawn.sort((a,b)=>a.depth-b.depth);for(const t of drawn){if(renderMode==='wire')continue;fallback.fillStyle=`rgb(${t.color.map(x=>Math.round(x*255)).join(',')})`;fallback.beginPath();t.ps.forEach((p,i)=>i?fallback.lineTo(p[0],p[1]):fallback.moveTo(p[0],p[1]));fallback.closePath();fallback.fill();fallback.strokeStyle=dark?'#70907f':'#435b4e';fallback.lineWidth=.6;fallback.stroke();}for(const e of edgeHits)if(renderMode==='wire'||!e.o.faces.length)line2(fallback,e.a,e.b,selected.has(e.o.id)?'#dc8050':'#5d8071');}
ctx.clearRect(0,0,width,height);if(selectedFace){const o=doc.objects.find(o=>o.id===selectedFace.id),f=o?.faces[selectedFace.face];if(f&&objectVisible(o)){const ps=f.map(i=>project(o.vertices[i]));ctx.beginPath();ps.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.closePath();ctx.fillStyle='#fbbd5940';ctx.fill();ctx.strokeStyle=dark?'#ffb773':'#cc652a';ctx.lineWidth=2;ctx.stroke();}}
if(selected.size){const bb=K.bounds(chosen().filter(o=>objectVisible(o))),a=project(bb.lo);ctx.fillStyle=dark?'#ffb773':'#a34d23';ctx.font='10px system-ui';ctx.fillText(`${bb.size.map(n=>fmt(n)).join(' × ')} mm`,a[0]+6,a[1]+19);}
const preview=previewPoints();if(preview.length){ctx.setLineDash([5,4]);ctx.strokeStyle=dark?'#d4f2a3':'#286849';ctx.lineWidth=2;ctx.beginPath();preview.map(project).forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));if(['rectangle','circle','polygon'].includes(tool)&&preview.length>2)ctx.closePath();ctx.stroke();ctx.setLineDash([]);for(const p of points){const s=project(p);ctx.fillStyle=dark?'#d4f2a3':'#286849';ctx.beginPath();ctx.arc(s[0],s[1],4,0,Math.PI*2);ctx.fill();}}
if(hover&&['rectangle','circle','polygon','line','measure'].includes(tool)){const p=project(hover);ctx.strokeStyle=dark?'#fff':'#173d35';ctx.lineWidth=1;ctx.strokeRect(p[0]-4,p[1]-4,8,8);}
if(measure){const [a,c]=measure.map(project),distance=V.len(V.sub(...measure));line2(ctx,a,c,'#d46635',2);ctx.fillStyle=hexColor('--panel');const text=fmt(distance)+' mm';ctx.font='bold 12px system-ui';const w=ctx.measureText(text).width;ctx.fillRect((a[0]+c[0])/2-4,(a[1]+c[1])/2-20,w+10,23);ctx.fillStyle=hexColor('--ink');ctx.fillText(text,(a[0]+c[0])/2,(a[1]+c[1])/2-4);}
// Always-visible axis triad keeps spatial orientation legible.
const o=[width-57,height-93];for(const [axis,label,color]of[[0,'X','#bb6259'],[1,'Y','#598867'],[2,'Z','#6488b2']]){let v=[0,0,0];v[axis]=25;const end=[o[0]+V.dot(v,b.right),o[1]-V.dot(v,b.up)];line2(ctx,o,end,color,2);ctx.fillStyle=color;ctx.font='10px system-ui';ctx.fillText(label,end[0]+3,end[1]-3);}
$('#zoomLabel').textContent=Math.round(camera.scale/2.8*100)+'%';}
function fmt(n){return Number(n.toFixed(2)).toLocaleString('en-US',{maximumFractionDigits:2});}
function previewPoints(){if(!points.length)return [];if(!hover)return points;if(tool==='rectangle')return rectPoints(points[0],hover);if(tool==='circle')return circlePoints(points[0],hover);return [...points,hover];}
function rectPoints(a,b){const [i,j]=planeAxes(),c=a.slice(),d=b.slice();c[i]=b[i];d[i]=a[i];return [a,c,b,d];}
function circlePoints(a,b){const [i,j]=planeAxes(),r=Math.hypot(b[i]-a[i],b[j]-a[j]);return Array.from({length:48},(_,k)=>{const p=a.slice(),t=k/48*Math.PI*2;p[i]+=Math.cos(t)*r;p[j]+=Math.sin(t)*r;return p;});}
function orientProfile(ps){const m=K.profile(ps);if(V.dot(K.normal(m.vertices,m.faces[0]),planeNormal())<0)m.faces[0].reverse();return m;}
function fit(){const b=K.bounds(doc.objects.filter(o=>objectVisible(o)));camera.target=b.center;camera.scale=doc.objects.length?Math.min(width,height)*.65/Math.max(V.len(b.size),20):2.8;camera.scale=Math.max(.01,Math.min(80,camera.scale));render();}
function setView(view){if(view==='top'){camera.az=0;camera.el=Math.PI/2;}if(view==='front'){camera.az=Math.PI;camera.el=0;}if(view==='right'){camera.az=Math.PI/2;camera.el=0;}if(view==='iso'){camera.az=.75;camera.el=.6;}$('#viewLabel').textContent=view==='iso'?'ISOMETRIC':view.toUpperCase();$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));render();}
function hit(x,y){let best=null;for(const t of drawn){const [a,b,c]=t.ps,den=(b[1]-c[1])*(a[0]-c[0])+(c[0]-b[0])*(a[1]-c[1]);if(Math.abs(den)<1e-8)continue;const u=((b[1]-c[1])*(x-c[0])+(c[0]-b[0])*(y-c[1]))/den,v=((c[1]-a[1])*(x-c[0])+(a[0]-c[0])*(y-c[1]))/den,w=1-u-v;if(u>=-.0001&&v>=-.0001&&w>=-.0001){const depth=u*a[2]+v*b[2]+w*c[2];if(!best||depth>best.depth)best={o:t.o,face:t.face,depth};}}
if(!best)for(const e of edgeHits){const dx=e.b[0]-e.a[0],dy=e.b[1]-e.a[1],t=Math.max(0,Math.min(1,((x-e.a[0])*dx+(y-e.a[1])*dy)/(dx*dx+dy*dy||1)));if(Math.hypot(x-e.a[0]-t*dx,y-e.a[1]-t*dy)<6)best={o:e.o,face:null,depth:0};}return best;}
function selectHit(h,add=false){if(!h){if(!add)selected.clear();selectedFace=null;}else{const ids=h.o.group?doc.objects.filter(o=>o.group===h.o.group).map(o=>o.id):[h.o.id];if(!add)selected.clear();for(const i of ids){if(add&&selected.has(i))selected.delete(i);else selected.add(i);}selectedFace=h.face!==null&&selected.has(h.o.id)?{id:h.o.id,face:h.face}:null;}sync();}
function setTool(key){if(gesture)endGesture(true);tool=key;points=[];hover=null;gesture=null;$$('#tools button').forEach(b=>{b.classList.toggle('active',b.dataset.tool===key);b.setAttribute('aria-pressed',b.dataset.tool===key?'true':'false');});$('#activeTool').textContent=toolDefs.find(t=>t[0]===key)?.[1]||key;$('#toolHint').textContent=hints[key];stage.style.cursor=key==='orbit'||key==='pan'?'grab':key==='select'?'default':'crosshair';$('#finish').hidden=true;$('#cancel').hidden=true;$('#empty').hidden=doc.objects.length>0||key!=='select';render();}
function pointer(e){const r=stage.getBoundingClientRect();return [e.clientX-r.left,e.clientY-r.top];}
function newProfile(ps,name){if(!edit(()=>{addObject(name,orientProfile(ps));}))return;points=[];hover=null;setTool('pushpull');toast('Profile created. Drag its face up, or enter a push/pull distance.');}
function finishProfile(){if(tool==='polygon'){if(points.length<3){toast('Add at least three vertices.');return;}try{newProfile(points,'Profile');}catch(e){toast(e.message);}}else if(tool==='line'){if(points.length<2){toast('Add at least two points.');return;}edit(()=>addObject('Line',{vertices:clone(points),faces:[],edges:points.slice(1).map((_,i)=>[i,i+1])}));points=[];setTool('select');}}
function clickDraw(x,y){const p=pointerPoint(x,y,true);if(!p){toast('This work plane is edge-on. Choose 3D or a view facing the plane.');return;}if(tool==='measure'){const pt=pointerPoint(x,y,true);points.push(pt);if(points.length===2){measure=clone(points);points=[];toast('Distance: '+fmt(V.len(V.sub(...measure)))+' mm');}render();return;}
if(tool==='rectangle'||tool==='circle'){if(!points.length){points=[p];$('#cancel').hidden=false;}else if(V.len(V.sub(points[0],p))>.001){if(tool==='rectangle'){const aa=K.local(points[0],workFrame()),bb=K.local(p,workFrame());if(Math.abs(aa[0]-bb[0])<.001||Math.abs(aa[1]-bb[1])<.001){toast('Choose a second corner with width and depth.');return;}}newProfile(tool==='rectangle'?rectPoints(points[0],p):circlePoints(points[0],p),tool==='rectangle'?'Rectangle':'Circle');}}
else if(tool==='line'||tool==='polygon'){if(tool==='polygon'&&points.length>=3){const a=project(points[0]);if(Math.hypot(a[0]-x,a[1]-y)<12){finishProfile();return;}}if(points.length>=1000){toast('Maximum 1,000 points per profile. Finish this outline first.');return;}if(!points.length||V.len(V.sub(points.at(-1),p))>.001)points.push(p);$('#finish').hidden=false;$('#cancel').hidden=false;}render();}
stage.addEventListener('pointerdown',e=>{if(e.target!==canvas&&e.target!==stage)return;stage.focus();$('#contextMenu').hidden=true;const [x,y]=pointer(e);lastPointer=[x,y];lastNavigationDrag=false;if(e.button===2||e.button===1||e.altKey||spaceDown||tool==='orbit'||tool==='pan'){e.preventDefault();gesture={type:e.shiftKey||spaceDown||tool==='pan'?'pan':'orbit',x,y,cam:clone(camera)};stage.setPointerCapture(e.pointerId);return;}if(e.button!==0)return;
if(['rectangle','circle','polygon','line','measure'].includes(tool)){clickDraw(x,y);return;}const h=hit(x,y);if(tool==='select'){selectHit(h,e.shiftKey);return;}if(tool==='pushpull'){if(!h||h.face===null){toast('Click a face to push or pull.');return;}if(objectLocked(h.o)){toast('Unlock this object before editing.');return;}selectHit(h);const normal=K.normal(h.o.vertices,h.o.faces[h.face]),bb=K.bounds([h.o]),a=project(bb.center),c=project(V.add(bb.center,normal));gesture={type:'extrude',x,y,object:h.o.id,face:h.face,original:clone(h.o),normal,screen:[c[0]-a[0],c[1]-a[1]],before:snapshot(),distance:0};stage.setPointerCapture(e.pointerId);}if(tool==='move'){if(!h){selected.clear();sync();return;}if(!selected.has(h.o.id))selectHit(h);if(!editable().length){toast('Unlock the selection before moving it.');return;}const p=planePoint(x,y);if(!p){toast('Choose a view facing the work plane.');return;}gesture={type:'move',x,y,start:p,before:snapshot(),originals:clone(editable())};stage.setPointerCapture(e.pointerId);}});
stage.addEventListener('pointermove',e=>{const [x,y]=pointer(e);lastPointer=[x,y];if(gesture){const g=gesture,dx=x-g.x,dy=y-g.y;if((g.type==='orbit'||g.type==='pan')&&Math.hypot(dx,dy)>4)lastNavigationDrag=true;if(g.type==='orbit'){camera.az=wrapOrbitAngle(g.cam.az-dx*.008);camera.el=wrapOrbitAngle(g.cam.el+dy*.008);$('#viewLabel').textContent='ORBIT';$$('[data-view]').forEach(b=>b.classList.remove('active'));}else if(g.type==='pan'){camera=clone(g.cam);const b=basis();camera.target=V.add(g.cam.target,V.add(V.mul(b.right,-dx/g.cam.scale),V.mul(b.up,dy/g.cam.scale)));}else if(g.type==='extrude'){let [sx,sy]=g.screen;const mag=sx*sx+sy*sy;let d=mag>.05?(dx*sx+dy*sy)/mag:-dy/camera.scale;if(prefs.snap)d=Math.round(d/prefs.grid)*prefs.grid;g.distance=d;const o=doc.objects.find(o=>o.id===g.object);try{g.error=null;const m=Math.abs(d)>.0001?K.extrude(g.original,g.face,d):clone(g.original);Object.assign(o,m);if(g.original.faces.length===1&&Math.abs(d)>.0001)selectedFace={id:o.id,face:1};$('#extrudeDistance').value=fmt(d).replaceAll(',','');}catch(e){g.error=e.message;Object.assign(o,clone(g.original));} ;}else if(g.type==='move'){let p=planePoint(x,y);if(p){let delta=V.sub(p,g.start);if(prefs.snap){const wf=workFrame();delta=V.add(V.mul(wf.u,Math.round(V.dot(delta,wf.u)/prefs.grid)*prefs.grid),V.mul(wf.v,Math.round(V.dot(delta,wf.v)/prefs.grid)*prefs.grid));}for(const original of g.originals){let o=doc.objects.find(o=>o.id===original.id);o.vertices=original.vertices.map(p=>V.add(p,delta));}}}render();return;}
hover=pointerPoint(x,y,tool==='measure');if(hover)$('#coordinates').textContent=hover.map((n,i)=>['X','Y','Z'][i]+' '+fmt(n)).join(' · ')+' mm';if(points.length||['rectangle','circle','polygon','line','measure'].includes(tool))render();});
function endGesture(cancel=false){if(!gesture)return;const g=gesture;gesture=null;if(g.error){toast(g.error,7000);}if(g.before){if(cancel){doc=JSON.parse(g.before);if(selectedFace&&!doc.objects.find(o=>o.id===selectedFace.id)?.faces[selectedFace.face])selectedFace=null;sync();return;}if(snapshot()!==g.before){history.push(g.before);if(history.length>50)history.shift();future=[];changed();}else updateInspector();}render();}
stage.addEventListener('pointerup',()=>endGesture());stage.addEventListener('pointercancel',()=>endGesture(true));stage.addEventListener('dblclick',()=>{if(tool==='line'||tool==='polygon')finishProfile();});stage.addEventListener('wheel',e=>{e.preventDefault();camera.scale=Math.max(.01,Math.min(150,camera.scale*Math.exp(-e.deltaY*.001)));render();},{passive:false});
stage.addEventListener('contextmenu',e=>{e.preventDefault();if(tool!=='select'||lastNavigationDrag)return;const [x,y]=pointer(e),h=hit(x,y);if(h&&!selected.has(h.o.id))selectHit(h);const m=$('#contextMenu');m.style.left=Math.min(innerWidth-180,e.clientX)+'px';m.style.top=Math.min(innerHeight-170,e.clientY)+'px';m.hidden=false;m.querySelector('button').focus();});
function updateObjects(){const q=$('#objectSearch').value.toLowerCase();$('#objects').replaceChildren();for(const o of [...doc.objects].reverse().filter(o=>o.name.toLowerCase().includes(q))){const row=document.createElement('div');row.className='objectRow'+(selected.has(o.id)?' selected':'')+(!o.visible?' hiddenObject':'');const btn=document.createElement('button');btn.className='objectSelect';btn.innerHTML=`<span class="dot" style="--swatch:${o.color}"></span>${esc(o.name)}${o.group?' ⊞':''}`;btn.title=o.name;btn.setAttribute('aria-pressed',String(selected.has(o.id)));btn.onclick=e=>selectHit({o,face:null},e.shiftKey);row.append(btn);for(const [key,on,off]of[['visible','◉','○'],['locked','▣','□']]){const b=document.createElement('button');b.textContent=o[key]?on:off;b.title=(key==='visible'?(o.visible?'Hide ':'Show '):(o.locked?'Unlock ':'Lock '))+o.name;b.setAttribute('aria-label',b.title);b.onclick=()=>edit(()=>o[key]=!o[key]);row.append(b);}$('#objects').append(row);}if(!doc.objects.length)$('#objects').innerHTML='<p class="muted">Your profiles and solids will appear here.</p>';}
function updateInspector(){const os=chosen(),es=editable();$('#selectionCount').textContent=os.length?os.length+' selected'+(os.length-es.length?' · '+(os.length-es.length)+' locked':''):'none';$('#selectionEmpty').hidden=!!os.length;$('#selectionControls').hidden=!os.length;if(!os.length)return;const b=K.bounds(es.length?es:os);$('#objectName').value=os.length===1?os[0].name:os.length+' objects';$('#objectName').disabled=os.length!==1||!es.length;$$('[data-pos]').forEach(e=>{e.value=Number(b.lo[+e.dataset.pos].toFixed(3));e.disabled=!es.length;});$$('[data-size]').forEach(e=>{e.value=Number(b.size[+e.dataset.size].toFixed(3));e.disabled=!es.length||b.size[+e.dataset.size]<.00001;});$('#objectColor').value=os[0].color;$('#objectColor').disabled=!es.length;const faceObj=doc.objects.find(o=>o.id===selectedFace?.id);$('#applyExtrude').disabled=!faceObj||objectLocked(faceObj);$('#faceHint').textContent=faceObj?objectLocked(faceObj)?'Object is locked.':'Selected face '+(selectedFace.face+1)+' · positive follows its normal.':'Select a face in the viewport to extrude.';try{const ss=os.map(K.stats),closed=ss.every(s=>s.closed);$('#meshStats').textContent=os.reduce((s,o)=>s+o.faces.length,0)+' faces · '+ss.reduce((s,x)=>s+x.triangles,0)+' triangles · '+(closed?'Closed surfaces; overlaps not checked':'Open surface / linework')+(closed?' · '+fmt(ss.reduce((s,x)=>s+x.volume,0))+' mm³':'');}catch{$('#meshStats').textContent='Geometry needs repair before export.';}}
function shiftObjects(delta){for(const o of editable())K.transform(o,p=>V.add(p,delta));}
function duplicate(){if(!selected.size){toast('Select an object first.');return;}edit(()=>{const ids=[],groups=new Map();for(const o of chosen()){const n=clone(o);n.id=id();n.name+=' copy';n.locked=false;if(n.group){if(!groups.has(n.group))groups.set(n.group,id());n.group=groups.get(n.group);}K.transform(n,p=>V.add(p,[prefs.grid,prefs.grid,0]));doc.objects.push(n);ids.push(n.id);}selected=new Set(ids);selectedFace=null;});}
function remove(){if(!editable().length){toast('Select an unlocked object first.');return;}edit(()=>{const ids=new Set(editable().map(o=>o.id));doc.objects=doc.objects.filter(o=>!ids.has(o.id));selected.clear();selectedFace=null;});}
function applyExtrude(){const o=doc.objects.find(o=>o.id===selectedFace?.id),d=Number($('#extrudeDistance').value);if(!o||objectLocked(o))return;edit(()=>{const wasFlat=o.faces.length===1;Object.assign(o,K.extrude(o,selectedFace.face,d));if(wasFlat)selectedFace.face=1;});}
function download(content,name,type='application/octet-stream'){const blob=content instanceof Blob?content:new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);toast('Download prepared: '+name);}
function filename(){return (doc.name.replace(/[^a-z0-9 _-]/gi,'').trim()||'model').replace(/\s+/g,'-');}
function saveProject(){download(JSON.stringify({...doc,exportedAt:new Date().toISOString()},null,2),filename()+'.sketchbench.json','application/json');}
function modal(title,html){if($('#dialog').open)$('#dialog').close();$('#dialogTitle').textContent=title;$('#dialogBody').innerHTML=html;$('#dialog').showModal();}
function closeDialog(){$('#dialog').close();}
function actionButton(action,label,help=''){return `<button data-action="${action}">${label}${help?'<small>'+help+'</small>':''}</button>`;}
function fileMenu(){modal('Your model, your files',`<div class="actionlist">${actionButton('new','New model','Save the current project and create a new empty project.')}${actionButton('open','Open / import','JSON projects, STL, OBJ + MTL, or GLB. STL/OBJ imports assume millimeters.')}${actionButton('saveProject','Save project','Download an editable project backup with all objects and metadata.')}${actionButton('recover','Restore previous save','Recover the autosave immediately before the latest one.')}${actionButton('sample','Example models','Open a bracket, enclosure, or furniture assembly as a new project.')}</div><p>Autosave stays in this browser on this device and site. It does not write to your server or synchronize devices.</p>`);}
function exportMenu(){modal('Take it to the bench',`<p>Model exports include ${selected.size?'the selected visible objects':'all visible objects'}. Project backups always include the whole model.</p><div class="actionlist">${actionButton('saveProject','Editable project · JSON','The reliable way to continue editing later.')}${actionButton('stl','3D printing mesh · STL','Triangulated surfaces in millimeters; check overlaps in your slicer.')}${actionButton('obj','Mesh interchange · OBJ','Faces and lines; material colors are not included.')}${actionButton('png','Viewport image · PNG','The current view without interface controls.')}${actionButton('print','Model sheet · Print / PDF','Current view, dimensions, and object inventory.')}</div>`);}
function exportObjects(){return doc.objects.filter(o=>objectVisible(o)&&(!selected.size||selected.has(o.id)));}
function imageBlob(callback){const c=document.createElement('canvas');c.width=canvas.width;c.height=canvas.height;const cc=c.getContext('2d');render();cc.drawImage(canvas,0,0);c.toBlob(callback,'image/png');}
function output(format){const os=exportObjects();if(!os.length){toast('There are no visible objects to export.');return;}try{if(format==='stl'){if(os.every(o=>!o.faces.length))throw Error('STL needs faces. Close a profile and extrude it first.');const open=os.filter(o=>!K.stats(o).closed);if(open.length){modal('Open surfaces in STL',`<p>${open.length} object(s) contain open surfaces or linework. These may not print as solids. STL omits lines. You can still export for inspection.</p><div class="inline"><button data-action="closeDialog">Go back</button><button class="primary" id="confirmSTL">Export surfaces</button></div>`);$('#confirmSTL').onclick=()=>{download(K.stl(os),filename()+'.stl');closeDialog();};return;}download(K.stl(os),filename()+'.stl');}if(format==='obj')download(K.obj(os),filename()+'.obj','text/plain');if(format==='png')imageBlob(b=>b?download(b,filename()+'.png'):toast('Image export failed. Try a smaller viewport.'));if(format==='print')printModel();if(format!=='print')closeDialog();}catch(e){toast(e.message,7000);}}
function printModel(){closeDialog();render();let image=canvas.toDataURL('image/png'),os=doc.objects.filter(o=>objectVisible(o));$('#printSheet').innerHTML=`<h1>${esc(doc.name)}</h1><p>SKETCHBENCH ${VERSION} · ${new Date().toLocaleDateString()} · Dimensions in millimeters</p><img src="${image}" alt="Model view"><table><thead><tr><th>Object</th><th>Size X × Y × Z (mm)</th><th>Surface</th></tr></thead><tbody>${os.map(o=>`<tr><td>${esc(o.name)}</td><td>${K.bounds([o]).size.map(fmt).join(' × ')}</td><td>${K.stats(o).closed?'Closed':'Open / linework'}</td></tr>`).join('')}</tbody></table><p>Concept mesh model. Closed surfaces do not guarantee a printable assembly: overlapping parts and self-intersections require inspection in a slicer.</p><small>Green Shoe Garage · SKETCH → SHAPE → ARRANGE → EXPORT</small>`;const img=$('#printSheet img');const go=()=>{window.print();};if(img.complete)go();else img.onload=go;}
function primitiveDialog(){modal('Add a solid',`<p>Start with a solid, then select faces to reshape it.</p><label>Shape<select id="primitiveType"><option value="box">Box</option><option value="cylinder">Cylinder</option><option value="cone">Cone</option><option value="sphere">Sphere</option><option value="torus">Torus</option></select></label><div class="formgrid three"><label id="widthLabel">Width (mm)<input id="pw" type="number" value="80" min="0.1" max="100000"></label><label id="depthLabel">Depth (mm)<input id="pd" type="number" value="60" min="0.1" max="100000"></label><label id="heightLabel">Height (mm)<input id="ph" type="number" value="40" min="0.1" max="100000"></label></div><div id="roundFields" hidden><label>Radius (mm)<input id="pr" type="number" min="0.1" value="25"></label><label id="tubeLabel" hidden>Tube radius (mm)<input id="pt" type="number" min="0.1" value="8"></label><label>Radial segments<select id="segments"><option>16</option><option selected>32</option><option>64</option></select></label></div><div class="formgrid three"><label>Center X<input id="px" type="number" value="0"></label><label>Center Y<input id="py" type="number" value="0"></label><label>Base Z<input id="pz" type="number" value="0"></label></div><button class="primary wide" id="insertSolid">Add solid</button>`);$('#primitiveType').onchange=()=>{const t=$('#primitiveType').value;$('#widthLabel').hidden=$('#depthLabel').hidden=t!=='box';$('#heightLabel').hidden=['sphere','torus'].includes(t);$('#roundFields').hidden=t==='box';$('#tubeLabel').hidden=t!=='torus';};$('#insertSolid').onclick=()=>{try{const t=$('#primitiveType').value,nums=['pw','pd','ph','pr','pt','px','py','pz'].map(s=>Number($('#'+s).value)),[w,d,h,r,tube,x,y,z]=nums,n=Number($('#segments').value);if(nums.some(x=>!Number.isFinite(x)||Math.abs(x)>100000)||[w,d,h,r,tube].some(x=>x<=0))throw Error('Use positive dimensions, with coordinates between −100,000 and 100,000 mm.');if(t==='torus'&&tube>=r)throw Error('Tube radius must be smaller than the main radius.');let m=t==='box'?K.box(w,d,h):t==='cylinder'?K.cylinder(r,h,n):t==='cone'?K.cylinder(r,h,n,0):t==='sphere'?K.sphere(r,n):K.torus(r,tube,n);const bb=K.bounds([m]);K.transform(m,p=>V.add(p,[x-bb.center[0],y-bb.center[1],z-bb.lo[2]]));edit(()=>addObject(t[0].toUpperCase()+t.slice(1),m));setTool('select');closeDialog();fit();}catch(e){toast(e.message,7000);}};}
function confirmReplace(title,fn){if(!doc.objects.length){fn();return;}modal(title,'<p>The current model will be replaced. You can undo this during this session, or save a project backup first.</p><div class="inline"><button data-action="saveProject">Save backup</button><button id="replaceConfirm" class="primary">Replace model</button></div>');$('#replaceConfirm').onclick=()=>{closeDialog();fn();};}
function fresh(){edit(()=>{doc={app:'SKETCHBENCH',schema:1,version:VERSION,name:'Untitled model',units:'mm',objects:[]};selected.clear();selectedFace=null;});measure=null;setTool('select');camera={az:.75,el:.6,scale:2.8,target:[0,0,0]};render();}
function sample(){edit(()=>{doc.objects=[];doc.name='A little workbench';const part=(name,size,pos,color)=>{const m=K.box(...size);K.transform(m,p=>V.add(p,pos));doc.objects.push(makeObject(name,m,color));};part('Oak worktop',[180,100,10],[-90,-50,80],'#d4b079');for(let x of [-78,66])for(let y of [-40,28])part('Green steel leg',[12,12,80],[x,y,0],'#507c66');part('Lower shelf',[156,78,6],[-78,-39,20],'#9bb4a0');part('Sketch block',[38,29,3],[-62,-15,90],'#ede7d2');let cup=K.cylinder(12,24);K.transform(cup,p=>V.add(p,[43,17,90]));doc.objects.push(makeObject('Reference cylinder',cup,'#d78362'));selected.clear();selectedFace=null;});measure=null;setTool('select');setView('iso');fit();toast('Example loaded. Every part is editable. File → New model starts empty.');}
async function importFile(file){if(!file)return;if(file.size>25*1024*1024){toast('File too large. Maximum import size is 25 MB.',7000);return;}try{const ext=file.name.split('.').pop().toLowerCase();if(ext==='json'||ext==='sketchbench'){const d=validateProject(JSON.parse(await file.text()));confirmReplace('Open project?',()=>{edit(()=>{doc=d;selected.clear();selectedFace=null;});setTool('select');fit();closeDialog();toast('Project opened.');});}else{let m=ext==='stl'?K.parseSTL(await file.arrayBuffer()):ext==='obj'?K.parseOBJ(await file.text()):null;if(!m)throw Error('Open a SKETCHBENCH JSON, STL, or OBJ file.');K.validateMesh(m);if(doc.objects.reduce((s,o)=>s+o.vertices.length,0)+m.vertices.length>150000)throw Error('Model would exceed 150,000 vertices.');edit(()=>addObject(file.name.replace(/\.[^.]+$/,''),m));setTool('select');fit();closeDialog();toast('Mesh imported. Coordinates interpreted as millimeters.');}}catch(e){toast('Import rejected: '+e.message,10000);}}
function showHelp(){modal('A line. A face. A thing.',`<p><b>1.</b> Choose Rectangle, Circle, or Profile. Click on the work plane to draw an outline.</p><p><b>2.</b> Choose Push/pull. Drag the face, or enter an exact distance in the inspector and Apply.</p><p><b>3.</b> Select parts to set X/Y/Z position, dimensions, or color. Advanced adds rotation, mirror, arrays, and grouping.</p><p><b>4.</b> Export a project for editing, STL/OBJ for other tools, or a model sheet.</p><div class="kbd"><span><b>V</b> Select</span><span><b>R / C / G</b> Rectangle / Circle / Profile</span><span><b>P</b> Push/pull</span><span><b>M / O / H</b> Move / Orbit / Pan</span><span><b>T</b> Measure</span><span><b>F</b> Fit model</span><span><b>Ctrl/⌘ Z</b> Undo</span><span><b>Ctrl/⌘ D</b> Duplicate</span><span><b>Ctrl/⌘ S</b> Save project</span><span><b>Delete</b> Delete selection</span><span><b>Enter</b> Finish profile</span><span><b>Esc</b> Cancel / Select</span></div><p>Right/middle-drag or Alt-drag orbits; Shift + right-drag pans. On touchscreens use the explicit Orbit and Pan tools. Use the object list and dimension fields for precise keyboard editing. Hold Shift while selecting for multiple objects.</p><p><b>Model boundary:</b> polygon meshes in millimeters. Face push/pull adds geometry; it does not cut or merge intersecting solids. No booleans, fillets, constraints, arbitrary face sketch planes, or native OpenSketch project import in this preview.</p><p><b>Privacy:</b> no accounts, AI, telemetry, remote fonts, or external runtime libraries. The optional service worker caches only this app for offline reload.</p><p><b>Next:</b> v0.2 numeric sketch input and face planes; v0.3 solid operations and mesh diagnostics; v0.4 curves and offsets; v1.0 follows browser acceptance testing.</p><small>SKETCHBENCH ${VERSION} · GPL-3.0-only · Independent Green Shoe Garage implementation.</small>`);}
function arrayDialog(){if(!editable().length){toast('Select an unlocked object first.');return;}modal('Linear array','<p>Make independent copies. Count includes the original.</p><div class="formgrid"><label>Count<input id="arrayCount" type="number" value="3" min="2" max="50"></label><label>Spacing X (mm)<input id="arrayX" type="number" value="50"></label><label>Spacing Y (mm)<input id="arrayY" type="number" value="0"></label><label>Spacing Z (mm)<input id="arrayZ" type="number" value="0"></label></div><button id="applyArray" class="primary wide">Create copies</button>');$('#applyArray').onclick=()=>{let count=Number($('#arrayCount').value),delta=['arrayX','arrayY','arrayZ'].map(s=>Number($('#'+s).value)),os=clone(editable());if(!Number.isInteger(count)||count<2||count>50||delta.some(n=>!Number.isFinite(n)||Math.abs(n)>100000)){toast('Use 2–50 copies and finite spacing.');return;}if(doc.objects.length+os.length*(count-1)>1000||doc.objects.reduce((s,o)=>s+o.vertices.length,0)+os.reduce((s,o)=>s+o.vertices.length,0)*(count-1)>150000){toast('This array exceeds the model size limit.');return;}edit(()=>{for(let i=1;i<count;i++)for(const o of os){const n=clone(o);n.id=id();n.group=null;n.name+=' '+(i+1);K.transform(n,p=>V.add(p,V.mul(delta,i)));doc.objects.push(n);}});closeDialog();fit();};}
const actions={file:fileMenu,export:exportMenu,help:showHelp,primitive:primitiveDialog,closeDialog,undo:()=>undo(),redo:()=>undo(true),fit,zoomIn:()=>{camera.scale=Math.min(150,camera.scale*1.2);render();},zoomOut:()=>{camera.scale=Math.max(.01,camera.scale/1.2);render();},theme:()=>{prefs.theme=['light','dark','contrast'][(['light','dark','contrast'].indexOf(prefs.theme)+1)%3];savePrefs();applyPrefs();},duplicate,delete:remove,finish:finishProfile,cancel:()=>{endGesture(true);setTool('select');},saveProject,open:()=>$('#fileInput').click(),new:()=>confirmReplace('Start a new model?',()=>{fresh();closeDialog();}),sample:()=>confirmReplace('Load the example?',()=>{sample();closeDialog();}),recover:async()=>{try{const d=db?await readStore('recovery'):JSON.parse(localStorage.getItem(KEY+'-recovery')||'null');if(!d){toast('No previous autosave is available yet.');return;}const next=validateProject(d);confirmReplace('Restore the previous save?',()=>{edit(()=>{doc=next;selected.clear();selectedFace=null;});closeDialog();fit();});}catch(e){toast('Recovery failed: '+e.message,7000);}},stl:()=>output('stl'),obj:()=>output('obj'),png:()=>output('png'),print:()=>output('print'),rotate:()=>{const a=Number($('#rotateAngle').value),axis=Number($('#rotateAxis').value);if(!Number.isFinite(a)||!editable().length)return;edit(()=>{const c=K.bounds(editable()).center;for(const o of editable())K.transform(o,p=>K.rotate(p,axis,a,c));});},mirror:()=>{if(!editable().length)return;edit(()=>{const c=K.bounds(editable()).center;for(const o of editable()){K.transform(o,p=>[2*c[0]-p[0],p[1],p[2]]);o.faces.forEach(f=>f.reverse());}});},array:arrayDialog,group:()=>{if(editable().length<2){toast('Select two or more unlocked objects.');return;}edit(()=>{const g=id();for(const o of editable())o.group=g;});toast('Grouped. Selecting one part selects the group.');},ungroup:()=>{if(!editable().length)return;edit(()=>{for(const o of editable())o.group=null;});}};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(b?.dataset.tool){setTool(b.dataset.tool);return;}if(b?.dataset.action){actions[b.dataset.action]?.();$('#contextMenu').hidden=true;}if(b?.dataset.view)setView(b.dataset.view);if(b?.dataset.color&&editable().length)edit(()=>editable().forEach(o=>o.color=b.dataset.color));if(!e.target.closest('#contextMenu'))$('#contextMenu').hidden=true;});
$('#mode').onclick=()=>{prefs.advanced=!prefs.advanced;savePrefs();applyPrefs();};$('#panelToggle').onclick=()=>{prefs.panel=!prefs.panel;savePrefs();applyPrefs();};$('#renderStyle').onclick=()=>{renderMode=renderMode==='shaded'?'solid':renderMode==='solid'?'wire':'shaded';$('#renderStyle').textContent={shaded:'Shaded',solid:'Solid',wire:'Wireframe'}[renderMode];render();};
$('#projectName').onchange=e=>{const name=e.target.value.trim()||'Untitled model';if(name!==doc.name)edit(()=>doc.name=name);};$('#objectName').onchange=e=>{if(editable().length===1)edit(()=>editable()[0].name=e.target.value.trim()||'Object');};$('#objectColor').onchange=e=>edit(()=>editable().forEach(o=>o.color=e.target.value));$('#newColor').oninput=e=>{prefs.color=e.target.value;savePrefs();};$('#applyExtrude').onclick=applyExtrude;
$$('[data-pos]').forEach(e=>e.onchange=()=>{const axis=Number(e.dataset.pos),value=Number(e.value);if(!Number.isFinite(value)||Math.abs(value)>100000){toast('Enter a position between −100,000 and 100,000 mm.');updateInspector();return;}edit(()=>{const delta=[0,0,0];delta[axis]=value-K.bounds(editable()).lo[axis];shiftObjects(delta);});});
$$('[data-size]').forEach(e=>e.onchange=()=>{const axis=Number(e.dataset.size),value=Number(e.value);if(!Number.isFinite(value)||value<=0||value>100000){toast('Enter a size between 0 and 100,000 mm.');updateInspector();return;}edit(()=>{const b=K.bounds(editable()),ratio=value/b.size[axis];for(const o of editable())K.transform(o,p=>p.map((v,i)=>i===axis?b.lo[i]+(v-b.lo[i])*ratio:v));});});
$('#plane').onchange=e=>{prefs.plane=e.target.value;points=[];hover=null;savePrefs();render();};$('#elevation').onchange=e=>{let v=Number(e.target.value);if(Number.isFinite(v)&&Math.abs(v)<100000)prefs.elevation=v;else e.target.value=prefs.elevation;points=[];savePrefs();render();};$('#gridSize').onchange=e=>{let v=Number(e.target.value);if(v>=.1&&v<=1000)prefs.grid=v;else e.target.value=prefs.grid;savePrefs();render();};$('#snap').onchange=e=>{prefs.snap=e.target.checked;savePrefs();};$('#objectSearch').oninput=updateObjects;
$('#fileInput').onchange=e=>{importFile(e.target.files[0]);e.target.value='';};stage.addEventListener('dragover',e=>{e.preventDefault();});stage.addEventListener('drop',e=>{e.preventDefault();importFile(e.dataTransfer.files[0]);});$('#dialog').addEventListener('click',e=>{if(e.target===$('#dialog'))closeDialog();});
let clipboard=[];document.addEventListener('keydown',e=>{if($('#dialog').open)return;if(e.target.matches('input,textarea,select'))return;const key=e.key.toLowerCase(),cmd=e.ctrlKey||e.metaKey;if(cmd&&['s','z','y','d','a','c','v'].includes(key)){e.preventDefault();if(key==='s')saveProject();if(key==='z')undo(e.shiftKey);if(key==='y')undo(true);if(key==='d')duplicate();if(key==='a'){selected=new Set(doc.objects.filter(o=>objectVisible(o)).map(o=>o.id));selectedFace=null;sync();}if(key==='c'){clipboard=clone(chosen());toast('Copied '+clipboard.length+' object(s) within SKETCHBENCH.');}if(key==='v'&&clipboard.length)edit(()=>{selected.clear();for(const o of clipboard){const n=clone(o);n.id=id();n.group=null;n.locked=false;K.transform(n,p=>V.add(p,[prefs.grid,prefs.grid,0]));doc.objects.push(n);selected.add(n.id);}selectedFace=null;});return;}
if(key==='escape'){endGesture(true);$('#contextMenu').hidden=true;setTool('select');measure=null;render();}if(key==='enter'&&points.length){e.preventDefault();finishProfile();}if(key==='delete'||key==='backspace'){e.preventDefault();remove();}if(key==='f')fit();const found=toolDefs.find(t=>t[2].toLowerCase()===key);if(found&&!cmd)setTool(found[0]);if(e.code==='Space'){e.preventDefault();spaceDown=true;}if(key.startsWith('arrow')&&selected.size){e.preventDefault();const d=[0,0,0],v=e.shiftKey?prefs.grid:1;if(key==='arrowleft')d[0]=-v;if(key==='arrowright')d[0]=v;if(key==='arrowup')d[1]=v;if(key==='arrowdown')d[1]=-v;edit(()=>shiftObjects(d));}if(e.shiftKey&&key==='f10'){e.preventDefault();$('#contextMenu').hidden=false;$('#contextMenu').style.left='100px';$('#contextMenu').style.top='150px';$('#contextMenu button').focus();}});document.addEventListener('keyup',e=>{if(e.code==='Space')spaceDown=false;});window.addEventListener('blur',()=>{spaceDown=false;endGesture();});
