/* Hierarchical groups and linked component definitions. GPL-3.0-only. */
let editContext=null;
const identityMatrix=()=>[1,0,0,0,0,1,0,0,0,0,1,0];
const matrixPoint=(m,p)=>[0,1,2].map(i=>m[i*4]*p[0]+m[i*4+1]*p[1]+m[i*4+2]*p[2]+m[i*4+3]);
function matrixFrom(fn){const o=fn([0,0,0]),v=[0,1,2].map(i=>{const a=[0,0,0];a[i]=1;return V.sub(fn(a),o);});return [0,1,2].flatMap(i=>[v[0][i],v[1][i],v[2][i],o[i]]);}
const matrixCompose=(a,b)=>matrixFrom(p=>matrixPoint(a,matrixPoint(b,p)));
function matrixInverse(m){const [a,b,c,,d,e,f,,g,h,i]=m,det=a*(e*i-f*h)-b*(d*i-f*g)+c*(d*h-e*g);if(Math.abs(det)<1e-12)throw Error('Component transform is singular.');const q=[(e*i-f*h)/det,(c*h-b*i)/det,(b*f-c*e)/det,0,(f*g-d*i)/det,(a*i-c*g)/det,(c*d-a*f)/det,0,(d*h-e*g)/det,(b*g-a*h)/det,(a*e-b*d)/det,0];const t=matrixPoint(q,[m[3],m[7],m[11]]);q[3]=-t[0];q[7]=-t[1];q[11]=-t[2];return q;}
function meshPayload(o){const p=clone(o);for(const k of ['id','group','layer','locked','visible','component'])delete p[k];return p;}
function inGroup(o,g){let next=o.group,seen=new Set();while(next&&!seen.has(next)){if(next===g)return true;seen.add(next);next=(doc.groups||[]).find(x=>x.id===next)?.parent;}return false;}
const objectLockedBeforeAssemblies=objectLocked;objectLocked=o=>objectLockedBeforeAssemblies(o)||(editContext&&!(editContext.kind==='component'?o.component?.instance===editContext.id:inGroup(o,editContext.id)));
const transformBeforeAssemblies=K.transform;K.transform=function(o,fn){const c=o.component?clone(o.component):null,result=transformBeforeAssemblies(o,fn);if(c&&!(editContext?.kind==='component'&&editContext.id===c.instance)){c.matrix=matrixCompose(matrixFrom(fn),c.matrix);o.component=c;}return result;};
const editBeforeAssemblies=edit;
edit=function(fn){return editBeforeAssemblies(()=>{
 const existingIDs=new Set(doc.objects.map(o=>o.id)),existingInstances=new Set(doc.objects.map(o=>o.component?.instance).filter(Boolean));
 const sourcesBefore=editContext?.kind==='component'?doc.objects.filter(o=>o.component?.instance===editContext.id).map(clone):[],anchor=sourcesBefore[0]?.component;
 const instances=anchor?new Map(doc.objects.filter(o=>o.component?.definition===anchor.definition).map(o=>[o.component.instance,clone(o.component)])):null;
 fn();
 if(anchor){
  const def=(doc.definitions||[]).find(d=>d.id===anchor.definition);if(!def)return;
  const removed=sourcesBefore.filter(o=>!doc.objects.some(p=>p.id===o.id)).map(o=>o.component.member);
  if(removed.length){def.members=def.members.filter(m=>!removed.includes(m.id));doc.objects=doc.objects.filter(o=>!(o.component?.definition===def.id&&removed.includes(o.component.member)));}
  for(const o of doc.objects.filter(o=>!existingIDs.has(o.id))){o.component={...clone(anchor),member:id()};o.group=anchor.instance;}
  for(const o of doc.objects.filter(o=>o.component?.instance===anchor.instance)){
   const old=sourcesBefore.find(p=>p.id===o.id);if(old&&JSON.stringify(meshPayload(old))===JSON.stringify(meshPayload(o)))continue;
   const c=o.component,local=meshPayload(o);K.transform(local,p=>matrixPoint(matrixInverse(c.matrix),p));let member=def.members.find(m=>m.id===c.member);
   if(member)member.mesh=local;else{member={id:c.member,mesh:local};def.members.push(member);}
   for(const [instance,placement]of instances){if(instance===anchor.instance)continue;const geometry=clone(local);K.transform(geometry,p=>matrixPoint(placement.matrix,p));const other=doc.objects.find(p=>p.component?.instance===instance&&p.component?.member===c.member);
    if(other)Object.assign(other,geometry);else doc.objects.push({...geometry,id:id(),group:instance,layer:o.layer,locked:false,visible:true,component:{...placement,member:c.member}});
   }
  }
 }else{
  const copyInstances=new Map();for(const o of doc.objects){if(existingIDs.has(o.id)||!o.component||!existingInstances.has(o.component.instance))continue;const source=o.component.instance;if(!copyInstances.has(source)){const next=id();copyInstances.set(source,next);doc.groups=doc.groups||[];doc.groups.push({id:next,name:(doc.groups.find(g=>g.id===source)?.name||'Component')+' copy',parent:null});}o.component.instance=copyInstances.get(source);o.group=o.component.instance;}
 }
});};

function componentDialog(){modal('Linked components',`<p>Instances share a definition. Open an instance to edit all linked copies; Make Unique separates it.</p><label>Name<input id="definitionName" value="${esc(chosen()[0]?.name||'Component')}" maxlength="80"></label><button id="defineComponent" class="primary wide">Make selection a linked component</button><div class="inline"><button data-action="openContext">Open selection</button><button data-action="closeContext">Close editing context</button><button data-action="makeUnique">Make unique</button></div>${(doc.definitions||[]).map(d=>`<div class="projectRow"><span>${esc(d.name)}<small>${d.members.length} parts</small></span><button data-definition-insert="${d.id}">Insert</button></div>`).join('')}<button data-action="legacyParts" class="wide">Independent saved parts</button>`);$('#defineComponent').onclick=()=>{const os=editable();if(!os.length)return toast('Select one or more unlocked objects.');edit(()=>{const origin=K.bounds(os).center,definition=id(),instance=id(),matrix=identityMatrix();matrix[3]=origin[0];matrix[7]=origin[1];matrix[11]=origin[2];const members=os.map(o=>{const member=id(),mesh=meshPayload(o);K.transform(mesh,p=>V.sub(p,origin));o.component={definition,instance,member,matrix:clone(matrix)};o.group=instance;return {id:member,mesh};});doc.definitions=doc.definitions||[];doc.definitions.push({id:definition,name:$('#definitionName').value.slice(0,80)||'Component',members});doc.groups=doc.groups||[];doc.groups.push({id:instance,name:$('#definitionName').value||'Component',parent:null});});componentDialog();};$$('[data-definition-insert]').forEach(b=>b.onclick=()=>{const def=doc.definitions.find(d=>d.id===b.dataset.definitionInsert);edit(()=>{const instance=id(),matrix=identityMatrix();matrix[3]=camera.target[0];matrix[7]=camera.target[1];matrix[11]=camera.target[2];selected.clear();for(const member of def.members){const mesh=clone(member.mesh);K.transform(mesh,p=>matrixPoint(matrix,p));const o=makeObject(mesh.name||def.name,mesh,mesh.color);o.group=instance;o.component={instance,definition:def.id,member:member.id,matrix:clone(matrix)};doc.objects.push(o);selected.add(o.id);}doc.groups=doc.groups||[];doc.groups.push({id:instance,name:def.name,parent:null});selectedFace=null;});closeDialog();});}
function openContext(){const o=chosen()[0];if(!o)return toast('Select a group or component.');if(o.component)editContext={kind:'component',id:o.component.instance};else if(o.group)editContext={kind:'group',id:o.group};else return toast('Group the selection first.');selected.clear();selectedFace=null;$('#contextState').textContent=o.component?'Editing linked definition':'Editing group';sync();toast('Editing context opened. Linked component geometry changes update every instance.');}
function closeContext(){editContext=null;$('#contextState').textContent='Model';selected.clear();selectedFace=null;sync();}
function makeUnique(){const o=chosen()[0];if(!o?.component)return toast('Select a component instance.');edit(()=>{const c=o.component,def=clone(doc.definitions.find(d=>d.id===c.definition));def.id=id();def.name+=' unique';doc.definitions.push(def);for(const p of doc.objects.filter(p=>p.component?.instance===c.instance))p.component.definition=def.id;});toast('This instance now has its own definition.');}
const selectBeforeAssemblies=selectHit;selectHit=function(h,add=false){if(!h)return selectBeforeAssemblies(h,add);if(editContext){if(objectLocked(h.o))return;const group=h.o.group;h.o.group=null;selectBeforeAssemblies(h,add);h.o.group=group;return;}if(h.o.group){const root=g=>{let seen=new Set(),p=g;while(p&&!seen.has(p)){seen.add(p);const up=(doc.groups||[]).find(x=>x.id===p)?.parent;if(!up)return p;p=up;}return g;},g=root(h.o.group),members=doc.objects.filter(o=>inGroup(o,g));if(!add)selected.clear();const remove=add&&members.every(o=>selected.has(o.id));members.forEach(o=>remove?selected.delete(o.id):selected.add(o.id));selectedFace=h.face===null?null:{id:h.o.id,face:h.face};sync();return;}selectBeforeAssemblies(h,add);};
const updateObjectsBeforeAssemblies=updateObjects;updateObjects=function(){updateObjectsBeforeAssemblies();const box=$('#outliner');if(!box)return;const q=$('#objectSearch').value.toLowerCase();box.innerHTML=(doc.groups||[]).filter(g=>g.name.toLowerCase().includes(q)&&doc.objects.some(o=>inGroup(o,g.id))).map(g=>{let depth=0,next=g.parent,seen=new Set();while(next&&!seen.has(next)){seen.add(next);depth++;next=doc.groups.find(p=>p.id===next)?.parent;}return `<button class="wide" style="padding-left:${12+depth*14}px" data-outline-group="${g.id}">▱ ${esc(g.name)}</button>`;}).join('');$$('[data-outline-group]').forEach(b=>b.onclick=()=>{selected=new Set(doc.objects.filter(o=>inGroup(o,b.dataset.outlineGroup)).map(o=>o.id));selectedFace=null;sync();});};
const legacyParts=componentsDialog;Object.assign(actions,{components:componentDialog,legacyParts,openContext,closeContext,makeUnique,group:()=>{const os=editable();if(!os.length)return;edit(()=>{const gid=id(),groups=new Set(os.map(o=>o.group).filter(Boolean));doc.groups=doc.groups||[];doc.groups.push({id:gid,name:'Group '+(doc.groups.length+1),parent:editContext?.kind==='group'?editContext.id:null});for(const g of groups){let group=doc.groups.find(x=>x.id===g);if(!group){group={id:g,name:'Group',parent:null};doc.groups.push(group);}group.parent=gid;}os.filter(o=>!o.group).forEach(o=>o.group=gid);});},ungroup:()=>{edit(()=>{for(const o of editable()){delete o.component;o.group=null;}doc.groups=(doc.groups||[]).filter(g=>doc.objects.some(o=>inGroup(o,g.id)));});}});
const validateBeforeAssemblies=validateProject;validateProject=function(data){const d=validateBeforeAssemblies(data);const clean=(x,max,name)=>{if(x===undefined)return [];if(!Array.isArray(x)||x.length>max)throw Error('Invalid '+name);return clone(x);};d.guides=clean(data.guides,1000,'guides');if(d.guides.some(g=>[g.origin,g.direction].some(p=>!Array.isArray(p)||p.length!==3||p.some(n=>!Number.isFinite(n)))))throw Error('Invalid guide coordinates.');d.groups=clean(data.groups,1000,'groups');const safeID=v=>typeof v==='string'&&/^[a-z\d_-]{1,100}$/i.test(v);if(d.groups.some(g=>!safeID(g.id)||typeof g.name!=='string'||g.name.length>80||g.parent&&!safeID(g.parent)))throw Error('Invalid group.');d.definitions=clean(data.definitions,100,'component definitions');for(const def of d.definitions){if(!safeID(def.id)||typeof def.name!=='string'||def.name.length>80||!Array.isArray(def.members)||def.members.length>100)throw Error('Invalid component definition.');for(const m of def.members){if(!safeID(m.id))throw Error('Invalid component member.');K.validateMesh(m.mesh);if(m.mesh.cad)validateNativeData(m.mesh.cad,m.mesh);}}const defs=new Set(d.definitions.map(d=>d.id));d.objects.forEach((o,i)=>{const c=data.objects[i].component;if(c){if(!safeID(c.instance)||!safeID(c.member)||!defs.has(c.definition)||!Array.isArray(c.matrix)||c.matrix.length!==12||c.matrix.some(v=>!Number.isFinite(v)))throw Error('Invalid component instance.');o.component=clone(c);}});return d;};
