/* Native solid integration and edge finishing. GPL-3.0-only. */
let cadWorker=null,cadReady=false,cadFailure='',cadSequence=0,cadBusy=false,cadCommit=false,cadPreview=null,cadDrag=null,sketchHost=null;
let edgeSelection={id:null,indices:new Set()},selectionMode='face',edgeDialogEpoch=0;const cadPending=new Map();
let cadStartupTimer=null;
function cadState(message){
 $('#kernelState').textContent=message||cadFailure||(cadReady?'Solid engine ready':'Solid engine initializing…');
 $('#cadRecovery').hidden=!cadFailure;
}
function cadFail(message){
 clearTimeout(cadStartupTimer);cadReady=false;cadFailure=String(message);cadWorker?.terminate();
 for(const p of cadPending.values()){clearTimeout(p.timer);p.reject(Error(cadFailure));}
 cadPending.clear();cadState();
}
async function cadWorkerDiagnostic(url,detail){
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);
 try{
  const response=await fetch(url,{credentials:'same-origin',cache:'no-store',signal:controller.signal});
  const type=(response.headers.get('content-type')||'').split(';')[0].trim().toLowerCase();
  response.body?.cancel().catch(()=>{});
  if(!response.ok)return 'Cannot load solid worker: HTTP '+response.status+' at '+url+'. Check that the file is uploaded and accessible.';
  if(!/^(text|application)\/(x-)?(javascript|ecmascript)$/.test(type)&&!/^text\/(javascript1\.[0-5]|jscript|livescript)$/.test(type))return 'The server sends '+url+' as '+(type||'an unknown content type')+'. Serve this .js file as text/javascript or application/javascript.';
  return 'Solid worker failed at '+url+'. '+(detail||'Check the browser console for a blocked worker or script error.');
 }catch(e){return 'Cannot load solid worker at '+url+'. '+(detail||e.message||String(e));}
 finally{clearTimeout(timer);}
}
function initCAD(){
 clearTimeout(cadStartupTimer);cadWorker?.terminate();cadWorker=null;cadReady=false;cadFailure='';cadState();
 if(typeof Worker==='undefined'){cadFail('This browser does not support Web Workers. Update the browser to use solid tools.');return;}
 if(!/^https?:$/.test(location.protocol)){cadFail('Open SKETCHBENCH through an HTTP or HTTPS web server. Direct file opening cannot load the solid engine.');return;}
 try{
  const url=new URL('./cad/worker.js',document.baseURI).href;
  const worker=cadWorker=new Worker(url,{type:'module'});
  cadStartupTimer=setTimeout(()=>{if(cadWorker===worker&&!cadReady)cadFail('The solid engine did not start within 90 seconds. Check the connection, then choose Retry solid engine.');},90000);
  worker.onmessage=({data})=>{
   if(cadWorker!==worker||cadFailure)return;
   if(data.status){if(!cadBusy)cadState(data.status);return;}
   if(data.ready){clearTimeout(cadStartupTimer);cadReady=true;cadState();sync();return;}
   if(data.fatal){cadFail(data.fatal);return;}
   const p=cadPending.get(data.id);if(!p)return;clearTimeout(p.timer);cadPending.delete(data.id);
   data.error?p.reject(Error(data.error)):p.resolve(data.result);
  };
  worker.onerror=e=>{
   if(cadWorker!==worker)return;
   const detail=e.message?e.message+(e.filename?' ('+e.filename+':'+e.lineno+')':''):'';
   cadFail('Solid worker failed at '+url+'. '+(detail||'Checking the server response…'));
   cadWorkerDiagnostic(url,detail).then(message=>{if(cadWorker===worker&&!cadReady){cadFailure=message;cadState();}});
  };
 }catch(e){cadFail('Cannot start the solid worker: '+(e.message||String(e)));}
}
function cadCall(op,args){if(!cadWorker||cadFailure)return Promise.reject(Error(cadFailure||'Solid tools require the complete hosted folder.'));return new Promise((resolve,reject)=>{const n=++cadSequence,timer=setTimeout(()=>{cadPending.delete(n);reject(Error('The geometry operation timed out. Cancel and retry with a simpler selection.'));},60000);cadPending.set(n,{resolve,reject,timer});cadWorker.postMessage({id:n,op,args});});}
async function cadTask(label,fn){if(cadBusy){toast('Finish or cancel the current solid operation.');return;}cadBusy=true;cadState(label+'…');try{return await fn();}catch(e){toast(e.message,10000);return null;}finally{cadBusy=false;cadState();}}
function cadApply(fn){cadCommit=true;try{return edit(fn);}finally{cadCommit=false;}}
const beforeCadEdit=edit;edit=function(fn){if(cadBusy&&!cadCommit){toast('Wait for the solid operation to finish.');return false;}return beforeCadEdit(fn);};
const beforeCadSwitch=saveBeforeSwitch;saveBeforeSwitch=async()=>{if(cadBusy||cadDrag){toast('Finish the solid operation before switching projects.');return false;}return beforeCadSwitch();};
const oldCadUndo=undo;undo=function(redo=false){if(cadBusy)return toast('Wait for the solid operation to finish.');cadPreview=null;edgeSelection={id:null,indices:new Set()};oldCadUndo(redo);};
const featureEdgesBeforeCAD=K.featureEdges;K.featureEdges=m=>m.cad?m.edges:featureEdgesBeforeCAD(m);
const statsBeforeCAD=K.stats;K.stats=m=>m.cad?{area:statsBeforeCAD(m).area,volume:m.cad.volume,closed:m.cad.volume>0,triangles:m.faces.length}:statsBeforeCAD(m);
const loopsBeforeCAD=selectedFaceLoops;selectedFaceLoops=function(o,fi){if(!o.cad)return loopsBeforeCAD(o,fi);const idx=o.cad.faceMap[fi],fs=o.faces.filter((f,i)=>o.cad.faceMap[i]===idx);return K.facePatch({vertices:o.vertices,faces:fs,edges:[]},0).loops;};
function validateNativeData(c,m){
 const xyz=p=>Array.isArray(p)&&p.length===3&&p.every(n=>Number.isFinite(n)&&Math.abs(n)<=1e7),idx=(n,limit)=>Number.isInteger(n)&&n>=0&&n<limit;
 if(typeof c.brep!=='string'||c.brep.length>15000000||!c.brep.includes('CASCADE Topology')||!Array.isArray(c.faceMap)||c.faceMap.length!==m.faces.length||!Array.isArray(c.edges)||!Array.isArray(c.faces)||c.edges.length>20000||c.faces.length>10000)throw Error('Invalid native solid data.');
 if(c.faceMap.some(n=>!idx(n,c.faces.length))||c.faces.some((f,i)=>f.index!==i||typeof f.type!=='string'||!xyz(f.center)||!xyz(f.normal)||!Array.isArray(f.edges)||f.edges.some(n=>!idx(n,c.edges.length))))throw Error('Invalid native face data.');
 if(c.edges.some((e,i)=>e.index!==i||![e.start,e.end,e.mid].every(xyz)||!Number.isFinite(e.length)||!Array.isArray(e.segments)||e.segments.some(s=>!Array.isArray(s)||s.length!==2||s.some(v=>!idx(v,m.vertices.length)))))throw Error('Invalid solid edge references.');
 if(c.volume!==null&&(!Number.isFinite(c.volume)||c.volume<0)||c.edges.some(e=>e.center&&!xyz(e.center)||e.normal&&!xyz(e.normal)||e.radius!==undefined&&(!Number.isFinite(e.radius)||e.radius<=0)))throw Error('Invalid native measurements.');
 if(c.normalIndices&&(!Array.isArray(c.normalIndices)||c.normalIndices.length!==m.faces.length||c.normalIndices.some(f=>!Array.isArray(f)||f.length!==3||f.some(n=>!idx(n,m.vertices.length)))))throw Error('Invalid smooth surface references.');
 if(c.transforms&&(!Array.isArray(c.transforms)||c.transforms.length>10000||c.transforms.some(m=>!Array.isArray(m)||m.length!==12||m.some(n=>!Number.isFinite(n)))))throw Error('Invalid native transforms.');
 if(c.normals&&(!Array.isArray(c.normals)||c.normals.length!==m.faces.length||c.normals.some(ns=>!Array.isArray(ns)||ns.length!==3||!ns.every(xyz))))throw Error('Invalid surface normals.');
 if(c.lastFeature&&(typeof c.lastFeature.base!=='string'||c.lastFeature.base.length>15000000||!['fillet','chamfer'].includes(c.lastFeature.kind)))throw Error('Invalid edge treatment history.');
 return clone(c);
}
const validateBeforeCAD=validateProject;validateProject=function(data){if(![1,2,3].includes(data?.schema))throw Error('Unsupported project schema.');const d=validateBeforeCAD({...data,schema:2});d.schema=3;for(let i=0;i<d.objects.length;i++){const c=data.objects[i].cad;if(c)d.objects[i].cad=validateNativeData(c,d.objects[i]);}for(let i=0;i<d.components.length;i++)for(let j=0;j<d.components[i].objects.length;j++){const c=data.components[i].objects[j].cad;if(c)d.components[i].objects[j].cad=validateNativeData(c,d.components[i].objects[j]);}return d;};

const newDocumentBeforeCAD=newDocument;newDocument=function(name){const d=newDocumentBeforeCAD(name);d.schema=3;return d;};
const renderBeforeCAD=render;render=function(){let originals;if(cadPreview){originals=doc.objects;doc.objects=doc.objects.map(o=>o.id===cadPreview.id?{...o,...cadPreview.mesh}:o);}try{renderBeforeCAD();}finally{if(originals)doc.objects=originals;}const o=doc.objects.find(o=>o.id===edgeSelection.id);if(o?.cad)for(const i of edgeSelection.indices)for(const [a,b]of o.cad.edges[i]?.segments||[])for(const [p,q]of visibleEdgeParts({a:project(o.vertices[a]),b:project(o.vertices[b])},drawn))line2(ctx,p,q,'#ed793c',4);};
const inspectorBeforeCAD=updateInspector;updateInspector=function(){inspectorBeforeCAD();const os=editable(),o=os.length===1?os[0]:null;if(o?.cad){$('#meshStats').textContent=`Native solid · ${o.cad.faces.length} surfaces · ${o.cad.edges.length} edges · ${fmt(o.cad.volume||0)} mm³`;const fi=o.cad.faceMap[selectedFace?.face],face=o.cad.faces[fi];$('#faceHint').textContent=face?`${face.type.toLowerCase()} surface ${fi+1} · push inward to cut`: 'Select a planar face to push/pull.';$('#applyExtrude').disabled=!face||face.type!=='PLANE';}$('#edgeCount').textContent=edgeSelection.id===o?.id?edgeSelection.indices.size+' edges selected':'Click edges or choose them in the tool';};
function cadPickEdge(x,y){let best=null;for(const o of doc.objects.filter(objectVisible)){if(!o.cad)continue;for(const e of o.cad.edges)for(const [a,b]of e.segments){const p=project(o.vertices[a]),q=project(o.vertices[b]),dx=q[0]-p[0],dy=q[1]-p[1],t=Math.max(0,Math.min(1,((x-p[0])*dx+(y-p[1])*dy)/(dx*dx+dy*dy||1))),dist=Math.hypot(x-p[0]-t*dx,y-p[1]-t*dy),z=p[2]+(q[2]-p[2])*t,h=hit(x,y);if(dist<9&&(!h||z>=h.depth-.25)&&(!best||dist<best.dist))best={o,index:e.index,dist};}}return best;}
function cadSelectEdge(x,y,add=false){const h=cadPickEdge(x,y);if(!h){if(!add)edgeSelection={id:null,indices:new Set()};sync();return;}if(edgeSelection.id!==h.o.id||!add)edgeSelection={id:h.o.id,indices:new Set()};if(add&&edgeSelection.indices.has(h.index))edgeSelection.indices.delete(h.index);else edgeSelection.indices.add(h.index);selected=new Set([h.o.id]);selectedFace=null;sync();}
function cadPointerDown(e,x,y){if(cadBusy)return true;if(tool==='select'&&selectionMode==='edge'&&e.button===0&&!e.altKey&&!spaceDown){cadSelectEdge(x,y,e.shiftKey);return true;}if(tool!=='pushpull'||e.button!==0||e.altKey||spaceDown)return false;const h=hit(x,y);if(!h?.o.cad)return false;if(objectLocked(h.o)){toast('Unlock this solid first.');return true;}const fi=h.o.cad.faceMap[h.face],f=h.o.cad.faces[fi];if(f?.type!=='PLANE'){toast('Choose a planar face. Use Fillet or Chamfer for curved edges.');return true;}selectHit(h);const p=project(f.center),q=project(V.add(f.center,f.normal));cadDrag={o:clone(h.o),face:fi,x,y,screen:[q[0]-p[0],q[1]-p[1]],distance:0,version:0};stage.setPointerCapture(e.pointerId);return true;}
function cadPointerMove(e,x,y){if(!cadDrag)return false;const d=cadDrag,dx=x-d.x,dy=y-d.y,[sx,sy]=d.screen;let distance=(sx*sx+sy*sy)>.05?(dx*sx+dy*sy)/(sx*sx+sy*sy):-dy/camera.scale;if(prefs.snap)distance=Math.round(distance/prefs.grid)*prefs.grid;d.distance=distance;previewSolidDrag(d);$('#extrudeDistance').value=distance.toFixed(2);$('#toolHint').textContent='Push/pull '+fmt(distance)+' mm · release to calculate · Escape cancels';return true;}
async function cadPointerUp(cancel=false){if(!cadDrag)return false;const d=cadDrag;cadDrag=null;cadPreview=null;if(!cancel&&Math.abs(d.distance)>.0001)await cadTask('Updating solid',async()=>{prefs.lastPull=d.distance;savePrefs();const m=await cadCall(d.o.cad.volume?'pushpull':'extrudeRegion',{object:d.o,face:d.face,distance:d.distance,holes:sketchRegion(d.o).holes.map(h=>h.o)});cadApply(()=>{const o=doc.objects.find(o=>o.id===d.o.id);Object.assign(o,m);selectedFace=null;});});return true;}
const applyExtrudeBeforeCAD=applyExtrude;applyExtrude=async function(){const o=doc.objects.find(o=>o.id===selectedFace?.id);if(!o?.cad)return applyExtrudeBeforeCAD();const face=o.cad.faceMap[selectedFace.face],distance=Number($('#extrudeDistance').value);prefs.lastPull=distance;savePrefs();await cadTask('Push/pull',async()=>{const m=await cadCall('pushpull',{object:o,face,distance});cadApply(()=>{Object.assign(o,m);selectedFace=null;edgeSelection.indices.clear();});});};$('#applyExtrude').onclick=applyExtrude;
const facePlaneBeforeCAD=faceWorkplane;faceWorkplane=function(){const o=doc.objects.find(o=>o.id===selectedFace?.id);if(o?.cad){const f=o.cad.faces[o.cad.faceMap[selectedFace.face]];if(f.type!=='PLANE'){toast('Choose a planar face to sketch on.');return;}facePlaneBeforeCAD();sketchHost=o.cad.volume?{id:o.id,face:o.cad.faceMap[selectedFace.face]}:null;toast(sketchHost?'Drawing now divides this solid’s face.':'New outlines remain separate on this sketch plane.');return;}sketchHost=null;facePlaneBeforeCAD();};actions.facePlane=faceWorkplane;
const newProfileBeforeCAD=newProfile;newProfile=async function(ps,name){const host=doc.objects.find(o=>o.id===sketchHost?.id);if(host?.cad&&prefs.plane==='face'){await cadTask('Dividing face',async()=>{const m=await cadCall('splitFace',{object:host,points:ps,closed:true});cadApply(()=>{Object.assign(host,m);selected=new Set([host.id]);selectedFace=null;});points=[];hover=null;setTool('pushpull');toast('Face divided. Click the region to push/pull.');});return;}await cadTask('Drawing profile',async()=>{const m=await cadCall('profile',{loops:[ps]});cadApply(()=>{const o=addObject(name,m);const added=doc.objects.at(-1);selectedFace={id:added.id,face:0};});points=[];hover=null;setTool('pushpull');});};
const finishBeforeCAD=finishProfile;finishProfile=async function(){const host=doc.objects.find(o=>o.id===sketchHost?.id);if(tool==='line'&&host?.cad&&points.length>=2){await cadTask('Dividing face',async()=>{const m=await cadCall('splitFace',{object:host,points:clone(points),closed:false});cadApply(()=>Object.assign(host,m));points=[];setTool('select');});return;}return finishBeforeCAD();};actions.finish=finishProfile;
function oneSolid(){const os=editable();if(os.length!==1||!os[0].cad||!(os[0].cad.volume>0))throw Error('Select one native solid. Use Convert mesh if needed.');return os[0];}
async function convertSolid(){const o=editable()[0];if(editable().length!==1||!o)return toast('Select one unlocked closed mesh.');if(o.cad)return toast('This is already a native solid.');await cadTask('Converting mesh',async()=>{const m=await cadCall('convert',{object:o});cadApply(()=>Object.assign(o,m));toast('Converted to an editable faceted solid. Original mesh is available with Undo.');});}
function edgeTool(kind,editing=false){let epoch,o;try{o=oneSolid();}catch(e){toast(e.message);return;}if(editing&&!o.cad.lastFeature)return toast('Select a solid whose last operation was a fillet or chamfer.');const prior=editing?o.cad.lastFeature.args:null;if(editing)kind=o.cad.lastFeature.kind;
 const opts=kind==='fillet'?'<option value="constant">Constant radius</option><option value="variable">Variable radius · start/end</option>':'<option value="equal">Equal distance</option><option value="two">Two distances</option><option value="angle">Distance + angle</option>';
 modal(kind==='fillet'?'Round edges · Fillet':'Bevel edges · Chamfer',`<p>Select edges in the viewport before opening this tool, or select them below.</p><div class="formgrid"><label>Mode<select id="finishMode">${opts}</select></label><label>${kind==='fillet'?'Radius':'Distance'} (mm)<input id="finishAmount" type="number" min="0.001" step="0.5" value="${prior?.amount||2}"></label><label>Second distance / end radius<input id="finishAmount2" type="number" min="0.001" step="0.5" value="${prior?.amount2||3}"></label><label>Angle (degrees)<input id="finishAngle" type="number" min="0.1" max="89.9" value="${prior?.angle||45}"></label></div><label>Reference face for asymmetric chamfer<select id="finishReference">${o.cad.faces.map(f=>`<option value="${f.index}">${f.index+1} · ${f.type.toLowerCase()}</option>`).join('')}</select></label><div class="inline"><label class="check"><input id="finishAll" type="checkbox"> All edges</label><label class="check"><input id="finishChain" type="checkbox"> Include tangent chain</label></div><details ${edgeSelection.indices.size?'':'open'}><summary>Edges</summary><div class="edgeList">${o.cad.edges.map(e=>`<label class="check"><input type="checkbox" data-finish-edge="${e.index}" ${(edgeSelection.id===o.id&&edgeSelection.indices.has(e.index))?'checked':''}>${e.index+1} · ${e.type.toLowerCase()} · ${fmt(e.length)} mm</label>`).join('')}</div></details><p id="finishStatus" role="status">Preview checks the resulting solid before applying.</p><div class="inline"><button id="finishPreview">Preview</button><button id="finishApply" class="primary">Apply</button><button id="finishCancel">Cancel</button></div>`);
 epoch=edgeDialogEpoch;if(prior){$('#finishMode').value=prior.mode;$('#finishAll').checked=!!prior.all;$('#finishChain').checked=!!prior.chain;$('#finishReference').value=prior.referenceFace||0;for(const key of ['finishAll','finishChain','finishReference'])$('#'+key).disabled=true;$$('[data-finish-edge]').forEach(e=>e.disabled=true);$('#finishStatus').textContent='Edits the original edge selection. Remove the treatment first to choose different edges.';}
 let result=null,lastKey='';const args=()=>({object:o,kind,mode:$('#finishMode').value,amount:+$('#finishAmount').value,amount2:+$('#finishAmount2').value,angle:+$('#finishAngle').value,referenceFace:+$('#finishReference').value,all:$('#finishAll').checked,chain:$('#finishChain').checked,edges:editing?prior.edges:$$('[data-finish-edge]').filter(e=>e.checked).map(e=>+e.dataset.finishEdge)});
 const run=async commit=>{await cadTask('Building '+kind,async()=>{const a=args(),key=JSON.stringify(a);$('#finishStatus').textContent='Calculating…';if(!result||key!==lastKey){result=await cadCall(editing?'editFeature':'finish',a);lastKey=key;}if(epoch!==edgeDialogEpoch||!$('#dialog').open)return;if(commit){cadPreview=null;cadApply(()=>{Object.assign(o,result);selectedFace=null;edgeSelection.indices.clear();});closeDialog();toast(kind+' applied. Use Edit last edge treatment to change its values.');}else{cadPreview={id:o.id,mesh:result};render();$('#finishStatus').textContent='Valid solid · '+fmt(result.cad.volume)+' mm³ · preview only';}});};$('#finishPreview').onclick=()=>run(false);$('#finishApply').onclick=()=>run(true);$('#finishCancel').onclick=()=>closeDialog();
}
const modalBeforeCAD=modal;modal=function(...args){edgeDialogEpoch++;cadPreview=null;return modalBeforeCAD(...args);};
const closeBeforeCAD=closeDialog;closeDialog=function(){edgeDialogEpoch++;cadPreview=null;closeBeforeCAD();render();};actions.closeDialog=closeDialog;$('#dialog').addEventListener('cancel',()=>{edgeDialogEpoch++;cadPreview=null;render();});
primitiveDialog=function(){modal('Add a native solid',`<label>Shape<select id="cadKind"><option value="box">Box</option><option value="cylinder">Cylinder</option><option value="sphere">Sphere</option><option value="cone">Cone</option><option value="torus">Torus</option><option value="enclosure">Open enclosure</option></select></label><div class="formgrid three"><label>Width<input id="cadW" type="number" value="80"></label><label>Depth<input id="cadD" type="number" value="60"></label><label>Height<input id="cadH" type="number" value="30"></label><label>Radius<input id="cadR" type="number" value="20"></label><label>Wall / tube radius<input id="cadT" type="number" value="3"></label></div><div class="formgrid three">${['X','Y','Z'].map((s,i)=>`<label>Origin ${s}<input id="cadPos${i}" type="number" value="0"></label>`).join('')}</div><p>Dimensions are millimeters. These solids support fillets, chamfers, and face drawing.</p><button id="cadInsert" class="primary wide">Add solid</button>`);$('#cadInsert').onclick=()=>cadTask('Creating solid',async()=>{const args={kind:$('#cadKind').value,w:+$('#cadW').value,d:+$('#cadD').value,h:+$('#cadH').value,r:+$('#cadR').value,thickness:+$('#cadT').value,position:[0,1,2].map(i=>+$('#cadPos'+i).value)};const mesh=await cadCall('primitive',args);cadApply(()=>addObject(args.kind,mesh));closeDialog();setTool('select');fit();});};actions.primitive=primitiveDialog;
const originalSolidsDialog=solidsDialog;solidsDialog=function(){const os=editable();if(os.length!==2||!os.every(o=>o.cad))return originalSolidsDialog();modal('Combine native solids',`<label>First solid (A)<select id="cadBooleanA">${os.map(o=>`<option value="${o.id}">${esc(o.name)}</option>`).join('')}</select></label><label>Operation<select id="cadBooleanKind"><option value="subtract">Subtract · A − B</option><option value="union">Union</option><option value="intersect">Intersection</option><option value="trim">Trim · retain cutter</option></select></label><label class="check"><input id="cadKeep" type="checkbox" checked> Keep source solids hidden</label><button id="cadBooleanRun" class="primary wide">Calculate</button>`);$('#cadBooleanRun').onclick=()=>cadTask('Combining solids',async()=>{const a=os.find(o=>o.id===$('#cadBooleanA').value)||os[0],b=os.find(o=>o!==a),kind=$('#cadBooleanKind').value,keep=$('#cadKeep').checked,m=await cadCall('boolean',{object:a,other:b,kind});cadApply(()=>{if(keep)os.forEach(o=>o.visible=false);else doc.objects=doc.objects.filter(o=>!os.includes(o)||(kind==='trim'&&o===b));addObject(a.name+' '+kind,m,a.color);});closeDialog();});};actions.solids=solidsDialog;
async function solidCommand(op,args={}){await cadTask('Updating solid',async()=>{const o=oneSolid(),m=await cadCall(op,{object:o,...args});cadApply(()=>{Object.assign(o,m);selectedFace=null;edgeSelection.indices.clear();});});}
async function exportNativeSTEP(){await cadTask('Exporting STEP',async()=>{const o=oneSolid(),data=await cadCall('exportSTEP',{object:o});download(data.text,filename()+'.step','application/step');closeDialog();});}
const importBeforeCAD=importFile;importFile=async function(file,mtl=''){if(/\.(step|stp)$/i.test(file?.name||'')){if(file.size>25000000)return toast('STEP limit: 25 MB.');await cadTask('Importing STEP',async()=>{const m=await cadCall('importSTEP',{text:await file.text()});cadApply(()=>addObject(file.name,m));fit();closeDialog();});return;}return importBeforeCAD(file,mtl);};$('#fileInput').accept+=',.step,.stp';
const exportBeforeCAD=exportMenu;exportMenu=function(){exportBeforeCAD();$('#dialogBody .actionlist').insertAdjacentHTML?.('afterbegin',actionButton('step','Editable solid · STEP','One selected native solid, with curved surfaces.'));};actions.export=exportMenu;
Object.assign(actions,{fillet:()=>edgeTool('fillet'),chamfer:()=>edgeTool('chamfer'),editEdgeTreatment:()=>edgeTool('',true),removeEdgeTreatment:()=>solidCommand('undoFeature'),convertSolid,healFaces:()=>solidCommand('heal'),step:exportNativeSTEP,selectEdges:()=>{selectionMode=selectionMode==='edge'?'face':'edge';setTool('select');$('#selectionMode').textContent=selectionMode==='edge'?'Edges':'Faces / objects';},});
actions.retryCAD=()=>{if(cadBusy)return toast('Wait for the current operation to finish.');initCAD();};
initCAD();
// Preserve exact solid geometry when existing move/rotate/mirror/array tools transform meshes.
const transformBeforeCAD=K.transform;K.transform=function(m,fn){if(!m.cad)return transformBeforeCAD(m,fn);const origin=fn([0,0,0]),columns=[0,1,2].map(i=>{const p=[0,0,0];p[i]=1;return V.sub(fn(p),origin);}),lengths=columns.map(V.len);if(Math.max(...lengths)-Math.min(...lengths)>1e-6||Math.abs(V.dot(columns[0],columns[1]))>1e-6||Math.abs(V.dot(columns[0],columns[2]))>1e-6||Math.abs(V.dot(columns[1],columns[2]))>1e-6)throw Error('Use Push/pull to resize a native solid along one axis, or Transform for uniform scaling.');const matrix=[0,1,2].flatMap(i=>[columns[0][i],columns[1][i],columns[2][i],origin[i]]);m.cad=clone(m.cad);m.cad.transforms=[...(m.cad.transforms||[]),matrix];m.cad.faces.forEach(f=>{f.center=fn(f.center);f.normal=V.unit(V.sub(fn(f.normal),origin));});if(m.cad.normals)m.cad.normals=m.cad.normals.map(ns=>ns.map(n=>V.unit(V.sub(fn(n),origin))));m.cad.edges.forEach(e=>{if(e.center)e.center=fn(e.center);if(e.normal)e.normal=V.unit(V.sub(fn(e.normal),origin));if(e.radius)e.radius*=lengths[0];e.start=fn(e.start);e.end=fn(e.end);e.mid=fn(e.mid);e.length*=lengths[0];});m.cad.volume*=lengths[0]**3;return transformBeforeCAD(m,fn);};
// A direct vertex edit must never leave an obsolete native solid attached.
const vertexBeforeCAD=vertexEditor;vertexEditor=function(){if(editable().some(o=>o.cad)){toast('Native solids use face and edge tools. Export/import a mesh for arbitrary vertex editing.');return;}vertexBeforeCAD();};actions.vertexEditor=vertexEditor;
const repairBeforeCAD=repairMesh;repairMesh=function(mode){if(editable().some(o=>o.cad)){toast('Native solids are checked by the solid engine. Use Merge coplanar faces to simplify.');return;}repairBeforeCAD(mode);};
// Convert newly extruded flat sketches to exact planar solids, including inner loops.
const extrudeBeforeCAD=applyExtrude;applyExtrude=async function(){const o=doc.objects.find(o=>o.id===selectedFace?.id);if(!o||o.cad||o.faces.length!==1)return extrudeBeforeCAD();const region=sketchRegion(o,0);if(region.error)return toast(region.error);const loops=[o.faces[0].map(i=>o.vertices[i]),...region.holes.map(h=>h.points)],distance=+$('#extrudeDistance').value,normal=K.normal(o.vertices,o.faces[0]);await cadTask('Extruding profile',async()=>{const m=await cadCall('extrudeProfile',{loops,normal,distance});cadApply(()=>{Object.assign(o,m);selectedFace=null;});});};$('#applyExtrude').onclick=applyExtrude;
// The baseline move drag writes vertices directly. Route it through the transform adapter.
function finishNativeProfileGesture(g,cancel){if(cancel||g.type!=='extrude'||g.original?.faces.length!==1||g.error||Math.abs(g.distance)<1e-6)return false;doc=JSON.parse(g.before);const o=doc.objects.find(o=>o.id===g.object),loops=[g.original.faces[0].map(i=>g.original.vertices[i]),...(g.region?.holes||[]).map(h=>h.points)];cadTask('Extruding solid',async()=>{const m=await cadCall('extrudeProfile',{loops,normal:g.normal,distance:g.distance});cadApply(()=>{Object.assign(o,m);selectedFace=null;});});return true;}
function cancelSolidOperation(){if(!cadBusy)return;cadWorker?.terminate();for(const p of cadPending.values()){clearTimeout(p.timer);p.reject(Error('Operation cancelled. The original geometry was preserved.'));}cadPending.clear();cadReady=false;cadFailure='';cadPreview=null;initCAD();render();}actions.cancelSolid=cancelSolidOperation;
const drawBeforeAutoFace=clickDraw;clickDraw=function(x,y){if(prefs.autoFacePlane!==false&&!points.length&&['rectangle','circle','polygon','line'].includes(tool)){const h=hit(x,y);if(h?.o.cad?.volume&&h.o.cad.faces[h.o.cad.faceMap[h.face]]?.type==='PLANE'&&!objectLocked(h.o)){selectedFace={id:h.o.id,face:h.face};faceWorkplane();}}return drawBeforeAutoFace(x,y);};
const oldFlatLoop=sketchLoop;sketchLoop=function(o){if(!o.cad)return oldFlatLoop(o);if(o.cad.volume||o.cad.faces.length!==1||o.cad.faces[0].type!=='PLANE')return null;try{const loops=K.facePatch(o,0).loops;if(loops.length!==1)return null;const points=loops[0],frame=K.frame(points),area=Math.abs(points.reduce((s,p,i)=>s+V.dot(V.cross(V.sub(p,frame.o),V.sub(points[(i+1)%points.length],frame.o)),frame.n)/2,0));return {o,points,frame,area};}catch{return null;}};
const oldRegionV2=sketchRegion;sketchRegion=function(o,fi=0){if(!doc.objects.some(o=>o.cad&&!o.cad.volume))return oldRegionV2(o,fi);const outer=sketchLoop(o),result={holes:[],error:null};if(!outer)return result;const boundary=outer.points.map(p=>K.local(p,outer.frame)),candidates=[];for(const other of doc.objects.filter(objectVisible)){if(other.id===o.id)continue;const loop=sketchLoop(other);if(!loop)continue;const local=loop.points.map(p=>K.local(p,outer.frame));if(local.some(p=>Math.abs(p[2])>1e-5))continue;if(regionContains(boundary,local))candidates.push({...loop,local});else if(regionBoundariesMeet(boundary,local))result.error='Touching or intersecting outlines must be separated before region extrusion.';}result.holes=candidates.filter(a=>!candidates.some(b=>a!==b&&regionContains(b.local,a.local)));return result;};
const faceLoopsBeforeRegionsV2=selectedFaceLoops;selectedFaceLoops=function(o,fi){const loops=faceLoopsBeforeRegionsV2(o,fi);if(o.cad&&!o.cad.volume){const r=sketchRegion(o,fi);return [...loops,...r.holes.map(h=>h.points)];}return loops;};
const applyBeforeFlatCAD=applyExtrude;applyExtrude=async function(){const o=doc.objects.find(o=>o.id===selectedFace?.id);if(!o?.cad||o.cad.volume)return applyBeforeFlatCAD();const region=sketchRegion(o);if(region.error)return toast(region.error);await cadTask('Extruding region',async()=>{const mesh=await cadCall('extrudeRegion',{object:o,face:o.cad.faceMap[selectedFace.face],holes:region.holes.map(h=>h.o),distance:+$('#extrudeDistance').value});cadApply(()=>{Object.assign(o,mesh);selectedFace=null;});});};$('#applyExtrude').onclick=applyExtrude;
// Surface materials follow matching surfaces after a native rebuild.
const editBeforeFaceMaterials=edit;edit=function(fn){return editBeforeFaceMaterials(()=>{const before=new Map(doc.objects.filter(o=>o.cad&&o.faceMaterials).map(o=>[o.id,{brep:o.cad.brep,faces:clone(o.cad.faces),materials:clone(o.faceMaterials)}]));fn();for(const o of doc.objects){const old=before.get(o.id);if(!old||!o.cad||old.brep===o.cad.brep)continue;const next={};for(const [idx,material]of Object.entries(old.materials)){const f=old.faces[+idx];if(!f)continue;const candidates=o.cad.faces.filter(q=>q.type===f.type&&V.dot(q.normal,f.normal)>.999);candidates.sort((a,b)=>{const score=q=>V.len(V.cross(V.sub(q.center,f.center),f.normal));return score(a)-score(b);});if(candidates[0])next[candidates[0].index]=material;}o.faceMaterials=next;}});};
async function previewSolidDrag(d){if(d.pending||Math.abs(d.distance)<.00001)return;d.pending=true;const distance=d.distance;try{const m=await cadCall(d.o.cad.volume?'pushpull':'extrudeRegion',{object:d.o,face:d.face,distance,holes:sketchRegion(d.o).holes.map(h=>h.o)});if(cadDrag===d&&distance===d.distance){cadPreview={id:d.o.id,mesh:m};render();}}catch{}finally{d.pending=false;if(cadDrag===d&&d.distance!==distance)previewSolidDrag(d);}}
