/* Smooth display, simple ground shadows and scene playback. GPL-3.0-only. */
function smoothNormals(o,t){if(prefs.smooth===false||!o.cad?.normals||t.sectionCap)return null;const face=o.faces[t.face],raw=o.cad.normals[t.face],order=o.cad.normalIndices?.[t.face],ns=order?face.map(i=>raw[order.indexOf(i)]):raw;if(!ns?.every(n=>Array.isArray(n)&&n.length===3)||!face)return null;const [a,b,c]=face.map(i=>o.vertices[i]),v0=V.sub(b,a),v1=V.sub(c,a),aa=V.dot(v0,v0),ab=V.dot(v0,v1),bb=V.dot(v1,v1),den=aa*bb-ab*ab;if(Math.abs(den)<1e-15)return null;return t.points.map(p=>{const v=V.sub(p,a),x=(bb*V.dot(v,v0)-ab*V.dot(v,v1))/den,y=(aa*V.dot(v,v1)-ab*V.dot(v,v0))/den;return V.unit(V.add(V.mul(ns[0],1-x-y),V.add(V.mul(ns[1],x),V.mul(ns[2],y))));});}
function groundShadowTriangles(objects){if(!prefs.shadows||renderMode==='wire'||doc.section?.enabled)return [];const ground=Math.min(0,K.bounds(objects).lo[2])-.02,result=[],color=rgb(prefs.theme==='light'?'#cbd2c4':'#17211b');for(const o of objects)for(const t of K.triangles(o)){const world=t.points.map(p=>{const z=p[2]-ground;return [p[0]-.4*z,p[1]+.6*z,ground];});result.push({o,face:t.face,world,ps:world.map(project),color,opacity:1,shadow:true});}return result;}
let sceneAnimation=0;
function stopScenePlayback(){sceneAnimation++;}
function transitionScene(scene,duration=800){const token=++sceneAnimation,from=clone(camera),to=clone(scene.camera);return new Promise(resolve=>{let start=null;const frame=time=>{if(token!==sceneAnimation){resolve(false);return;}if(start===null)start=time;const t=Math.min(1,(time-start)/Math.max(1,duration)),u=t*t*(3-2*t),mix=(a,b)=>a+(b-a)*u;camera={...to,az:mix(from.az,to.az),el:mix(from.el,to.el),scale:Math.exp(mix(Math.log(from.scale),Math.log(to.scale))),target:from.target.map((v,i)=>mix(v,to.target[i])),fov:mix(from.fov||45,to.fov||45)};render();if(t<1)requestAnimationFrame(frame);else{edit(()=>restoreScene(scene));resolve(true);}};requestAnimationFrame(frame);});}
async function playScenes(){const scenes=doc.scenes||[];if(scenes.length<2)return toast('Save at least two scenes.');closeDialog();for(const s of scenes){if(!await transitionScene(s,1200))break;}toast('Scene playback finished.');}
const sceneDialogBeforeAnimation=viewsDialog;viewsDialog=function(){sceneDialogBeforeAnimation();$('#dialogBody').insertAdjacentHTML?.('beforeend','<div class="inline"><button data-action="playScenes">Play scene sequence</button><button data-action="stopScenes">Stop playback</button></div>');$$('[data-scene-load]').forEach(b=>b.onclick=()=>{const scene=doc.scenes.find(s=>s.id===b.dataset.sceneLoad);closeDialog();transitionScene(scene);});};
Object.assign(actions,{views:viewsDialog,playScenes,stopScenes:stopScenePlayback,toggleSmooth:()=>{prefs.smooth=prefs.smooth===false;savePrefs();render();toast(prefs.smooth?'Smooth surface shading':'Faceted surface shading');},toggleShadows:()=>{prefs.shadows=!prefs.shadows;savePrefs();render();toast(prefs.shadows?'Ground shadows on':'Ground shadows off');}});
stage.addEventListener('pointerdown',stopScenePlayback,true);stage.addEventListener('wheel',stopScenePlayback,true);document.addEventListener('keydown',e=>{if(e.key==='Escape')stopScenePlayback();});
// Clip before projection so walking through a model cannot stretch behind-camera faces across the view.
function nearDistance(p){const focal=height/2/Math.tan((camera.fov||45)*Math.PI/360);return focal/camera.scale-V.dot(V.sub(p,camera.target),basis().back)-.1;}
function nearPolygon(ps){if(!camera.perspective)return ps;const out=[];for(let i=0;i<ps.length;i++){const a=ps[i],b=ps[(i+1)%ps.length],da=nearDistance(a),db=nearDistance(b);if(da>=0)out.push(a);if((da<0&&db>=0)||(da>=0&&db<0))out.push(V.add(a,V.mul(V.sub(b,a),da/(da-db))));}return out;}
const displayBeforeNear=displayTriangles;displayTriangles=function(o){const ts=displayBeforeNear(o);if(!camera.perspective)return ts;return ts.flatMap(t=>{const ps=nearPolygon(t.points),out=[];for(let i=1;i<ps.length-1;i++)out.push({...t,points:[ps[0],ps[i],ps[i+1]]});return out;});};
const edgesBeforeNear=displayEdges;displayEdges=function(o,all){const es=edgesBeforeNear(o,all);if(!camera.perspective)return es;return es.flatMap(([a,b])=>{const da=nearDistance(a),db=nearDistance(b);if(da<0&&db<0)return [];if(da<0)a=V.add(a,V.mul(V.sub(b,a),da/(da-db)));else if(db<0)b=V.add(a,V.mul(V.sub(b,a),da/(da-db)));return [[a,b]];});};
