/* Display sections, attached dimensions and 3D text. GPL-3.0-only. */
let sectionCache=new WeakMap();
function sectionValue(p){const s=doc.section;return (p[s.axis]-s.offset)*(s.keepPositive?1:-1);}
function clippedPolygon(ps){if(!doc.section?.enabled)return ps;const out=[];for(let i=0;i<ps.length;i++){const a=ps[i],b=ps[(i+1)%ps.length],da=sectionValue(a),db=sectionValue(b);if(da>=-1e-8)out.push(a);if((da>0&&db<0)||(da<0&&db>0))out.push(V.add(a,V.mul(V.sub(b,a),da/(da-db))));}return out;}
function sectionGeometry(o){const signature=JSON.stringify(doc.section),cached=sectionCache.get(o);if(cached?.v===o.vertices&&cached?.f===o.faces&&cached?.key===signature)return cached;const tris=[],cutSegments=[];for(const t of K.triangles(o)){const clipped=clippedPolygon(t.points);for(let i=1;i<clipped.length-1;i++)tris.push({...t,points:[clipped[0],clipped[i],clipped[i+1]]});const hits=[];for(let i=0;i<3;i++){const a=t.points[i],b=t.points[(i+1)%3],da=sectionValue(a),db=sectionValue(b);if((da>1e-7&&db< -1e-7)||(da< -1e-7&&db>1e-7))hits.push(V.add(a,V.mul(V.sub(b,a),da/(da-db))));else if(Math.abs(da)<=1e-7)hits.push(a);}const unique=[...new Map(hits.map(p=>[p.map(n=>n.toFixed(5)).join(','),p])).values()];if(unique.length===2&&V.len(V.sub(...unique))>1e-6)cutSegments.push(unique);}
 const key=p=>p.map(n=>n.toFixed(5)).join(','),links=new Map(),segments=new Map();for(const [a,b]of cutSegments){const ka=key(a),kb=key(b),sk=[ka,kb].sort().join('|');if(segments.has(sk))continue;segments.set(sk,[a,b]);for(const [p,q]of [[a,b],[b,a]]){const k=key(p);if(!links.has(k))links.set(k,[]);links.get(k).push(q);}}
 const used=new Set(),loops=[];for(const [sk,[a,b]]of segments){if(used.has(sk))continue;const loop=[a],first=key(a);let p=a,q=b;for(let guard=0;guard<segments.size+1;guard++){used.add([key(p),key(q)].sort().join('|'));if(key(q)===first){if(loop.length>2)loops.push(loop);break;}loop.push(q);const next=(links.get(key(q))||[]).find(v=>!used.has([key(q),key(v)].sort().join('|')));if(!next)break;p=q;q=next;}}
 if(doc.section.fill&&loops.length){try{const normal=[0,0,0];normal[doc.section.axis]=doc.section.keepPositive?-1:1;const frame=K.frame(loops[0]),local=loops.map(ps=>ps.map(p=>K.local(p,frame))),contains=(a,b)=>regionPoint(b[0],a)>0,depth=local.map((l,i)=>local.filter((outer,j)=>j!==i&&contains(outer,l)).length);loops.forEach((outer,i)=>{if(depth[i]%2)return;const holes=loops.filter((_,j)=>depth[j]===depth[i]+1&&contains(local[i],local[j])),cap=K.extrudeLoops(outer,holes,.001),n=K.normal(cap.vertices,cap.faces[0]);for(const t of K.triangles(cap)){if(t.points.every(p=>Math.abs(sectionValue(p))<1e-6))tris.push({face:0,points:t.points,normal,sectionCap:true});}});}catch{}}
 const value={v:o.vertices,f:o.faces,key:signature,tris,loops,cutSegments};sectionCache.set(o,value);return value;
}
function displayTriangles(o){return doc.section?.enabled?sectionGeometry(o).tris:K.triangles(o);}
function displayEdges(o,all){const result=[];for(const [i,j]of all?K.edges(o):o.cad&&prefs.smooth!==false?o.cad.edges.filter(e=>!e.smooth).flatMap(e=>e.segments):K.featureEdges(o)){let a=o.vertices[i],b=o.vertices[j];if(doc.section?.enabled){const da=sectionValue(a),db=sectionValue(b);if(da<0&&db<0)continue;if(da<0)a=V.add(a,V.mul(V.sub(b,a),da/(da-db)));else if(db<0)b=V.add(a,V.mul(V.sub(b,a),da/(da-db)));}result.push([a,b]);}if(doc.section?.enabled)result.push(...sectionGeometry(o).cutSegments);return result;}
function sectionDialog(){const s=doc.section||{axis:2,offset:15,keepPositive:false,fill:true};modal('Section plane',`<label>Plane normal<select id="sectionAxis"><option value="0">X · YZ section</option><option value="1">Y · XZ section</option><option value="2">Z · XY section</option></select></label><label>Position (mm)<input id="sectionOffset" type="number" value="${s.offset}"></label><label class="check"><input id="sectionKeep" type="checkbox" ${s.keepPositive?'checked':''}> Keep positive side</label><label class="check"><input id="sectionFill" type="checkbox" ${s.fill?'checked':''}> Fill closed section regions</label><div class="inline"><button id="applySection" class="primary">Show section</button><button id="disableSection">Disable</button><button data-action="sectionSVG">Export outlines · SVG</button></div><p>Sections affect the view, PNG, and print. Solid exports retain complete geometry.</p>`);$('#sectionAxis').value=s.axis;$('#applySection').onclick=()=>{const offset=+$('#sectionOffset').value;if(!Number.isFinite(offset))return;edit(()=>doc.section={enabled:true,axis:+$('#sectionAxis').value,offset,keepPositive:$('#sectionKeep').checked,fill:$('#sectionFill').checked});closeDialog();};$('#disableSection').onclick=()=>{edit(()=>doc.section=null);closeDialog();};}
function exportSectionSVG(){if(!doc.section?.enabled)return toast('Enable a section first.');const axes=[0,1,2].filter(i=>i!==doc.section.axis),loops=doc.objects.filter(objectVisible).flatMap(o=>sectionGeometry(o).loops),points=loops.flat();if(!points.length)return toast('The section has no closed outlines.');const lo=axes.map(i=>Math.min(...points.map(p=>p[i]))),hi=axes.map(i=>Math.max(...points.map(p=>p[i]))),size=hi.map((v,i)=>v-lo[i]);const paths=loops.map(l=>'<path d="'+l.map((p,i)=>(i?'L':'M')+(p[axes[0]]-lo[0]).toFixed(5)+' '+(hi[1]-p[axes[1]]).toFixed(5)).join(' ')+'Z"/>').join('');download(`<svg xmlns="http://www.w3.org/2000/svg" width="${size[0]}mm" height="${size[1]}mm" viewBox="0 0 ${size[0]} ${size[1]}"><title>${esc(doc.name)} section; millimeters</title><g fill="none" stroke="black" stroke-width="0.2">${paths}</g></svg>`,filename()+'-section.svg','image/svg+xml');}
function dimensionPoints(a){if(a.attachment?.type==='bounds'){const o=doc.objects.find(o=>o.id===a.attachment.object);if(!o){a.broken=true;return a.points;}const b=K.bounds([o]),axis=a.attachment.axis,p=b.lo.slice(),q=b.lo.slice();q[axis]=b.hi[axis];a.broken=false;return [p,q];}return a.points;}
const renderBeforeDimensionsV2=render;render=function(){for(const a of doc.annotations||[])if(a.attachment)a.points=dimensionPoints(a);renderBeforeDimensionsV2();for(const a of doc.annotations||[])if(a.broken){const p=project(a.points[0]);ctx.fillStyle='#b53527';ctx.fillText('Reference missing: '+a.label,p[0],p[1]+20);}};
function dimensionsV2(){modal('Dimensions and labels',`<label>Label<input id="attachedLabel" value="${esc(chosen()[0]?.name||'Dimension')}"></label><label>Dimension type<select id="attachedType"><option value="bounds0">Selected object width</option><option value="bounds1">Selected object depth</option><option value="bounds2">Selected object height</option><option value="measure">Current two-point measurement</option><option value="radius">Selected circular edge radius</option><option value="angle">Angle · pick three points</option><option value="leader">Leader label · pick two points</option></select></label><button id="addAttached" class="primary wide">Add dimension</button>${(doc.annotations||[]).map(a=>`<div class="projectRow"><span>${esc(a.label)}${a.broken?' · reference missing':''}<small>${a.attachment?'Attached to object':'Fixed endpoints'}</small></span><button data-remove-annotation="${a.id}">Delete</button></div>`).join('')}`);$('#addAttached').onclick=()=>{try{const type=$('#attachedType').value,o=chosen()[0],label=$('#attachedLabel').value.slice(0,100);let a={id:id(),label,points:null};if(['angle','leader'].includes(type)){annotationDraft={kind:type,label,points:[]};closeDialog();setTool('measure');toast(type==='angle'?'Pick a point on the first arm, the corner, then a point on the second arm.':'Pick the anchor, then the label position.');return;}if(type.startsWith('bounds')){if(!o)throw Error('Select an object.');a.attachment={type:'bounds',object:o.id,axis:+type.at(-1)};a.points=dimensionPoints(a);}else if(type==='measure'){if(!measure)throw Error('Measure two points first.');a.points=clone(measure);}else{const edge=o?.cad?.edges[[...edgeSelection.indices][0]];if(edge?.type!=='CIRCLE'||V.len(V.sub(edge.start,edge.end))>1e-5)throw Error('Select one complete circular edge.');a.points=[V.mul(V.add(edge.start,edge.mid),.5),edge.start];a.label='R '+a.label;}edit(()=>{doc.annotations=doc.annotations||[];doc.annotations.push(a);});dimensionsV2();}catch(e){toast(e.message);}};$$('[data-remove-annotation]').forEach(b=>b.onclick=()=>{edit(()=>doc.annotations=doc.annotations.filter(a=>a.id!==b.dataset.removeAnnotation));dimensionsV2();});}
function textDialog(){modal('Extruded text',`<label>Text<input id="textString" value="SKETCHBENCH" maxlength="100"></label><div class="formgrid"><label>Letter size (mm)<input id="textSize" type="number" value="10" min="1"></label><label>Extrusion depth (mm)<input id="textDepth" type="number" value="2" min=".1"></label></div><p>Placed at the work-plane origin. Move it, then use Union or Subtract for raised or recessed lettering.</p><button id="addText" class="primary wide">Create text solid</button>`);$('#addText').onclick=()=>cadTask('Building text',async()=>{const font=await fetch('./vendor/DejaVuSans.ttf').then(r=>{if(!r.ok)throw Error('The bundled font could not load.');return r.arrayBuffer();}),f=workFrame(),m=await cadCall('text',{text:$('#textString').value,size:+$('#textSize').value,depth:+$('#textDepth').value,origin:f.o,xDir:f.u,normal:f.n,font});cadApply(()=>addObject('Text',m));closeDialog();fit();});}
function planeSplitDialog(){let o;try{o=oneSolid();}catch(e){return toast(e.message);}modal('Split solid with work plane',`<p>Creates separate native solids on either side of the current work plane. The source is kept hidden.</p><button id="splitNative" class="primary wide">Split</button>`);$('#splitNative').onclick=()=>cadTask('Splitting solid',async()=>{const f=workFrame(),r=await cadCall('splitPlane',{object:o,origin:f.o,xDir:f.u,normal:f.n});cadApply(()=>{o.visible=false;selected.clear();for(let i=0;i<r.parts.length;i++)addObject(o.name+' part '+(i+1),r.parts[i],o.color);});closeDialog();});}
const validateBeforeDocumentation=validateProject;validateProject=function(data){const d=validateBeforeDocumentation(data);for(let i=0;i<d.annotations.length;i++){const a=data.annotations[i].attachment;if(a?.type==='bounds'&&typeof a.object==='string'&&[0,1,2].includes(a.axis))d.annotations[i].attachment=clone(a);}if(d.section&&(![0,1,2].includes(d.section.axis)||!Number.isFinite(d.section.offset)))throw Error('Invalid section plane.');return d;};
Object.assign(actions,{section:sectionDialog,sectionSVG:exportSectionSVG,dimensions:dimensionsV2,text3d:textDialog,splitSolid:planeSplitDialog});
function pushToFaceDialog(){let o;try{o=oneSolid();}catch(e){return toast(e.message);}if(!selectedFace)return toast('Select the face to move.');const face=o.cad.faceMap[selectedFace.face],f=o.cad.faces[face],targets=[];for(const object of doc.objects.filter(objectVisible))for(const candidate of object.cad?.faces||[])if(candidate.type==='PLANE'&&Math.abs(V.dot(f.normal,candidate.normal))>.999&&!(o.id===object.id&&candidate.index===face))targets.push({object,face:candidate});if(!targets.length)return toast('No parallel target faces are available.');modal('Push/pull to face',`<label>Target face<select id="pullTarget">${targets.map((t,i)=>`<option value="${i}">${esc(t.object.name)} · face ${t.face.index+1}</option>`).join('')}</select></label><button id="runPullToFace" class="primary wide">Move to target plane</button>`);$('#runPullToFace').onclick=()=>cadTask('Push/pull to face',async()=>{const m=await cadCall('pushpull',{object:o,face,distance:0,targetPoint:targets[+$('#pullTarget').value].face.center});cadApply(()=>{Object.assign(o,m);selectedFace=null;});closeDialog();});}actions.pushToFace=pushToFaceDialog;
actions.repeatPull=()=>{if(!selectedFace)return toast('Select a face first.');$('#extrudeDistance').value=prefs.lastPull||$('#extrudeDistance').value;applyExtrude();};

let annotationDraft=null;
function annotationValue(a){if(a.kind==='leader')return a.label;if(a.kind==='angle'){const [p,c,q]=a.points,angle=Math.acos(Math.max(-1,Math.min(1,V.dot(V.unit(V.sub(p,c)),V.unit(V.sub(q,c))))))*180/Math.PI;return a.label+' · '+fmt(angle)+'°';}return a.label+' · '+fmt(V.len(V.sub(...a.points)))+' mm';}
const annotationRender=render;render=function(){annotationRender();for(const a of doc.annotations||[]){if(!['angle','leader'].includes(a.kind))continue;const ps=a.points.map(project),color=prefs.theme==='light'?'#a35027':'#ffb779';for(let i=1;i<ps.length;i++)line2(ctx,ps[i-1],ps[i],color,1.5);const p=a.kind==='angle'?ps[1]:ps[1];ctx.fillStyle=color;ctx.beginPath();ctx.arc(ps[0][0],ps[0][1],3,0,Math.PI*2);ctx.fill();const text=annotationValue(a);ctx.font='12px system-ui';ctx.fillStyle=hexColor('--panel');ctx.fillRect(p[0]+6,p[1]-19,ctx.measureText(text).width+8,22);ctx.fillStyle=hexColor('--ink');ctx.fillText(text,p[0]+10,p[1]-3);}};
const annotationDown=cadPointerDown;cadPointerDown=function(e,x,y){if(annotationDraft&&e.button===0){const p=pointerPoint(x,y);if(!p)return true;annotationDraft.points.push(p);if(annotationDraft.points.length===(annotationDraft.kind==='angle'?3:2)){const a=annotationDraft;annotationDraft=null;if(a.points.slice(1).some((p,i)=>V.len(V.sub(p,a.points[i]))<1e-6)){toast('Dimension points must be distinct.');return true;}edit(()=>{doc.annotations=doc.annotations||[];doc.annotations.push({id:id(),...a});});measure=null;setTool('select');}else toast('Pick the next dimension point.');render();return true;}return annotationDown(e,x,y);};
document.addEventListener('keydown',e=>{if(e.key==='Escape')annotationDraft=null;});
