/* File interchange and print finishing. GPL-3.0-only. */
const outputOld=output;output=function(format){if(format==='glb'||format==='objBundle'){try{const os=exportObjects();if(!os.length)throw Error('Select or show an object first.');download(format==='glb'?new Blob([K.glb(os)],{type:'model/gltf-binary'}):new Blob([K.zip(K.objMaterials(os))],{type:'application/zip'}),filename()+(format==='glb'?'.glb':'-obj.zip'));closeDialog();}catch(e){toast(e.message,8000);}return;}return outputOld(format);};
exportMenu=function(){modal('Take it to the bench',`<p>Mesh exports include ${selected.size?'selected visible objects':'all visible objects'}. JSON backups include the entire project, layers, views, dimensions and reusable parts.</p><div class="actionlist">${actionButton('saveProject','Editable project · JSON')}${actionButton('stl','3D printing mesh · STL','Millimeters; use Inspect and check the result in your slicer.')}${actionButton('objBundle','OBJ + materials · ZIP','Includes model.obj and materials.mtl; keep both together.')}${actionButton('glb','Colored 3D scene · GLB','Portable static geometry, colors and object names.')}${actionButton('png','Viewport image · PNG')}${actionButton('print','Model sheet · Print / PDF')}${actionButton('inspect','Inspect geometry before export')}</div>`);};
Object.assign(actions,{export:exportMenu,glb:()=>output('glb'),objBundle:()=>output('objBundle')});
const importOld=importFile;importFile=async function(file,mtl=''){if(!file)return;const ext=file.name.split('.').pop().toLowerCase();if(!['glb','obj'].includes(ext))return importOld(file);try{if(file.size>25*1024*1024)throw Error('Maximum import size is 25 MB.');const objects=ext==='glb'?K.parseGLB(await file.arrayBuffer()):K.parseOBJScene(await file.text(),mtl);if(!objects.length)throw Error('No supported geometry was found.');if(edit(()=>{selected.clear();for(const mesh of objects){const o=makeObject(mesh.name,mesh,mesh.color);doc.objects.push(o);selected.add(o.id);}selectedFace=null;})){setTool('select');closeDialog();fit();toast(ext==='glb'?'Imported static GLB geometry and colors. Textures and animations are not retained.':'OBJ imported in millimeters'+(mtl?' with material colors.':'. Add its MTL file when opening to preserve materials.'),8000);}}catch(e){toast('Import rejected: '+e.message,10000);}};
async function importFiles(files){try{let list=[...files],material=list.find(f=>/\.mtl$/i.test(f.name));if(material&&material.size>2*1024*1024)throw Error('MTL limit: 2 MB.');const mtl=material?await material.text():'';for(const f of list.filter(f=>!/\.mtl$/i.test(f.name)))await importFile(f,mtl);}catch(e){toast('Import failed: '+e.message,8000);}}
$('#fileInput').accept='.json,.sketchbench,.stl,.obj,.mtl,.glb';$('#fileInput').multiple=true;$('#fileInput').onchange=e=>{importFiles(e.target.files);e.target.value='';};
// The existing drop path remains single-file, so material-paired imports use Open.
imageBlob=function(callback){const c=document.createElement('canvas');c.width=canvas.width;c.height=canvas.height;const cc=c.getContext('2d');render();cc.drawImage(canvas,0,0);for(const a of doc.annotations||[]){const [p,q]=a.points.map(project);cc.save();cc.scale(dpr,dpr);line2(cc,p,q,'#bf6939',1.5);cc.fillStyle=hexColor('--ink');cc.font='12px system-ui';cc.fillText(a.label+' · '+fmt(V.len(V.sub(...a.points)))+' mm',(p[0]+q[0])/2,(p[1]+q[1])/2-5);cc.restore();}c.toBlob(callback,'image/png');};
printModel=function(){closeDialog();render();const image=canvas.toDataURL('image/png'),os=doc.objects.filter(objectVisible),rows=os.map(o=>{const d=K.diagnose(o);return `<tr><td>${esc(o.name)}</td><td>${K.bounds([o]).size.map(fmt).join(' × ')}</td><td>${d.closed?'Closed surface':'Needs inspection'}</td></tr>`;}).join('');$('#printSheet').innerHTML=`<h1>${esc(doc.name)}</h1><p>SKETCHBENCH ${VERSION} · ${new Date().toLocaleDateString()} · All dimensions in millimeters</p><img src="${image}" alt="Model view"><table><thead><tr><th>Object</th><th>Size X × Y × Z</th><th>Topology</th></tr></thead><tbody>${rows}</tbody></table>${(doc.annotations||[]).length?'<h2>Recorded dimensions</h2><table>'+doc.annotations.map(a=>`<tr><td>${esc(a.label)}</td><td>${fmt(V.len(V.sub(...a.points)))} mm</td></tr>`).join('')+'</table>':''}<p>Mesh model. Closed surfaces do not certify printability. Review intersections, disconnected shells and wall thickness in a slicer before fabrication.</p><small>Green Shoe Garage · GPL v3 · SKETCH → SHAPE → ARRANGE → EXPORT</small>`;const img=$('#printSheet img');if(img.complete)window.print();else img.onload=()=>window.print();};
