/* Release finishing and contextual help. GPL-3.0-only. */
showHelp=function(){modal('Make your first model',`<p><b>1 · Sketch.</b> Draw a rectangle, circle, or profile. Use the Dimensions field at the bottom for exact input: rectangle <b>80, 40</b>; circle <b>25</b>; line <b>50, 30</b> for length and angle. “Sketch by dimensions” adds arcs, ellipses, and regular polygons.</p><p><b>2 · Shape.</b> Select a face and use Push/pull. Drag in 3D or enter a distance in the inspector. “Use selected face” sets a plane for a new, separate sketch.</p><p><b>3 · Combine.</b> Shift-select two solids, then Combine solids. Choose A − B to cut a hole, Union to combine, or Intersection to keep their shared volume. Sources can be retained hidden. Inspect checks topology and supported crossings.</p><p><b>4 · Arrange.</b> Change X/Y/Z, size, color, or object names. Advanced adds rotation and vertex coordinates. Detail contains offsets, splines, sweeps, radial arrays, mirror planes, saved dimensions and views.</p><p><b>5 · Keep and share.</b> Projects manages local models and recoverable trash. Export JSON for backups, STL for slicing, OBJ + MTL for colored mesh exchange, or GLB for a portable static scene.</p><div class="kbd"><span><b>V / R / C / G / L</b> Select / sketch</span><span><b>P / M</b> Push/pull / Move</span><span><b>O / H / T</b> Orbit / Pan / Measure</span><span><b>F</b> Fit model</span><span><b>Ctrl/⌘ Z</b> Undo</span><span><b>Ctrl/⌘ Shift Z</b> Redo</span><span><b>Ctrl/⌘ D</b> Duplicate</span><span><b>Ctrl/⌘ S</b> Export JSON backup</span><span><b>Enter / Escape</b> Finish / cancel</span><span><b>Arrow keys</b> Nudge X/Y</span></div><p>Right/middle-drag or Alt-drag orbits a full 360° horizontally and vertically, including over the poles; Shift + right-drag pans. On touchscreens use Orbit/Pan buttons and zoom controls. Shift while drawing locks the dominant direction. Use the object list and numeric fields for keyboard editing.</p><p><b>Boundaries.</b> Polygon meshes in millimeters, without parametric constraints, fillets/chamfers, STEP, or native OpenSketch/SketchUp files. Curves are sampled polylines. Tight sweeps and imported meshes need inspection. Dimensions use fixed endpoints and reusable parts insert independent copies.</p><p><b>Your work stays here.</b> Autosave is browser-local, not server storage. Download backups. Another tab saving the same project pauses autosave here. No accounts, AI, telemetry, remote assets, or external runtime libraries.</p><p><b>Release candidate.</b> Geometry and controller tests passed; actual browser, touch, printing, and offline-reload acceptance remain required before stable v1.0.</p><small>SKETCHBENCH ${VERSION} · Green Shoe Garage · GPL-3.0-only</small>`);};actions.help=showHelp;
// The geometry cache is invalidated after edits; continuous moves replace vertex arrays.
const triangleBase=K.triangles,edgeBase=K.edges;let geometryCache=new WeakMap();K.invalidate=()=>geometryCache=new WeakMap();
function cachedGeometry(m){let e=geometryCache.get(m);if(!e||e.v!==m.vertices||e.f!==m.faces||e.e!==m.edges){e={v:m.vertices,f:m.faces,e:m.edges};geometryCache.set(m,e);}return e;}
K.triangles=function(m){const c=cachedGeometry(m);return c.triangles||(c.triangles=triangleBase(m));};K.edges=function(m){const c=cachedGeometry(m);return c.edges||(c.edges=edgeBase(m));};
const editBeforeCache=edit;edit=function(fn){return editBeforeCache(()=>{try{fn();}finally{K.invalidate();}});};
// The print and export views deliberately exclude transient selection graphics.
// Keyboard fallback remains available for every context-menu action.
