/* SKETCHBENCH additional mesh operations. GPL-3.0-only. */
(function(K){
'use strict';
const {V}=K,copy=x=>JSON.parse(JSON.stringify(x)),EPS=1e-6;
function frame(points,n){if(points.length<3)throw Error('Select a planar face.');n=n||K.normal(points,points.map((_,i)=>i));if(V.len(n)<.5)throw Error('Face has no area.');let u=V.unit(V.sub(points[1],points[0])),v=V.unit(V.cross(n,u));if(V.len(v)<.5)throw Error('Invalid face edge.');const o=points[0].slice();if(points.some(p=>Math.abs(V.dot(V.sub(p,o),n))>1e-4))throw Error('The selected face is not planar.');return {o,u,v,n};}
const local=(p,f)=>[V.dot(V.sub(p,f.o),f.u),V.dot(V.sub(p,f.o),f.v),V.dot(V.sub(p,f.o),f.n)];
const world=(p,f)=>V.add(f.o,V.add(V.mul(f.u,p[0]),V.add(V.mul(f.v,p[1]),V.mul(f.n,p[2]||0))));
function crossings(points){for(let i=0;i<points.length;i++)for(let j=i+2;j<points.length;j++){if(i===0&&j===points.length-1)continue;const a=points[i],b=points[(i+1)%points.length],c=points[j],d=points[(j+1)%points.length],cross=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);if(cross(a,b,c)*cross(a,b,d)<-EPS&&cross(c,d,a)*cross(c,d,b)<-EPS)return true;}return false;}
const originalProfile=K.profile;
K.profile=function(ps){if(ps.some((a,i)=>V.len(V.sub(a,ps[(i+1)%ps.length]))<EPS))throw Error('Profile contains a zero-length edge.');const m=originalProfile(ps),f=frame(ps);if(crossings(ps.map(p=>local(p,f))))throw Error('Profile edges cross. Draw a simple closed outline.');return m;};
function signedVolume(m){return K.triangles(m).reduce((s,t)=>s+V.dot(t.points[0],V.cross(t.points[1],t.points[2]))/6,0);}
function diagnose(mesh,checkIntersections=false){const m=K.weld(mesh),edgeMap=new Map(),issues=[],components=[],adj=m.faces.map(()=>new Set());let degenerate=0,nonplanar=0;
 for(let fi=0;fi<m.faces.length;fi++){const f=m.faces[fi],n=K.normal(m.vertices,f);if(V.len(n)<.5)degenerate++;if(f.some(i=>Math.abs(V.dot(V.sub(m.vertices[i],m.vertices[f[0]]),n))>1e-4))nonplanar++;for(let j=0;j<f.length;j++){const a=f[j],b=f[(j+1)%f.length],key=[a,b].sort((a,b)=>a-b).join(','),v=edgeMap.get(key)||[];v.push({fi,dir:a<b?1:-1});edgeMap.set(key,v);}}
 let open=0,nonmanifold=0,winding=0;for(const es of edgeMap.values()){if(es.length===1)open++;if(es.length>2)nonmanifold++;if(es.length===2&&es[0].dir===es[1].dir)winding++;for(const a of es)for(const b of es)if(a.fi!==b.fi)adj[a.fi].add(b.fi);}
 const visited=new Set();for(let i=0;i<m.faces.length;i++){if(visited.has(i))continue;let q=[i],size=0;visited.add(i);while(q.length){let j=q.pop();size++;for(let k of adj[j])if(!visited.has(k)){visited.add(k);q.push(k);}}components.push(size);}
 const add=(severity,message,confidence='high')=>issues.push({severity,message,confidence});
 if(open)add('error',open+' boundary edges: open surface.');if(nonmanifold)add('error',nonmanifold+' edges shared by more than two faces.');if(winding)add('error',winding+' edges have inconsistent face winding.');if(degenerate)add('error',degenerate+' zero-area faces.');if(nonplanar)add('warning',nonplanar+' nonplanar faces will be triangulated.');if(components.length>1)add('warning',components.length+' disconnected shells.');let inverted=false;try{inverted=signedVolume(m)<-EPS;}catch{add('error','A face cannot be triangulated.');}if(inverted)add('error','Surface orientation is reversed.');
 let intersections=null;if(checkIntersections){const ts=K.triangles(m);if(ts.length>1200)add('info','Self-intersection scan skipped above 1,200 triangles.');else{intersections=0;for(let i=0;i<ts.length;i++)for(let j=i+1;j<ts.length;j++){const a=ts[i],b=ts[j];if(a.face===b.face||a.ids.some(k=>b.ids.includes(k)))continue;if(triIntersect(a.points,b.points))intersections++;}if(intersections)add('error',intersections+' triangle pairs intersect.');}}
 if(!m.faces.length)add('info','Linework has no solid volume.');return {issues,open,nonmanifold,winding,degenerate,nonplanar,inverted,components:components.length,intersections,closed:m.faces.length>0&&!open&&!nonmanifold&&!winding&&!degenerate&&!inverted};}
function segTri(a,b,t){const dir=V.sub(b,a),e1=V.sub(t[1],t[0]),e2=V.sub(t[2],t[0]),h=V.cross(dir,e2),det=V.dot(e1,h);if(Math.abs(det)<EPS)return false;const inv=1/det,s=V.sub(a,t[0]),u=inv*V.dot(s,h);if(u<-EPS||u>1+EPS)return false;const q=V.cross(s,e1),v=inv*V.dot(dir,q),d=inv*V.dot(e2,q);return v>=-EPS&&u+v<=1+EPS&&d>EPS&&d<1-EPS;}
function triIntersect(a,b){if([0,1,2].some(k=>Math.max(...a.map(p=>p[k]))<Math.min(...b.map(p=>p[k]))-EPS||Math.max(...b.map(p=>p[k]))<Math.min(...a.map(p=>p[k]))-EPS))return false;return [0,1,2].some(i=>segTri(a[i],a[(i+1)%3],b)||segTri(b[i],b[(i+1)%3],a));}
// Existing solid faces translate their shared vertices. This avoids the old inward
// extrusion's duplicate coplanar walls. Reject collapse, inversions, or self-crossing.
const rawExtrude=K.extrude;
K.extrude=function(mesh,fi,d){if(!mesh.faces[fi])throw Error('Select a face.');if(!Number.isFinite(d)||Math.abs(d)<EPS)throw Error('Enter a nonzero extrusion distance.');if(mesh.faces.length===1)return rawExtrude(mesh,fi,d);const before=diagnose(mesh);if(!before.closed)throw Error('Solid-face push/pull needs a closed, consistently oriented mesh.');const m=copy(mesh),f=m.faces[fi],n=K.normal(m.vertices,f),oldNormals=m.faces.map(f=>K.normal(m.vertices,f));for(const i of f)m.vertices[i]=V.add(m.vertices[i],V.mul(n,d));if(m.faces.some((f,i)=>V.dot(K.normal(m.vertices,f),oldNormals[i])<.01))throw Error('This distance collapses or reverses a face. Try a smaller distance.');const after=diagnose(m,true);if(!after.closed||after.nonplanar||after.intersections||signedVolume(m)<=EPS)throw Error('This push/pull would create invalid geometry. Use a smaller distance or a boolean cut.');if(after.intersections===null&&K.triangles(m).length>1200)throw Error('Direct face editing is limited to 1,200 triangles. Use a boolean operation for larger meshes.');return m;};
function curve(kind,args){const {a=30,b=20,start=0,end=90,n=48,sides=6}=args;let count=kind==='polygon'?sides:n;if(!Number.isInteger(count)||count<3||count>256||!Number.isFinite(a)||a<=0||!Number.isFinite(b)||b<=0)throw Error('Use positive dimensions and 3–256 segments.');const open=kind==='arc';return Array.from({length:open?count+1:count},(_,i)=>{const t=(open?start+(end-start)*i/count:i/count*360)*Math.PI/180;return [Math.cos(t)*a,Math.sin(t)*(kind==='ellipse'?b:a),0];});}
function spline(ps,steps=12){if(ps.length<2||ps.length>100)throw Error('A spline needs 2–100 control points.');const out=[];for(let i=0;i<ps.length-1;i++){const a=ps[Math.max(0,i-1)],b=ps[i],c=ps[i+1],d=ps[Math.min(ps.length-1,i+2)];for(let j=0;j<steps;j++){const t=j/steps;out.push(b.map((_,k)=>.5*((2*b[k])+(-a[k]+c[k])*t+(2*a[k]-5*b[k]+4*c[k]-d[k])*t*t+(-a[k]+3*b[k]-3*c[k]+d[k])*t*t*t)));}}out.push(ps.at(-1).slice());return out;}
function offset(mesh,fi,d){const f=mesh.faces[fi];if(!f)throw Error('Select a face to offset.');const ps=f.map(i=>mesh.vertices[i]),fr=frame(ps),p=ps.map(a=>local(a,fr));if(!Number.isFinite(d)||Math.abs(d)<EPS)throw Error('Enter a nonzero offset.');const area=p.reduce((s,a,i)=>s+a[0]*p[(i+1)%p.length][1]-p[(i+1)%p.length][0]*a[1],0),sign=area>0?1:-1,out=[];
 for(let i=0;i<p.length;i++){let a=p[(i+p.length-1)%p.length],b=p[i],c=p[(i+1)%p.length],u=V.unit(V.sub(b,a)),v=V.unit(V.sub(c,b)),n1=[u[1]*sign,-u[0]*sign,0],n2=[v[1]*sign,-v[0]*sign,0],q1=V.add(b,V.mul(n1,d)),q2=V.add(b,V.mul(n2,d)),den=u[0]*v[1]-u[1]*v[0];if(Math.abs(den)<EPS){out.push(q1);continue;}const q=V.sub(q2,q1),t=(q[0]*v[1]-q[1]*v[0])/den;if(Math.abs(t)>Math.abs(d)*20)throw Error('Offset makes an excessively long corner. Reduce the distance.');out.push(V.add(q1,V.mul(u,t)));}
 if(out.some((a,i)=>V.dot(V.sub(out[(i+1)%out.length],a),V.sub(p[(i+1)%p.length],p[i]))<=EPS))throw Error('Offset collapses an edge. Reduce the distance.');if(crossings(out))throw Error('Offset crosses itself. Use a smaller distance.');const newArea=out.reduce((s,a,i)=>s+a[0]*out[(i+1)%out.length][1]-out[(i+1)%out.length][0]*a[1],0);if(newArea*area<=0||d<0&&Math.abs(newArea)>=Math.abs(area))throw Error('Offset collapses or reverses the profile.');return K.profile(out.map(p=>world(p,fr)));}
function sweep(profile,path){if(profile.faces.length!==1||path.length<2)throw Error('Select one flat profile and one open path.');if(path.length>200||profile.vertices.length>200)throw Error('Sweep limit: 200 profile vertices and 200 path points.');const fr=frame(profile.faces[0].map(i=>profile.vertices[i])),localPoints=profile.faces[0].map(i=>local(profile.vertices[i],fr)),center=K.bounds([profile]).center,lc=local(center,fr);let u=fr.u.slice(),oldT=null;const vertices=[],faces=[],count=localPoints.length;
 for(let k=0;k<path.length;k++){const tangent=V.unit(V.sub(path[Math.min(k+1,path.length-1)],path[Math.max(k-1,0)]));if(V.len(tangent)<.5)throw Error('Path has repeated or reversing points.');if(oldT){const axis=V.cross(oldT,tangent),sin=V.len(axis),cos=V.dot(oldT,tangent);if(cos<-.99)throw Error('Path reverses direction.');if(sin>EPS){const n=V.mul(axis,1/sin);u=V.add(V.add(V.mul(u,cos),V.mul(V.cross(n,u),sin)),V.mul(n,V.dot(n,u)*(1-cos)));}}u=V.unit(V.sub(u,V.mul(tangent,V.dot(u,tangent))));if(V.len(u)<.5)u=V.unit(V.cross(Math.abs(tangent[2])<.9?[0,0,1]:[0,1,0],tangent));const v=V.cross(tangent,u);for(const p of localPoints)vertices.push(V.add(path[k],V.add(V.mul(u,p[0]-lc[0]),V.mul(v,p[1]-lc[1]))));oldT=tangent;}
 faces.push(Array.from({length:count},(_,i)=>count-1-i));for(let k=0;k<path.length-1;k++)for(let j=0;j<count;j++)faces.push([k*count+j,k*count+(j+1)%count,(k+1)*count+(j+1)%count,(k+1)*count+j]);faces.push(Array.from({length:count},(_,i)=>(path.length-1)*count+i));const m={vertices,faces,edges:[]};if(signedVolume(m)<0)m.faces.forEach(f=>f.reverse());return m;}
Object.assign(K,{frame,local,world,curve,spline,offset,sweep,diagnose,signedVolume,triIntersect});
})(typeof module!=='undefined'?module.exports=require('./kernel.js'):K);
