/* Direct manipulation and additional sketch gestures. GPL-3.0-only. */
let gizmoMode='move',gizmoDrag=null,freehandDrawing=false;
function gizmoCenter(){return K.bounds(editable()).center;}
function gizmoHandles(){if(selectionMode!=='gizmo'||!editable().length)return [];const c=gizmoCenter(),length=55/camera.scale;return [0,1,2].map(axis=>{const dir=[0,0,0];dir[axis]=length;return {axis,center:c,from:project(c),to:project(V.add(c,dir))};});}
const renderBeforeGizmo=render;render=function(){renderBeforeGizmo();for(const h of gizmoHandles()){const color=['#d46a64','#60a475','#7198d8'][h.axis];line2(ctx,h.from,h.to,color,3);ctx.fillStyle=color;ctx.beginPath();ctx.arc(h.to[0],h.to[1],6,0,Math.PI*2);ctx.fill();ctx.font='bold 12px system-ui';ctx.fillText(['X','Y','Z'][h.axis],h.to[0]+8,h.to[1]);}};
const downBeforeGizmo=cadPointerDown;cadPointerDown=function(e,x,y){if(e.button===0&&!e.altKey&&!spaceDown&&tool==='select'&&selectionMode==='gizmo'){const h=gizmoHandles().find(h=>Math.hypot(x-h.to[0],y-h.to[1])<12);if(h){gizmoDrag={...h,x,y,objects:clone(editable()),before:snapshot()};stage.setPointerCapture(e.pointerId);return true;}}if(tool==='freehand'&&e.button===0){const p=pointerPoint(x,y);if(p){points=[p];freehandDrawing=true;stage.setPointerCapture(e.pointerId);}return true;}if(['arc3','rotatedRect'].includes(tool)&&e.button===0){const p=pointerPoint(x,y);if(!p)return true;points.push(p);if(points.length===3){try{const [a,b,c]=points;if(tool==='rotatedRect'){const u=V.unit(V.sub(b,a)),v=V.unit(V.cross(planeNormal(),u)),h=V.dot(V.sub(c,b),v);newProfile([a,b,V.add(b,V.mul(v,h)),V.add(a,V.mul(v,h))],'Rotated rectangle');}else{const f=workFrame(),[A,B,C]=points.map(p=>K.local(p,f)),d=2*(A[0]*(B[1]-C[1])+B[0]*(C[1]-A[1])+C[0]*(A[1]-B[1]));if(Math.abs(d)<1e-6)throw Error('Arc points must not be collinear.');const s=p=>p[0]**2+p[1]**2,cx=(s(A)*(B[1]-C[1])+s(B)*(C[1]-A[1])+s(C)*(A[1]-B[1]))/d,cy=(s(A)*(C[0]-B[0])+s(B)*(A[0]-C[0])+s(C)*(B[0]-A[0]))/d,r=Math.hypot(A[0]-cx,A[1]-cy),angle=p=>Math.atan2(p[1]-cy,p[0]-cx),start=angle(A),end=angle(C),mid=angle(B),turn=2*Math.PI,ccw=(end-start+turn)%turn,span=((mid-start+turn)%turn)<=ccw?ccw:ccw-turn,ps=Array.from({length:49},(_,i)=>K.world([cx+r*Math.cos(start+span*i/48),cy+r*Math.sin(start+span*i/48),0],f));edit(()=>addObject('Three-point arc',{vertices:ps,faces:[],edges:ps.slice(1).map((_,i)=>[i,i+1])}));points=[];setTool('select');}}catch(err){toast(err.message);points=[];}}render();return true;}return downBeforeGizmo(e,x,y);};
const moveBeforeGizmo=cadPointerMove;cadPointerMove=function(e,x,y){if(freehandDrawing){const p=planePoint(x,y);if(p&&points.length<1000&&Math.hypot(...project(p).slice(0,2).map((v,i)=>v-project(points.at(-1))[i]))>4)points.push(p);hover=p;render();return true;}if(gizmoDrag){const g=gizmoDrag,dx=x-g.x,dy=y-g.y,sx=g.to[0]-g.from[0],sy=g.to[1]-g.from[1],projection=(dx*sx+dy*sy)/(sx*sx+sy*sy||1),distance=projection*55/camera.scale;for(const original of g.objects){const o=doc.objects.find(o=>o.id===original.id);Object.assign(o,clone(original));const delta=[0,0,0];delta[g.axis]=prefs.snap?Math.round(distance/prefs.grid)*prefs.grid:distance;try{K.transform(o,p=>gizmoMode==='move'?V.add(p,delta):gizmoMode==='rotate'?K.rotate(p,g.axis,projection*90,g.center):V.add(g.center,V.mul(V.sub(p,g.center),Math.max(.01,1+projection))));}catch(err){toast(err.message);}}K.invalidate();render();return true;}return moveBeforeGizmo(e,x,y);};
function finishInteraction(cancel=false){if(gizmoDrag){const g=gizmoDrag;gizmoDrag=null;if(cancel)doc=JSON.parse(g.before);else if(snapshot()!==g.before){const after=clone(doc);doc=JSON.parse(g.before);edit(()=>{doc=after;});}sync();return true;}if(freehandDrawing){freehandDrawing=false;if(cancel){points=[];render();return true;}const ps=clone(points);if(ps.length>2&&V.len(V.sub(ps[0],ps.at(-1)))*camera.scale<14){ps.pop();newProfile(ps,'Freehand profile');}else if(ps.length>=2){edit(()=>addObject('Freehand line',{vertices:ps,faces:[],edges:ps.slice(1).map((_,i)=>[i,i+1])}));points=[];setTool('select');}return true;}return false;}
for(const [key,label]of [['freehand','Freehand'],['arc3','3-point arc'],['rotatedRect','Rotated rectangle']]){hints[key]=key==='arc3'?'Click start, point on arc, then end.':key==='rotatedRect'?'Click two corners along an edge, then the opposite edge.':'Drag to draw. Finish near the start to close a profile.';toolDefs.push([key,label,'','']);actions[key]=()=>setTool(key);}
Object.assign(actions,{gizmoMove:()=>{selectionMode='gizmo';gizmoMode='move';setTool('select');},gizmoRotate:()=>{selectionMode='gizmo';gizmoMode='rotate';setTool('select');},gizmoScale:()=>{selectionMode='gizmo';gizmoMode='scale';setTool('select');}});

let vertexSelection={id:null,indices:new Set()};
const downBeforeVertices=cadPointerDown;cadPointerDown=function(e,x,y){if(tool==='select'&&selectionMode==='vertex'&&e.button===0){let best=null;for(const o of doc.objects.filter(o=>objectVisible(o)&&!objectLocked(o)&&!o.cad))for(let i=0;i<o.vertices.length;i++){const p=project(o.vertices[i]),d=Math.hypot(p[0]-x,p[1]-y);if(d<10&&(!best||d<best.d)){const h=hit(x,y);if(!h||p[2]>=h.depth-1e-4)best={o,i,d};}}if(!best){if(!e.shiftKey)vertexSelection.indices.clear();render();return true;}if(!e.shiftKey||vertexSelection.id!==best.o.id)vertexSelection={id:best.o.id,indices:new Set()};if(e.shiftKey&&vertexSelection.indices.has(best.i))vertexSelection.indices.delete(best.i);else vertexSelection.indices.add(best.i);selected=new Set([best.o.id]);selectedFace=null;sync();return true;}return downBeforeVertices(e,x,y);};
const renderBeforeVertices=render;render=function(){renderBeforeVertices();if(selectionMode!=='vertex')return;const o=doc.objects.find(o=>o.id===vertexSelection.id);if(!o)return;for(const i of vertexSelection.indices){const p=o.vertices[i];if(!p)continue;const q=project(p);ctx.fillStyle='#e98245';ctx.beginPath();ctx.arc(q[0],q[1],5,0,Math.PI*2);ctx.fill();}};
function stretchVertices(){const o=doc.objects.find(o=>o.id===vertexSelection.id);if(!o||o.cad||!vertexSelection.indices.size||objectLocked(o))return toast('Select mesh vertices first. Native solids use face push/pull.');modal('Stretch mesh vertices',`<p>${vertexSelection.indices.size} vertices selected. Connected faces share the edit.</p><div class="formgrid three">${['X','Y','Z'].map((n,i)=>`<label>Move ${n}<input id="stretch${i}" value="0"></label>`).join('')}</div><button id="applyStretch" class="primary wide">Move vertices</button>`);$('#applyStretch').onclick=()=>{try{const d=[0,1,2].map(i=>parseLength($('#stretch'+i).value,prefs.units));edit(()=>{for(const i of vertexSelection.indices)o.vertices[i]=V.add(o.vertices[i],d);K.validateMesh(o);});closeDialog();}catch(e){toast(e.message);}};}
Object.assign(actions,{selectVertices:()=>{selectionMode='vertex';setTool('select');$('#selectionMode').textContent='Mesh vertices';toast('Click a mesh vertex. Shift-click adds more. Native solids use surface and edge tools.');},stretchVertices});
