/* Precision sketching and editing. GPL-3.0-only. */
let customFrame=null,axisConstraint='auto',shiftSketch=false;
function workFrame(){if(prefs.plane==='face'&&customFrame)return {...customFrame,o:V.add(customFrame.o,V.mul(customFrame.n,prefs.elevation))};const o=[0,0,0];if(prefs.plane==='xz'){o[1]=prefs.elevation;return {o,u:[1,0,0],v:[0,0,1],n:[0,-1,0]};}if(prefs.plane==='yz'){o[0]=prefs.elevation;return {o,u:[0,1,0],v:[0,0,1],n:[1,0,0]};}o[2]=prefs.elevation;return {o,u:[1,0,0],v:[0,1,0],n:[0,0,1]};}
planeNormal=()=>workFrame().n;
planePoint=function(x,y){const b=basis(),q=V.add(camera.target,V.add(V.mul(b.right,(x-width/2)/camera.scale),V.mul(b.up,-(y-height/2)/camera.scale))),f=workFrame(),den=V.dot(b.back,f.n);if(Math.abs(den)<1e-5)return null;return V.add(q,V.mul(b.back,V.dot(V.sub(f.o,q),f.n)/den));};
pointerPoint=function(x,y,vertices=true){const f=workFrame();if(vertices&&prefs.snap){let best=null,d=12;for(const o of doc.objects.filter(o=>objectVisible(o)))for(const p of o.vertices){if(tool!=='measure'&&Math.abs(V.dot(V.sub(p,f.o),f.n))>1e-4)continue;let s=project(p),dist=Math.hypot(s[0]-x,s[1]-y);if(dist<d){d=dist;best=p;}}if(best)return best.slice();}const p=planePoint(x,y);if(!p)return null;let q=K.local(p,f);if(prefs.snap){q[0]=Math.round(q[0]/prefs.grid)*prefs.grid;q[1]=Math.round(q[1]/prefs.grid)*prefs.grid;}if(points.length&&['line','polygon'].includes(tool)){const a=K.local(points.at(-1),f),dx=q[0]-a[0],dy=q[1]-a[1];let axis=axisConstraint;if(shiftSketch)axis=Math.abs(dx)>=Math.abs(dy)?'u':'v';if(axis==='auto'&&prefs.snap){if(Math.abs(dy)*camera.scale<7)axis='u';else if(Math.abs(dx)*camera.scale<7)axis='v';}if(axis==='u')q[1]=a[1];if(axis==='v')q[0]=a[0];}return K.world([q[0],q[1],0],f);};
rectPoints=function(a,b){const f=workFrame(),p=K.local(a,f),q=K.local(b,f);return [p,[q[0],p[1],0],q,[p[0],q[1],0]].map(x=>K.world(x,f));};
circlePoints=function(a,b){const f=workFrame(),r=V.len(V.sub(b,a));return K.curve('circle',{a:r}).map(p=>V.add(a,V.add(V.mul(f.u,p[0]),V.mul(f.v,p[1]))));};
function faceWorkplane(){const o=doc.objects.find(o=>o.id===selectedFace?.id);if(!o){toast('Select a face first.');return;}try{customFrame=K.frame(o.faces[selectedFace.face].map(i=>o.vertices[i]));prefs.plane='face';prefs.elevation=0;$('#plane').value='face';$('#elevation').value=0;points=[];hover=null;render();toast('Sketch plane aligned to the selected face. New sketches remain separate objects.');}catch(e){toast(e.message);}}
function faceView(){const n=workFrame().n;camera.az=Math.atan2(n[0],n[1]);camera.el=Math.asin(n[2]);$('#viewLabel').textContent='WORK PLANE';render();}
function applyNumeric(){const text=$('#numericDraw').value.trim(),ns=text.split(/[ ,;]+/).map(Number);if(ns.some(n=>!Number.isFinite(n)||Math.abs(n)>100000)||!text){toast('Enter dimensions in millimeters, such as 80, 40.');return;}const f=workFrame(),a=points[0]||f.o;try{if(tool==='rectangle'){if(ns.length!==2||ns.some(n=>n<=0))throw Error('Rectangle: enter width, depth.');newProfile(rectPoints(a,V.add(a,V.add(V.mul(f.u,ns[0]),V.mul(f.v,ns[1])))),'Rectangle');}else if(tool==='circle'){if(ns.length!==1||ns[0]<=0)throw Error('Circle: enter a positive radius.');newProfile(circlePoints(a,V.add(a,V.mul(f.u,ns[0]))),'Circle');}else if(tool==='line'||tool==='polygon'){if(ns.length>2||ns[0]<=0)throw Error('Line: enter length, angle in degrees.');const start=points.at(-1)||f.o,angle=(ns[1]||0)*Math.PI/180,p=V.add(start,V.add(V.mul(f.u,ns[0]*Math.cos(angle)),V.mul(f.v,ns[0]*Math.sin(angle))));if(!points.length)points.push(start.slice());points.push(p);$('#finish').hidden=false;$('#cancel').hidden=false;render();}else if(tool==='pushpull'){$('#extrudeDistance').value=ns[0];applyExtrude();}else throw Error('Choose Rectangle, Circle, Line, Profile, or Push/pull first.');}catch(e){toast(e.message,6000);}}
function numericSketch(){modal('Sketch by dimensions',`<p>Create on the current work plane. U and V are its horizontal and vertical axes.</p><label>Shape<select id="sketchKind"><option value="rectangle">Rectangle</option><option value="circle">Circle</option><option value="ellipse">Ellipse</option><option value="polygon">Regular polygon</option><option value="arc">Arc</option></select></label><div class="formgrid"><label>Width / radius U (mm)<input id="sketchA" type="number" value="80"></label><label>Depth / radius V (mm)<input id="sketchB" type="number" value="40"></label><label>Origin U (mm)<input id="sketchU" type="number" value="0"></label><label>Origin V (mm)<input id="sketchV" type="number" value="0"></label></div><div class="formgrid"><label>Polygon sides / curve segments<input id="sketchN" type="number" value="48" min="3" max="256"></label><label>Arc start / end (degrees)<input id="sketchArc" value="0, 90"></label></div><button class="primary wide" id="makeSketch">Create profile</button>`);$('#makeSketch').onclick=()=>{try{const kind=$('#sketchKind').value,values=['sketchA','sketchB','sketchU','sketchV','sketchN'].map(s=>Number($('#'+s).value)),[a,b,u,v,n]=values,[start,end]=$('#sketchArc').value.split(',').map(Number);if(values.some(x=>!Number.isFinite(x)||Math.abs(x)>100000)||a<=0||b<=0)throw Error('Use positive dimensions and finite coordinates.');if(kind==='arc'&&(!Number.isFinite(start)||!Number.isFinite(end)||Math.abs(end-start)>360||Math.abs(end-start)<.01))throw Error('Arc angles must span between 0 and 360 degrees.');const localPs=kind==='rectangle'?[[0,0,0],[a,0,0],[a,b,0],[0,b,0]]:K.curve(kind,{a,b,n,sides:n,start,end}),ps=localPs.map(p=>K.world([p[0]+u,p[1]+v,0],workFrame()));let m=kind==='arc'?{vertices:ps,faces:[],edges:ps.slice(1).map((_,i)=>[i,i+1])}:K.profile(ps);if(kind==='arc'){if(edit(()=>addObject('Arc',m))){closeDialog();setTool('select');fit();}}else{closeDialog();newProfile(ps,kind[0].toUpperCase()+kind.slice(1));}}catch(e){toast(e.message,7000);}};}
function vertexEditor(){let o=editable()[0];if(editable().length!==1){toast('Select one unlocked object.');return;}modal('Edit vertex',`<p>Coordinates are in millimeters. This edits mesh geometry directly; use Inspect afterward.</p><label>Vertex index (0–${o.vertices.length-1})<input id="vertexIndex" type="number" min="0" max="${o.vertices.length-1}" step="1" value="0"></label><div class="formgrid three">${['X','Y','Z'].map((s,i)=>`<label>${s}<input id="vertex${i}" type="number" step="0.1"></label>`).join('')}</div><button id="applyVertex" class="primary wide">Apply vertex change</button>`);const populate=()=>{const index=Number($('#vertexIndex').value);if(!Number.isInteger(index)||index<0||index>=o.vertices.length){toast('Choose an existing integer vertex index.');return;}o.vertices[index].forEach((v,i)=>$('#vertex'+i).value=v);};$('#vertexIndex').value='0';populate();$('#vertexIndex').onchange=populate;$('#applyVertex').onclick=()=>{o=doc.objects.find(x=>x.id===o.id);const index=Number($('#vertexIndex').value);if(!Number.isInteger(index)||index<0||index>=o.vertices.length){toast('Choose an existing vertex index.');return;}const p=[0,1,2].map(i=>Number($('#vertex'+i).value));if(p.some(n=>!Number.isFinite(n)||Math.abs(n)>100000)){toast('Use finite coordinates within ±100,000 mm.');return;}if(edit(()=>{o.vertices[+$('#vertexIndex').value]=p;K.validateMesh(o);})){closeDialog();}};}
Object.assign(actions,{facePlane:faceWorkplane,planeView:faceView,numericSketch,vertexEditor,applyNumeric});
$('#numericDraw').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();applyNumeric();}});
$('#constraint').onchange=e=>axisConstraint=e.target.value;
document.addEventListener('keydown',e=>{if(e.key==='Shift')shiftSketch=true;});document.addEventListener('keyup',e=>{if(e.key==='Shift')shiftSketch=false;});
$('#plane').onchange=e=>{const next=e.target.value;if(next==='face'){if(selectedFace){faceWorkplane();return;}if(!customFrame){e.target.value=prefs.plane;toast('Select a face and choose “Use selected face” first.');return;}}prefs.plane=next;points=[];hover=null;savePrefs();render();};
