/* Units, guides, inference, selections and transforms. GPL-3.0-only. */
function parseLength(text,unit='mm'){const units={mm:1,cm:10,m:1000,in:25.4,inch:25.4,'"':25.4,ft:304.8,"'":304.8};let s=String(text).trim().toLowerCase();if(!s)throw Error('Enter a measurement.');if(/[+*()]/.test(s))throw Error('Use a measurement, not an expression.');let total=0,found=false,sign=s.startsWith('-')?-1:1;s=s.replace(/^-\s*/,'');const re=/(\d+\s+\d+\/\d+|\d+\/\d+|(?:\d+(?:\.\d*)?|\.\d+))\s*(mm|cm|inch|in|ft|m|["'])?/g;let end=0;for(const m of s.matchAll(re)){if(s.slice(end,m.index).trim())throw Error('Unrecognized measurement.');const parts=m[1].split(/\s+/);let n=0;for(const p of parts){if(p.includes('/')){const [a,b]=p.split('/').map(Number);if(!b)throw Error('Fraction denominator cannot be zero.');n+=a/b;}else n+=Number(p);}total+=n*(units[m[2]||unit]||1);found=true;end=m.index+m[0].length;}if(!found||s.slice(end).trim()||!Number.isFinite(total)||total>1e6)throw Error('Invalid measurement.');return total*sign;}
function lengthList(s){return s.split(/[,;]+/).map(x=>parseLength(x,prefs.units||'mm'));}
let inferenceLabel='',marquee=null,transformDrag=null;
const snapBeforeV2=pointerPoint;pointerPoint=function(x,y,vertices=true){const base=snapBeforeV2(x,y,false);inferenceLabel='';if(!prefs.snap||!base)return base;const f=workFrame(),candidates=[],linearEdges=[],circles=[];const add=(p,label)=>{if(tool!=='measure'&&Math.abs(V.dot(V.sub(p,f.o),f.n))>.0001)return;const q=project(p),dist=Math.hypot(x-q[0],y-q[1]);if(dist<12)candidates.push({p,label,dist});};
 for(const o of doc.objects.filter(objectVisible)){for(const p of o.vertices)add(p,'Endpoint');const edges=o.cad?o.cad.edges.map(e=>[e.start,e.end,e.mid,e.type]):K.featureEdges(o).map(([a,b])=>[o.vertices[a],o.vertices[b],V.mul(V.add(o.vertices[a],o.vertices[b]),.5),'LINE']);for(const [a,b,mid,type]of edges){add(mid,type==='CIRCLE'?'Curve midpoint':'Midpoint');if(type==='LINE'){const d=V.sub(b,a),t=V.dot(V.sub(base,a),d)/(V.dot(d,d)||1);if(t>0&&t<1)add(V.add(a,V.mul(d,t)),'On edge');}}for(const [a,b,,kind]of edges)if(kind==='LINE'&&[a,b].every(p=>Math.abs(V.dot(V.sub(p,f.o),f.n))<1e-5))linearEdges.push([a,b]);for(const e of o.cad?.edges||[])if(e.type==='CIRCLE'&&e.center){add(e.center,'Center');circles.push(e);}if(o.cad)for(const face of o.cad.faces)if(face.type==='PLANE')add(face.center,'Face center');}
 for(const g of doc.guides||[]){const t=V.dot(V.sub(base,g.origin),g.direction);add(V.add(g.origin,V.mul(g.direction,t)),'Guide');}
 // Find local intersections only near the cursor, keeping large models responsive.
 const near=linearEdges.filter(([a,b])=>{const p=project(a),q=project(b);return x>=Math.min(p[0],q[0])-12&&x<=Math.max(p[0],q[0])+12&&y>=Math.min(p[1],q[1])-12&&y<=Math.max(p[1],q[1])+12;}).slice(0,100);
 for(let i=0;i<near.length;i++)for(let j=i+1;j<near.length;j++){const [a,b]=near[i].map(p=>K.local(p,f)),[c,d]=near[j].map(p=>K.local(p,f)),u=V.sub(b,a),v=V.sub(d,c),den=u[0]*v[1]-u[1]*v[0];if(Math.abs(den)<1e-9)continue;const w=V.sub(c,a),t=(w[0]*v[1]-w[1]*v[0])/den,h=(w[0]*u[1]-w[1]*u[0])/den;if(t>=0&&t<=1&&h>=0&&h<=1)add(K.world(V.add(a,V.mul(u,t)),f),'Intersection');}
 if(points.length&&['line','polygon'].includes(tool)){const start=points.at(-1);for(const c of circles){if(Math.abs(V.dot(c.normal,f.n))<.999)continue;const delta=V.sub(start,c.center),dist=V.len(delta);if(dist<=c.radius+1e-6)continue;const u=V.mul(delta,1/dist),v=V.cross(c.normal,u),a=c.radius*c.radius/dist,b=c.radius*Math.sqrt(1-c.radius*c.radius/(dist*dist));for(const sign of [-1,1])add(V.add(c.center,V.add(V.mul(u,a),V.mul(v,b*sign))),'Tangent');}}
 if(candidates.length){candidates.sort((a,b)=>a.dist-b.dist);inferenceLabel=candidates[0].label;return candidates[0].p.slice();}
 if(points.length&&['line','polygon'].includes(tool)){const start=points.at(-1),delta=V.sub(base,start);for(const o of doc.objects.filter(objectVisible))for(const [i,j]of K.featureEdges(o)){let d=V.unit(V.sub(o.vertices[j],o.vertices[i]));if(Math.abs(V.dot(d,f.n))>.0001)continue;for(const [dir,label]of [[d,'Parallel'],[V.cross(f.n,d),'Perpendicular']]){const p=V.add(start,V.mul(dir,V.dot(delta,dir))),q=project(p);if(Math.hypot(x-q[0],y-q[1])<6){inferenceLabel=label;return p;}}}}
 return base;};
const renderBeforePrecisionV2=render;render=function(){renderBeforePrecisionV2();for(const g of doc.guides||[]){const range=Math.max(width,height)/camera.scale*2;ctx.setLineDash([5,5]);line2(ctx,project(V.sub(g.origin,V.mul(g.direction,range))),project(V.add(g.origin,V.mul(g.direction,range))),'#ad64b2',1);ctx.setLineDash([]);}if(inferenceLabel&&hover){const p=project(hover);ctx.font='12px system-ui';ctx.fillStyle=hexColor('--ink');ctx.fillText(inferenceLabel,p[0]+12,p[1]-12);}if(marquee){ctx.strokeStyle='#ca743e';ctx.setLineDash(marquee.x2<marquee.x?[5,3]:[]);ctx.strokeRect(marquee.x,marquee.y,marquee.x2-marquee.x,marquee.y2-marquee.y);ctx.setLineDash([]);}};
const numericBeforeV2=applyNumeric;applyNumeric=function(){const input=$('#numericDraw'),text=input.value;try{if(['rectangle','circle','pushpull'].includes(tool)){input.value=lengthList(text).join(',');numericBeforeV2();input.value=text;}else numericBeforeV2();}catch(e){toast(e.message);}};actions.applyNumeric=applyNumeric;
function guideDialog(){modal('Construction guides',`<label>Input units<select id="unitPreference"><option value="mm">Millimeters</option><option value="cm">Centimeters</option><option value="m">Meters</option><option value="in">Inches</option><option value="ft">Feet</option></select></label><p>Dimensions field accepts units and fractions: 2in, 1 1/2in, 3ft 2in. Separate dimensions with commas.</p><div class="formgrid"><label>Offset U<input id="guideU" value="0"></label><label>Offset V<input id="guideV" value="10"></label><label>Angle from U (degrees)<input id="guideAngle" type="number" value="0"></label></div><button id="addGuide" class="primary wide">Add guide on work plane</button><button id="clearGuides" class="wide">Delete all guides</button>`);$('#unitPreference').value=prefs.units||'mm';$('#unitPreference').onchange=()=>{prefs.units=$('#unitPreference').value;savePrefs();};$('#addGuide').onclick=()=>{try{const f=workFrame(),u=parseLength($('#guideU').value,prefs.units),v=parseLength($('#guideV').value,prefs.units),a=+$('#guideAngle').value*Math.PI/180;if(!Number.isFinite(a))throw Error('Use a finite angle.');edit(()=>{doc.guides=doc.guides||[];doc.guides.push({id:id(),origin:K.world([u,v,0],f),direction:V.add(V.mul(f.u,Math.cos(a)),V.mul(f.v,Math.sin(a)))});});closeDialog();}catch(e){toast(e.message);}};$('#clearGuides').onclick=()=>{edit(()=>doc.guides=[]);closeDialog();};}
function transformDialog(){if(!editable().length)return toast('Select objects first.');const center=K.bounds(editable()).center;modal('Transform selection',`<label>Operation<select id="transformKind"><option value="translate">Move</option><option value="rotate">Rotate</option><option value="scale">Uniform scale</option></select></label><div class="formgrid three">${['X','Y','Z'].map((s,i)=>`<label>Move ${s}<input id="transformD${i}" value="0"></label>`).join('')}</div><label>Rotation axis<select id="transformAxis"><option value="2">Z</option><option value="0">X</option><option value="1">Y</option></select></label><label>Angle / scale factor<input id="transformAmount" type="number" value="90"></label><div class="formgrid three">${['X','Y','Z'].map((s,i)=>`<label>Pivot ${s}<input id="transformC${i}" type="number" value="${center[i]}"></label>`).join('')}</div><label class="check"><input id="transformCopy" type="checkbox"> Transform a copy</label><button id="runTransform" class="primary wide">Apply transform</button>`);$('#runTransform').onclick=()=>{try{const kind=$('#transformKind').value,delta=[0,1,2].map(i=>parseLength($('#transformD'+i).value,prefs.units)),c=[0,1,2].map(i=>+$('#transformC'+i).value),axis=+$('#transformAxis').value,a=+$('#transformAmount').value;if([...c,a].some(v=>!Number.isFinite(v))||(kind==='scale'&&a<=0))throw Error('Use finite values and a positive scale.');edit(()=>{let os=editable();if($('#transformCopy').checked){os=os.map(o=>({...clone(o),id:id(),name:o.name+' copy',group:null}));doc.objects.push(...os);selected=new Set(os.map(o=>o.id));}for(const o of os)K.transform(o,p=>kind==='translate'?V.add(p,delta):kind==='rotate'?K.rotate(p,axis,a,c):V.add(c,V.mul(V.sub(p,c),a)));});closeDialog();}catch(e){toast(e.message);}};}
const selectDownBeforeV2=cadPointerDown;cadPointerDown=function(e,x,y){if(tool==='select'&&selectionMode==='window'&&e.button===0&&!e.altKey&&!spaceDown){marquee={x,y,x2:x,y2:y,add:e.shiftKey};stage.setPointerCapture(e.pointerId);return true;}return selectDownBeforeV2(e,x,y);};
const selectMoveBeforeV2=cadPointerMove;cadPointerMove=function(e,x,y){if(marquee){marquee.x2=x;marquee.y2=y;render();return true;}return selectMoveBeforeV2(e,x,y);};
function endMarquee(cancel=false){if(!marquee)return false;const r=marquee;marquee=null;if(!cancel){const lo=[Math.min(r.x,r.x2),Math.min(r.y,r.y2)],hi=[Math.max(r.x,r.x2),Math.max(r.y,r.y2)],inside=p=>p[0]>=lo[0]&&p[0]<=hi[0]&&p[1]>=lo[1]&&p[1]<=hi[1];if(!r.add)selected.clear();for(const o of doc.objects.filter(objectVisible)){const ps=o.vertices.map(project),contained=ps.every(inside),overlap=Math.max(...ps.map(p=>p[0]))>=lo[0]&&Math.min(...ps.map(p=>p[0]))<=hi[0]&&Math.max(...ps.map(p=>p[1]))>=lo[1]&&Math.min(...ps.map(p=>p[1]))<=hi[1];if(r.x2<r.x?overlap:contained)selected.add(o.id);}selectedFace=null;}sync();return true;}
Object.assign(actions,{guides:guideDialog,transform:transformDialog,windowSelect:()=>{selectionMode='window';setTool('select');$('#selectionMode').textContent='Window / crossing';toast('Drag right for contained objects; left for crossing objects.');},hideSelected:()=>edit(()=>chosen().forEach(o=>o.visible=false)),isolate:()=>edit(()=>doc.objects.forEach(o=>o.visible=selected.has(o.id))),showAll:()=>edit(()=>doc.objects.forEach(o=>o.visible=true))});
// Native dimension changes extend a planar end, preserving solid data.
$$('[data-size]').forEach(e=>{const previous=e.onchange;e.onchange=()=>{const os=editable();if(os.length!==1||!os[0].cad)return previous();cadTask('Resizing solid',async()=>{const o=os[0],m=await cadCall('resize',{object:o,axis:+e.dataset.size,size:+e.value});cadApply(()=>{Object.assign(o,m);selectedFace=null;});});};});
const newProfileBeforeAnalytic=newProfile;newProfile=async function(ps,name){if(name!=='Circle')return newProfileBeforeAnalytic(ps,name);const center=ps.reduce((a,p)=>V.add(a,V.mul(p,1/ps.length)),[0,0,0]),host=doc.objects.find(o=>o.id===sketchHost?.id);await cadTask('Drawing circle',async()=>{const m=await cadCall('circleProfile',{center,radius:V.len(V.sub(ps[0],center)),normal:planeNormal(),object:prefs.plane==='face'?host:null});cadApply(()=>{if(host&&prefs.plane==='face')Object.assign(host,m);else addObject('Circle',m);});points=[];setTool('pushpull');});};
const offsetBeforeNative=offsetDialog;offsetDialog=function(){const o=doc.objects.find(o=>o.id===selectedFace?.id);if(!o?.cad)return offsetBeforeNative();const face=o.cad.faceMap[selectedFace.face];modal('Offset face',`<label>Offset distance (mm)<input id="nativeOffset" type="number" value="-3"></label><label class="check"><input id="offsetDivide" type="checkbox" checked> Divide the source face</label><button id="runNativeOffset" class="primary wide">Create offset</button>`);$('#runNativeOffset').onclick=()=>cadTask('Offsetting face',async()=>{const divide=$('#offsetDivide').checked,m=await cadCall('offset',{object:o,face,distance:+$('#nativeOffset').value,divide});cadApply(()=>{if(divide){Object.assign(o,m);selectedFace=null;}else addObject('Offset profile',m);});closeDialog();});};actions.offset=offsetDialog;
const sweepBeforeNative=sweepDialog;sweepDialog=function(){const os=editable(),profile=os.find(o=>o.faces.length&&(o.cad?o.cad.faces.length===1:o.faces.length===1)),path=os.find(o=>!o.faces.length);if(os.length!==2||!profile||!path)return sweepBeforeNative();cadTask('Sweeping profile',async()=>{const loops=profile.cad?selectedFaceLoops(profile,0):[profile.faces[0].map(i=>profile.vertices[i])];const m=await cadCall('sweep',{loops,path:path.vertices});cadApply(()=>addObject('Sweep',m,profile.color));closeDialog();});};actions.sweep=sweepDialog;
