/* Face materials, portable textures, cameras, and scene states. GPL-3.0-only. */
const texturePixels=new Map();let materialCanvas=null,materialContext=null,materialBuffer=null;
function faceAppearance(o,fi){const key=o.cad?o.cad.faceMap[fi]:fi,id=o.faceMaterials?.[key]||o.material,mat=(doc.materials||[]).find(m=>m.id===id);return mat||{color:o.color,opacity:1};}
function loadTexture(mat){if(!mat.texture||texturePixels.has(mat.id)||typeof Image==='undefined')return;texturePixels.set(mat.id,null);const img=new Image();img.onload=()=>{const c=document.createElement('canvas'),scale=Math.min(1,1024/Math.max(img.width,img.height));c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));const cc=c.getContext('2d');cc.drawImage(img,0,0,c.width,c.height);texturePixels.set(mat.id,{data:cc.getImageData(0,0,c.width,c.height).data,width:c.width,height:c.height});render();};img.onerror=()=>texturePixels.delete(mat.id);img.src=mat.texture;}
function triangleUV(t,mat){const n=K.normal(t.o.vertices,t.o.faces[t.face]),drop=n.map(Math.abs).indexOf(Math.max(...n.map(Math.abs))),axes=[0,1,2].filter(i=>i!==drop),a=(mat.rotation||0)*Math.PI/180,c=Math.cos(a),s=Math.sin(a),scale=Math.max(.01,mat.scale||50);return t.world.map(p=>[(p[axes[0]]*c-p[axes[1]]*s)/scale+(mat.offsetU||0),(p[axes[0]]*s+p[axes[1]]*c)/scale+(mat.offsetV||0)]);}
function prepareDrawnMaterial(t){const mat=faceAppearance(t.o,t.face);if(mat.texture){loadTexture(mat);t.texture=texturePixels.get(mat.id);t.uv=triangleUV(t,mat);}t.opacity=renderMode==='xray'?.25:mat.opacity??1;}
function drawMaterials(){if(renderMode==='wire'||!drawn.length)return;let needed=false;for(const t of drawn){if(t.shadow)continue;const mat=faceAppearance(t.o,t.face);if(mat.texture){loadTexture(mat);t.texture=texturePixels.get(mat.id);t.uv=triangleUV(t,mat);needed=needed||!!t.texture;}t.opacity=renderMode==='xray'?.25:mat.opacity??1;if(t.opacity<1)needed=true;}if(!needed||fallback)return;
 if(!materialCanvas){materialCanvas=document.createElement('canvas');materialContext=materialCanvas.getContext('2d');}const w=Math.min(canvas.width,1600),h=Math.round(canvas.height*w/canvas.width),scale=w/width;if(materialCanvas.width!==w||materialCanvas.height!==h){materialCanvas.width=w;materialCanvas.height=h;}materialBuffer=K.rasterTriangles(drawn,w,h,scale,materialBuffer);materialContext.putImageData(new ImageData(materialBuffer.pixels,w,h),0,0);ctx.drawImage(materialCanvas,0,0,width,height);
 for(const e of edgeHits)for(const [a,b]of visibleEdgeParts(e,drawn))line2(ctx,a,b,selected.has(e.o.id)?'#df824c':prefs.theme==='light'?'#3e5448':'#b6cbb5',1);
}
function materialsDialog(){doc.materials=doc.materials||[];modal('Materials and textures',`<div class="formgrid"><label>Name<input id="matName" value="Material ${doc.materials.length+1}" maxlength="80"></label><label>Color<input id="matColor" type="color" value="${chosen()[0]?.color||prefs.color}"></label><label>Opacity<input id="matOpacity" type="number" min="0" max="1" step=".05" value="1"></label><label>Texture tile size (mm)<input id="matScale" type="number" min=".01" value="50"></label><label>Texture rotation (degrees)<input id="matRotation" type="number" value="0"></label><label>Texture offset U / V<input id="matOffset" value="0,0"></label></div><label>Texture image<input id="matFile" type="file" accept="image/png,image/jpeg,image/webp"></label><label>Apply to<select id="matScope"><option value="face">Selected face</option><option value="objects">Selected objects</option></select></label><button id="createMaterial" class="primary wide">Create and apply material</button><div id="materialLibrary">${doc.materials.map(m=>`<div class="projectRow"><span><span class="dot" style="--swatch:${m.color}"></span>${esc(m.name)}</span><button data-material-apply="${m.id}">Apply</button><button data-material-edit="${m.id}">Edit</button></div>`).join('')}</div><button id="sampleMaterial" class="wide">Sample selected face</button>`);
 const apply=mid=>{edit(()=>{if($('#matScope').value==='face'&&selectedFace){const o=doc.objects.find(o=>o.id===selectedFace.id);if(objectLocked(o))throw Error('Unlock this object.');o.faceMaterials=o.faceMaterials||{};o.faceMaterials[o.cad?o.cad.faceMap[selectedFace.face]:selectedFace.face]=mid;}else editable().forEach(o=>o.material=mid);});};
 $('#createMaterial').onclick=async()=>{try{const [offsetU,offsetV]=$('#matOffset').value.split(',').map(Number),mat={id:id(),name:$('#matName').value.slice(0,80),color:$('#matColor').value,opacity:+$('#matOpacity').value,scale:+$('#matScale').value,rotation:+$('#matRotation').value,offsetU,offsetV};if([mat.opacity,mat.scale,mat.rotation,offsetU,offsetV].some(v=>!Number.isFinite(v))||mat.opacity<0||mat.opacity>1||mat.scale<=0)throw Error('Use a positive texture size, finite offsets, and opacity from 0 to 1.');const file=$('#matFile').files[0];if(file){if(file.size>4000000||!['image/png','image/jpeg','image/webp'].includes(file.type))throw Error('Choose a PNG, JPEG, or WebP up to 4 MB.');mat.texture=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('Image read failed.'));r.readAsDataURL(file);});}edit(()=>{doc.materials.push(mat);if(selectedFace&&$('#matScope').value==='face'){const o=doc.objects.find(o=>o.id===selectedFace.id);if(objectLocked(o))throw Error('Unlock this object.');o.faceMaterials=o.faceMaterials||{};o.faceMaterials[o.cad?o.cad.faceMap[selectedFace.face]:selectedFace.face]=mat.id;}else editable().forEach(o=>o.material=mat.id);});closeDialog();}catch(e){toast(e.message);}};
 $$('[data-material-apply]').forEach(b=>b.onclick=()=>{apply(b.dataset.materialApply);closeDialog();});$$('[data-material-edit]').forEach(b=>b.onclick=()=>{const m=doc.materials.find(m=>m.id===b.dataset.materialEdit);$('#matName').value=m.name;$('#matColor').value=m.color;$('#matOpacity').value=m.opacity;$('#matScale').value=m.scale;$('#matRotation').value=m.rotation;$('#matOffset').value=[m.offsetU||0,m.offsetV||0].join(',');$('#createMaterial').textContent='Update material';$('#createMaterial').onclick=()=>{const nums=[$('#matOpacity').value,$('#matScale').value,$('#matRotation').value,...$('#matOffset').value.split(',')].map(Number);if(nums.length!==5||nums.some(n=>!Number.isFinite(n))||nums[1]<=0||nums[0]<0||nums[0]>1)return toast('Use valid texture settings.');edit(()=>Object.assign(m,{name:$('#matName').value.slice(0,80),color:$('#matColor').value,opacity:nums[0],scale:nums[1],rotation:nums[2],offsetU:nums[3],offsetV:nums[4]}));closeDialog();};});$('#sampleMaterial').onclick=()=>{const o=doc.objects.find(o=>o.id===selectedFace?.id);if(!o)return toast('Select a face first.');const m=faceAppearance(o,selectedFace.face);$('#matColor').value=m.color;$('#matOpacity').value=m.opacity??1;$('#matScale').value=m.scale||50;$('#matRotation').value=m.rotation||0;};
}
const projectBeforePerspective=project;project=function(p){if(!camera.perspective)return projectBeforePerspective(p);const b=basis(),q=V.sub(p,camera.target),focal=height/2/Math.tan((camera.fov||45)*Math.PI/360),distance=focal/camera.scale,depth=distance-V.dot(q,b.back),factor=focal/Math.max(.01,depth);return [width/2+V.dot(q,b.right)*factor,height/2-V.dot(q,b.up)*factor,distance/Math.max(.01,depth)];};
const depthBeforePerspective=sceneDepth;sceneDepth=function(back){if(!camera.perspective)return depthBeforePerspective(back);let d=1;for(const o of doc.objects.filter(objectVisible))for(const p of o.vertices)d=Math.max(d,Math.abs(project(p)[2]));return d*1.1;};
const planeBeforePerspective=planePoint;planePoint=function(x,y){if(!camera.perspective)return planeBeforePerspective(x,y);const b=basis(),focal=height/2/Math.tan((camera.fov||45)*Math.PI/360),distance=focal/camera.scale,eye=V.add(camera.target,V.mul(b.back,distance)),dir=V.add(V.mul(b.back,-1),V.add(V.mul(b.right,(x-width/2)/focal),V.mul(b.up,-(y-height/2)/focal))),f=workFrame(),den=V.dot(dir,f.n);if(Math.abs(den)<1e-6)return null;const t=V.dot(V.sub(f.o,eye),f.n)/den;return t>0?V.add(eye,V.mul(dir,t)):null;};
function cameraDialog(){modal('Camera and display',`<label>Projection<select id="cameraProjection"><option value="ortho">Orthographic</option><option value="perspective">Perspective</option><option value="two">Two-point perspective</option></select></label><label>Field of view (degrees)<input id="cameraFOV" type="number" min="10" max="100" value="${camera.fov||45}"></label><label class="check"><input id="walkMode" type="checkbox"> Walk controls · W/A/S/D, Q/E up/down</label><button id="applyCamera" class="primary wide">Apply camera</button><div class="inline"><button data-action="xray">Toggle X-ray</button><button data-action="views">Scenes</button></div>`);$('#cameraProjection').value=camera.perspective?'perspective':'ortho';$('#walkMode').checked=!!prefs.walk;$('#applyCamera').onclick=()=>{const fov=+$('#cameraFOV').value;if(fov<10||fov>100||!Number.isFinite(fov))return toast('FOV must be 10–100 degrees.');camera.perspective=$('#cameraProjection').value!=='ortho';if($('#cameraProjection').value==='two')camera.el=0;camera.fov=fov;prefs.walk=$('#walkMode').checked;savePrefs();render();closeDialog();};}
function sceneData(){return {camera:clone(camera),renderMode,theme:prefs.theme,visibility:doc.objects.map(o=>({id:o.id,visible:o.visible})),layers:clone(doc.layers),section:clone(doc.section||null),smooth:prefs.smooth!==false,shadows:!!prefs.shadows};}
function restoreScene(s){camera=clone(s.camera);renderMode=s.renderMode||'shaded';prefs.theme=s.theme||prefs.theme;for(const v of s.visibility||[]){const o=doc.objects.find(o=>o.id===v.id);if(o)o.visible=v.visible;}for(const l of s.layers||[]){const cur=doc.layers.find(x=>x.id===l.id);if(cur)cur.visible=l.visible;}doc.section=clone(s.section||null);prefs.smooth=s.smooth!==false;prefs.shadows=!!s.shadows;applyPrefs();sync();}
viewsDialog=function(){modal('Scenes',`<label>Scene name<input id="sceneName" value="Scene ${(doc.scenes||[]).length+1}" maxlength="80"></label><button id="addScene" class="primary wide">Save camera, visibility, style, and section</button>${(doc.scenes||[]).map(s=>`<div class="projectRow"><span>${esc(s.name)}</span><button data-scene-load="${s.id}">Restore</button><button data-scene-update="${s.id}">Update</button><button data-scene-delete="${s.id}">Delete</button></div>`).join('')}${(doc.views||[]).map(v=>`<button class="wide" data-legacy-view="${v.id}">${esc(v.name)} · previous camera view</button>`).join('')}`);$('#addScene').onclick=()=>{edit(()=>{doc.scenes=doc.scenes||[];doc.scenes.push({id:id(),name:$('#sceneName').value.slice(0,80),...sceneData()});});viewsDialog();};$$('[data-scene-load]').forEach(b=>b.onclick=()=>{const s=doc.scenes.find(s=>s.id===b.dataset.sceneLoad);edit(()=>restoreScene(s));closeDialog();});$$('[data-scene-update]').forEach(b=>b.onclick=()=>{edit(()=>Object.assign(doc.scenes.find(s=>s.id===b.dataset.sceneUpdate),sceneData()));viewsDialog();});$$('[data-scene-delete]').forEach(b=>b.onclick=()=>{edit(()=>doc.scenes=doc.scenes.filter(s=>s.id!==b.dataset.sceneDelete));viewsDialog();});$$('[data-legacy-view]').forEach(b=>b.onclick=()=>{camera=clone(doc.views.find(v=>v.id===b.dataset.legacyView).camera);render();closeDialog();});};
Object.assign(actions,{materials:materialsDialog,camera:cameraDialog,views:viewsDialog,xray:()=>{renderMode=renderMode==='xray'?'shaded':'xray';render();}});
document.addEventListener('keydown',e=>{if(!prefs.walk||e.target.matches('input,textarea,select')||$('#dialog').open||e.ctrlKey||e.metaKey)return;const k=e.key.toLowerCase(),b=basis(),step=(e.shiftKey?50:10)/Math.max(.1,camera.scale/2.8),dir={w:V.mul(b.back,-1),s:b.back,a:V.mul(b.right,-1),d:b.right,q:[0,0,-1],e:[0,0,1]}[k];if(dir){e.preventDefault();camera.target=V.add(camera.target,V.mul(dir,step));render();}});
const validateBeforePresentation=validateProject;validateProject=function(data){const d=validateBeforePresentation(data);d.materials=clone(data.materials||[]);if(d.materials.length>200)throw Error('Material limit: 200.');for(const m of d.materials){if(!/^[a-z\d_-]{1,100}$/i.test(m.id)||typeof m.name!=='string'||m.name.length>80||!/^#[a-f\d]{6}$/i.test(m.color)||!Number.isFinite(m.opacity)||m.opacity<0||m.opacity>1||!Number.isFinite(m.scale)||m.scale<=0||m.texture&&(!/^data:image\/(png|jpeg|webp);base64,[a-z\d+/=]+$/i.test(m.texture)||m.texture.length>6000000))throw Error('Invalid material.');}d.objects.forEach((o,i)=>{o.material=data.objects[i].material||null;o.faceMaterials=clone(data.objects[i].faceMaterials||{});});d.scenes=clone(data.scenes||[]);if(d.scenes.length>100)throw Error('Scene limit: 100.');for(const s of d.scenes)if(!/^[a-z\d_-]{1,100}$/i.test(s.id)||typeof s.name!=='string'||s.name.length>80||!s.camera||!Number.isFinite(s.camera.az)||!Number.isFinite(s.camera.el)||!Array.isArray(s.camera.target)||s.camera.target.length!==3||s.camera.target.some(v=>!Number.isFinite(v))||!Number.isFinite(s.camera.scale)||s.camera.scale<=0)throw Error('Invalid scene.');d.section=clone(data.section||null);return d;};
// Two-pointer navigation; primary modeling remains an explicit tool.
const touches=new Map();let pinch=null;
stage.addEventListener('pointerdown',e=>{if(e.pointerType!=='touch')return;touches.set(e.pointerId,pointer(e));if(touches.size===2){endGesture(true);cadPointerUp(true);const [a,b]=[...touches.values()];pinch={distance:Math.hypot(a[0]-b[0],a[1]-b[1]),center:V.mul(V.add([...a,0],[...b,0]),.5),camera:clone(camera)};e.preventDefault();e.stopImmediatePropagation();}},true);
stage.addEventListener('pointermove',e=>{if(!touches.has(e.pointerId))return;touches.set(e.pointerId,pointer(e));if(!pinch||touches.size!==2)return;const [a,b]=[...touches.values()],dist=Math.hypot(a[0]-b[0],a[1]-b[1]),c=V.mul(V.add([...a,0],[...b,0]),.5);camera=clone(pinch.camera);camera.scale=Math.max(.01,Math.min(150,pinch.camera.scale*dist/Math.max(1,pinch.distance)));const basisNow=basis();camera.target=V.add(camera.target,V.add(V.mul(basisNow.right,-(c[0]-pinch.center[0])/camera.scale),V.mul(basisNow.up,(c[1]-pinch.center[1])/camera.scale)));e.preventDefault();e.stopImmediatePropagation();render();},true);
for(const name of ['pointerup','pointercancel'])stage.addEventListener(name,e=>{touches.delete(e.pointerId);if(touches.size<2)pinch=null;},true);
