/* Durable local projects, layers, and reusable parts. GPL-3.0-only. */
const originalValidate=validateProject;
function newDocument(name='Untitled model'){return {app:'SKETCHBENCH',schema:2,version:VERSION,projectId:id(),name,units:'mm',objects:[],layers:[],annotations:[],views:[],components:[]};}
validateProject=function(data){if(!data||![1,2].includes(data.schema))throw Error('Unsupported project schema; use a SKETCHBENCH schema 1 or 2 file.');const d=originalValidate({...data,schema:1});d.schema=2;d.projectId=typeof data.projectId==='string'&&/^[a-z\d_-]{1,100}$/i.test(data.projectId)?data.projectId:id();const array=(a,max,name)=>{if(a===undefined)return [];if(!Array.isArray(a)||a.length>max)throw Error('Invalid or oversized '+name+'.');return a;};const safeID=v=>typeof v==='string'&&/^[a-z\d_-]{1,100}$/i.test(v)?v:id(),finite3=p=>Array.isArray(p)&&p.length===3&&p.every(v=>Number.isFinite(v)&&Math.abs(v)<=1e7);
 d.layers=array(data.layers,100,'layers').map(l=>({id:safeID(l.id),name:String(l.name||'Layer').slice(0,80),visible:l.visible!==false,locked:!!l.locked}));const layerIDs=new Set(d.layers.map(l=>l.id));if(layerIDs.size!==d.layers.length)throw Error('Duplicate layer IDs.');for(let i=0;i<d.objects.length;i++)d.objects[i].layer=layerIDs.has(data.objects[i].layer)?data.objects[i].layer:null;
 d.annotations=array(data.annotations,100,'dimensions').map(a=>{if(!Array.isArray(a.points)||a.points.length!==(a.kind==='angle'?3:2)||!a.points.every(finite3))throw Error('Invalid dimension endpoints.');return {id:safeID(a.id),label:String(a.label||'Dimension').slice(0,100),kind:['angle','leader'].includes(a.kind)?a.kind:'linear',points:clone(a.points)};});
 d.views=array(data.views,50,'views').map(v=>{const c=v.camera;if(!c||!finite3(c.target)||!Number.isFinite(c.az)||!Number.isFinite(c.el)||!Number.isFinite(c.scale)||c.scale<.01||c.scale>150)throw Error('Invalid saved camera.');return {id:safeID(v.id),name:String(v.name||'View').slice(0,80),camera:{az:c.az,el:c.el,scale:c.scale,target:c.target.slice()}};});
 let totalVertices=d.objects.reduce((s,o)=>s+o.vertices.length,0);d.components=array(data.components,50,'reusable parts').map(c=>{const os=array(c.objects,100,'component objects'),validated=originalValidate({app:'SKETCHBENCH',schema:1,name:'Part',units:'mm',objects:os});totalVertices+=validated.objects.reduce((s,o)=>s+o.vertices.length,0);if(totalVertices>250000)throw Error('Project and parts exceed 250,000 vertices.');return {id:safeID(c.id),name:String(c.name||'Part').slice(0,80),objects:validated.objects};});return d;};
function projectRecord(data,thumb=''){return {projectId:data.projectId,name:data.name,savedAt:Date.now(),trashed:false,thumbnail:thumb,data};}
function thumb(){try{const c=document.createElement('canvas');c.width=180;c.height=120;c.getContext('2d').drawImage(canvas,0,0,180,120);return c.toDataURL('image/png');}catch{return '';}}
const slotKey=p=>'project:'+p;
async function putRecord(record){if(db)await transaction('readwrite',s=>s.put(record,slotKey(record.projectId)));else{localStorage.setItem(KEY+':'+slotKey(record.projectId),JSON.stringify(record));let ids=JSON.parse(localStorage.getItem(KEY+'-index')||'[]');if(!ids.includes(record.projectId)){ids.push(record.projectId);localStorage.setItem(KEY+'-index',JSON.stringify(ids));}}}
async function getRecord(pid){return db?readStore(slotKey(pid)):JSON.parse(localStorage.getItem(KEY+':'+slotKey(pid))||'null');}
async function allRecords(){if(db)return new Promise((resolve,reject)=>{const req=db.transaction('models').objectStore('models').getAll();req.onsuccess=()=>resolve(req.result.filter(v=>v&&v.data&&v.projectId));req.onerror=()=>reject(req.error);});let ids=JSON.parse(localStorage.getItem(KEY+'-index')||'[]');return ids.map(pid=>{try{return JSON.parse(localStorage.getItem(KEY+':'+slotKey(pid))||'null');}catch{return null;}}).filter(Boolean);}
let saveError=false;
save=async function(){if(!dirty)return;if(conflict){$('#saveState').textContent='Other tab changed this project · export backup';$('#saveState').className='error';return;}const data=clone(doc),json=JSON.stringify(data),image=thumb();$('#saveState').textContent='Saving…';saveQueue=saveQueue.catch(()=>{}).then(async()=>{try{const record=projectRecord(data,image);if(db){await transaction('readwrite',s=>{if(savedSnapshot?.projectId===data.projectId)s.put(savedSnapshot,'recovery:'+data.projectId);s.put(record,slotKey(data.projectId));s.put(data,'current');});}else{if(savedSnapshot?.projectId===data.projectId)localStorage.setItem(KEY+'-recovery:'+data.projectId,JSON.stringify(savedSnapshot));await putRecord(record);localStorage.setItem(KEY,json);}savedSnapshot=data;saveError=false;if(snapshot()===json)dirty=false;$('#saveState').textContent=dirty?'Unsaved':'Saved locally';$('#saveState').className=dirty?'dirty':'saved';try{localStorage.setItem(KEY+'-ping',JSON.stringify({project:data.projectId,tab:tabId,time:Date.now()}));}catch{}}catch(e){saveError=true;$('#saveState').textContent='Save failed · export project';$('#saveState').className='error';toast('Storage could not save this project. Export a backup before switching projects.',10000);}});await saveQueue;};
async function openDB(name){return new Promise((resolve,reject)=>{let req=indexedDB.open(name,1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains('models'))req.result.createObjectStore('models');};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);req.onblocked=()=>reject(Error('Storage blocked'));});}
load=async function(){doc=newDocument();try{db=await openDB(KEY);}catch{db=null;}try{let value=db?await readStore('current'):JSON.parse(localStorage.getItem(KEY)||'null');if(!value&&KEY!=='sketchbench-v1'){try{if(db){const legacy=await openDB('sketchbench-v1');value=await new Promise(resolve=>{const q=legacy.transaction('models').objectStore('models').get('current');q.onsuccess=()=>resolve(q.result);q.onerror=()=>resolve(null);});legacy.close();}else value=JSON.parse(localStorage.getItem('sketchbench-v1')||'null');}catch{}}if(value){doc=validateProject(value);savedSnapshot=clone(doc);if(value.schema===1){dirty=true;await save();}fit();}}catch(e){toast('Saved project could not be opened. Use Projects to recover another saved copy or import a backup.',12000);$('#saveState').textContent='Recovery needed';$('#saveState').className='error';}applyPrefs();setTool('select');sync();};
async function saveBeforeSwitch(){clearTimeout(saveTimer);await save();await saveQueue;if(dirty||saveError||conflict){toast('Project switch paused. Export a backup, then resolve the save warning.',9000);return false;}return true;}
async function activateProject(data){if(!await saveBeforeSwitch())return false;const next=validateProject(data);doc=next;history=[];future=[];selected.clear();selectedFace=null;points=[];measure=null;customFrame=null;if(prefs.plane==='face')prefs.plane='xy';savedSnapshot=clone(doc);dirty=true;conflict=false;await save();setTool('select');fit();sync();return true;}
async function projectsDialog(showTrash=false){try{await save();const records=(await allRecords()).filter(r=>!!r.trashed===showTrash).sort((a,b)=>b.savedAt-a.savedAt);modal(showTrash?'Project trash':'Local projects',`<p>Stored in this browser. Export files for backups or moving to another device.</p><div class="inline"><button data-action="new">New project</button><button id="toggleProjectTrash">${showTrash?'Back to projects':'Open trash'}</button></div>${records.length?records.map(r=>`<div class="projectRow">${/^data:image\/png;base64,[a-z\d+/=]+$/i.test(r.thumbnail||'')?`<img width="75" height="50" alt="Model preview" src="${r.thumbnail}">`:''}<span><b>${esc(r.name)}</b><small>${new Date(r.savedAt).toLocaleString()}</small></span>${showTrash?`<button data-project-restore="${esc(r.projectId)}">Restore</button>`:`<button data-project-open="${esc(r.projectId)}">Open</button><button data-project-copy="${esc(r.projectId)}">Copy</button><button data-project-trash="${esc(r.projectId)}" ${r.projectId===doc.projectId?'disabled title="Open another project before moving this one to trash"':''}>Trash</button>`}</div>`).join(''):'<p>No projects here yet.</p>'}`);$('#toggleProjectTrash').onclick=()=>projectsDialog(!showTrash);$$('[data-project-open]').forEach(b=>b.onclick=async()=>{const r=await getRecord(b.dataset.projectOpen);if(r&&await activateProject(r.data))closeDialog();});$$('[data-project-copy]').forEach(b=>b.onclick=async()=>{try{const r=await getRecord(b.dataset.projectCopy),d=validateProject(r.data);d.projectId=id();d.name+=' copy';await putRecord(projectRecord(d,r.thumbnail));projectsDialog();}catch(e){toast('Could not copy project: '+e.message,8000);}});for(const [attr,value]of[['projectTrash',true],['projectRestore',false]])$$('[data-'+(value?'project-trash':'project-restore')+']').forEach(b=>b.onclick=async()=>{try{const r=await getRecord(b.dataset[attr]);r.trashed=value;await putRecord(r);projectsDialog(showTrash);}catch(e){toast('Project change failed: '+e.message,8000);}});}catch(e){toast('Could not read local projects. Export your active model as a backup.',9000);}}
async function freshProject(){if(!await saveBeforeSwitch())return;doc=newDocument();history=[];future=[];selected.clear();selectedFace=null;measure=null;customFrame=null;if(prefs.plane==='face')prefs.plane='xy';savedSnapshot=null;changed();setTool('select');setView('iso');fit();closeDialog();}
const oldFresh=fresh;fresh=function(){oldFresh();doc.schema=2;doc.projectId=id();doc.layers=[];doc.annotations=[];doc.views=[];doc.components=[];};
const sampleOriginal=sample;sample=function(){sampleOriginal();doc.schema=2;doc.projectId=doc.projectId||id();doc.layers=doc.layers||[];doc.annotations=[];doc.views=[];doc.components=doc.components||[];};
const oldMakeObject=makeObject;makeObject=function(name,mesh,color){return {...oldMakeObject(name,mesh,color),layer:null};};
function layersDialog(){modal('Layers',`<p>Organize parts and hide or lock them together. Object controls still apply within visible layers.</p><label>New layer name<input id="layerName" value="Layer ${(doc.layers||[]).length+1}" maxlength="80"></label><button id="addLayer" class="wide primary">Create layer</button><label>Assign selected objects<select id="assignLayer"><option value="">No layer</option>${(doc.layers||[]).map(l=>`<option value="${esc(l.id)}">${esc(l.name)}</option>`).join('')}</select></label><button id="applyLayer" class="wide" ${editable().length?'':'disabled'}>Assign selection</button>${(doc.layers||[]).map(l=>`<div class="projectRow"><span>${esc(l.name)}</span><button data-layer-show="${esc(l.id)}">${l.visible?'Hide':'Show'}</button><button data-layer-lock="${esc(l.id)}">${l.locked?'Unlock':'Lock'}</button><button data-layer-delete="${esc(l.id)}">Remove</button></div>`).join('')}`);$('#addLayer').onclick=()=>{if((doc.layers||[]).length>=100){toast('Maximum 100 layers.');return;}edit(()=>{doc.layers=doc.layers||[];doc.layers.push({id:id(),name:$('#layerName').value.slice(0,80)||'Layer',visible:true,locked:false});});layersDialog();};$('#applyLayer').onclick=()=>{edit(()=>editable().forEach(o=>o.layer=$('#assignLayer').value||null));closeDialog();};$$('[data-layer-show]').forEach(b=>b.onclick=()=>{edit(()=>{const l=doc.layers.find(l=>l.id===b.dataset.layerShow);l.visible=!l.visible;});layersDialog();});$$('[data-layer-lock]').forEach(b=>b.onclick=()=>{edit(()=>{const l=doc.layers.find(l=>l.id===b.dataset.layerLock);l.locked=!l.locked;});layersDialog();});$$('[data-layer-delete]').forEach(b=>b.onclick=()=>{edit(()=>{const lid=b.dataset.layerDelete;doc.objects.filter(o=>o.layer===lid).forEach(o=>o.layer=null);doc.layers=doc.layers.filter(l=>l.id!==lid);});layersDialog();});}
function componentsDialog(){modal('Reusable parts',`<p>Save a selection as a reusable part. Insertions are independent copies. Parts travel with this project’s JSON backup.</p><label>Part name<input id="partName" value="${esc(chosen()[0]?.name||'Part')}" maxlength="80"></label><button id="savePart" class="primary wide" ${selected.size?'':'disabled'}>Save selected objects as a part</button>${(doc.components||[]).map(c=>`<div class="projectRow"><span>${esc(c.name)}<small>${c.objects.length} object(s)</small></span><button data-part-insert="${esc(c.id)}">Insert</button><button data-part-delete="${esc(c.id)}">Remove</button></div>`).join('')}`);$('#savePart').onclick=()=>{if((doc.components||[]).length>=50||chosen().length>100){toast('Limit: 50 reusable parts, 100 objects per part.');return;}edit(()=>{const objects=clone(chosen()),center=K.bounds(objects).center;objects.forEach(o=>{K.transform(o,p=>V.sub(p,center));o.layer=null;});doc.components=doc.components||[];doc.components.push({id:id(),name:$('#partName').value.slice(0,80)||'Part',objects});validateProject(doc);});componentsDialog();};$$('[data-part-insert]').forEach(b=>b.onclick=()=>{const part=doc.components.find(c=>c.id===b.dataset.partInsert);edit(()=>{selected.clear();const group=id();for(const src of part.objects){const o=clone(src);o.id=id();o.group=part.objects.length>1?group:null;o.layer=null;o.locked=false;o.visible=true;K.transform(o,p=>V.add(p,camera.target));doc.objects.push(o);selected.add(o.id);}selectedFace=null;});closeDialog();});$$('[data-part-delete]').forEach(b=>b.onclick=()=>{edit(()=>doc.components=doc.components.filter(c=>c.id!==b.dataset.partDelete));componentsDialog();});}
Object.assign(actions,{projects:projectsDialog,new:freshProject,layers:layersDialog,components:componentsDialog,sample:async()=>{if(!await saveBeforeSwitch())return;await freshProject();sample();},recover:async()=>{try{const data=db?await readStore('recovery:'+doc.projectId):JSON.parse(localStorage.getItem(KEY+'-recovery:'+doc.projectId)||'null');if(!data){toast('No previous save exists for this project.');return;}confirmReplace('Restore previous save?',()=>{const next=validateProject(data);edit(()=>{doc=next;selected.clear();selectedFace=null;});closeDialog();fit();});}catch(e){toast('Recovery failed: '+e.message,8000);}}});
const fileMenuOld=fileMenu;fileMenu=function(){fileMenuOld();const box=$('#dialogBody .actionlist');const b=document.createElement('button');b.textContent='Local projects and trash';b.dataset.action='projects';box.prepend(b);};actions.file=fileMenu;
const originalImport=importFile;importFile=async function(file){if(!file)return;const ext=file.name.split('.').pop().toLowerCase();if(['json','sketchbench'].includes(ext)){try{if(file.size>25*1024*1024)throw Error('Maximum 25 MB.');const next=validateProject(JSON.parse(await file.text()));next.projectId=id();if(await activateProject(next)){closeDialog();toast('Imported as a new local project.');}}catch(e){toast('Import rejected: '+e.message,9000);}return;}return originalImport(file);};
// Limit undo memory independently of the number of steps.
const editOriginal=edit;edit=function(fn){const result=editOriginal(fn);let bytes=history.reduce((s,h)=>s+h.length,0);while(bytes>20000000&&history.length>1)bytes-=history.shift().length;return result;};
