/* Bounded BSP operations for closed polygon meshes. GPL-3.0-only. */
(function(K){
'use strict';
const {V}=K,EPS=1e-5;
class Polygon{constructor(v){this.v=v;this.n=V.unit(V.cross(V.sub(v[1],v[0]),V.sub(v[2],v[0])));this.w=V.dot(this.n,v[0]);}flip(){this.v.reverse();this.n=V.mul(this.n,-1);this.w=-this.w;}}
function cut(poly,n,w,same,opposite,front,back){const types=poly.v.map(p=>{const d=V.dot(n,p)-w;return d>EPS?1:d<-EPS?2:0;}),type=types.reduce((a,b)=>a|b,0);if(type===0){(V.dot(n,poly.n)>0?same:opposite).push(poly);return;}if(type===1){front.push(poly);return;}if(type===2){back.push(poly);return;}const f=[],b=[];for(let i=0;i<poly.v.length;i++){const j=(i+1)%poly.v.length,a=poly.v[i],c=poly.v[j],ta=types[i],tb=types[j];if(ta!==2)f.push(a.slice());if(ta!==1)b.push(a.slice());if((ta|tb)===3){const t=(w-V.dot(n,a))/V.dot(n,V.sub(c,a)),p=V.add(a,V.mul(V.sub(c,a),t));f.push(p.slice());b.push(p.slice());}}for(const [v,out]of[[f,front],[b,back]]){const clean=v.filter((p,i)=>V.len(V.sub(p,v[(i+1)%v.length]))>EPS*.1);if(clean.length>=3){const p=makePolygon(clean);if(p)out.push(p);}}}
function makePolygon(v){for(let i=1;i<v.length-1;i++){const n=V.cross(V.sub(v[i],v[0]),V.sub(v[i+1],v[0]));if(V.len(n)>EPS*EPS){const p=new Polygon([v[0],v[i],v[i+1]]);p.v=v;return p;}}return null;}
class Tree{constructor(polys,budget,depth=0){this.polys=[];this.f=null;this.b=null;this.n=null;this.w=0;this.budget=budget;this.depth=depth;if(polys?.length)this.build(polys);}check(){this.budget.count++;if(this.depth>1800||this.budget.count>300000||Date.now()>this.budget.until)throw Error('Solid operation reached its complexity limit. Use simpler meshes.');}build(polys){this.check();if(!polys.length)return;if(!this.n){const seed=polys[Math.floor(polys.length/2)];this.n=seed.n.slice();this.w=seed.w;}const f=[],b=[];for(const p of polys)cut(p,this.n,this.w,this.polys,this.polys,f,b);if(f.length){if(!this.f)this.f=new Tree(null,this.budget,this.depth+1);this.f.build(f);}if(b.length){if(!this.b)this.b=new Tree(null,this.budget,this.depth+1);this.b.build(b);}}all(){return [...this.polys,...(this.f?this.f.all():[]),...(this.b?this.b.all():[])];}invert(){this.polys.forEach(p=>p.flip());if(this.n){this.n=V.mul(this.n,-1);this.w=-this.w;}this.f?.invert();this.b?.invert();[this.f,this.b]=[this.b,this.f];}clip(polys){this.check();if(!this.n)return polys.slice();let f=[],b=[];for(const p of polys)cut(p,this.n,this.w,f,b,f,b);if(this.f)f=this.f.clip(f);b=this.b?this.b.clip(b):[];return f.concat(b);}clipTo(other){this.polys=other.clip(this.polys);this.f?.clipTo(other);this.b?.clipTo(other);}}
function stitch(m){m=K.weld(m);if(m.vertices.length>6000||m.faces.length>12000)throw Error('Result is too complex to validate.');const vertices=m.vertices,faces=[];for(const f of m.faces){const out=[];for(let i=0;i<f.length;i++){const a=f[i],b=f[(i+1)%f.length],p=vertices[a],d=V.sub(vertices[b],p),len=V.dot(d,d),inter=[];if(len<EPS*EPS)continue;out.push(a);for(let j=0;j<vertices.length;j++){if(j===a||j===b)continue;const q=V.sub(vertices[j],p),t=V.dot(q,d)/len;if(t>EPS&&t<1-EPS&&V.len(V.sub(q,V.mul(d,t)))<EPS)inter.push([t,j]);}inter.sort((a,b)=>a[0]-b[0]);out.push(...inter.map(i=>i[1]));}if(out.length>=3)faces.push(out);}return {vertices,faces,edges:[]};}
function boolean(a,b,op){if(!['union','subtract','intersect'].includes(op))throw Error('Unknown solid operation.');for(const m of [a,b]){const d=K.diagnose(m,true);if(!d.closed||d.nonplanar||d.intersections)throw Error('Solid operations require closed, outward, nonintersecting input meshes. Inspect or repair each object first.');}const ta=K.triangles(a),tb=K.triangles(b);if(ta.length+tb.length>3000)throw Error('Solid operations support up to 3,000 input triangles combined.');const budget={count:0,until:Date.now()+6000},A=new Tree(ta.map(t=>new Polygon(t.points.map(p=>p.slice()))),budget),B=new Tree(tb.map(t=>new Polygon(t.points.map(p=>p.slice()))),budget);
 if(op==='union'){A.clipTo(B);B.clipTo(A);B.invert();B.clipTo(A);B.invert();A.build(B.all());}
 if(op==='subtract'){A.invert();A.clipTo(B);B.clipTo(A);B.invert();B.clipTo(A);B.invert();A.build(B.all());A.invert();}
 if(op==='intersect'){A.invert();B.clipTo(A);B.invert();A.clipTo(B);B.clipTo(A);A.build(B.all());A.invert();}
 const vertices=[],faces=[];for(const p of A.all()){if(V.len(p.n)<.5)continue;faces.push(p.v.map(v=>{vertices.push(v);return vertices.length-1;}));}if(!faces.length)return {vertices:[],faces:[],edges:[]};const m=stitch({vertices,faces,edges:[]}),result=K.diagnose(m);if(!result.closed)throw Error('The solid result failed topology checks. Inputs were preserved. Try reducing coincident surfaces or simplifying the meshes.');K.validateMesh(m);return m;}
Object.assign(K,{boolean,stitch});
})(typeof module!=='undefined'?module.exports=require('./geometry-plus.js'):K);
