// Controller tests use a DOM stub. They do not render or simulate a real browser.
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const K=require('../interchange.js'),app=['app.js','precision.js','sketch-regions.js','viewport-surfaces.js','studio.js','projects.js','export-ui.js','finish.js','examples.js','bootstrap.js'].map(n=>fs.readFileSync(path.join(__dirname,'..',n),'utf8')).join('\n'),shell=fs.readFileSync(path.join(__dirname,'../shell.html'),'utf8');
function environment(storage=new Map(),source=app){
 const nodes=new Map(),all=[],timers=new Map();let seq=0;const errors=[],downloads=[];
 const context2d=new Proxy({measureText:t=>({width:t.length*7})},{get:(o,k)=>k in o?o[k]:(()=>{}),set:(o,k,v)=>(o[k]=v,true)});
 class Element{
  constructor(tag='div',attrs={}){this.tagName=tag.toUpperCase();this.attrs=attrs;this.dataset={};for(const [k,v]of Object.entries(attrs))if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=v;this.value=attrs.value||'';this.textContent='';this.style={};this.hidden=false;this.disabled=false;this.checked=false;this.open=false;this.children=[];this.complete=true;this.files=[];this.events={};const set=new Set();this.classList={add:v=>set.add(v),remove:v=>set.delete(v),toggle:(v,on)=>on?set.add(v):set.delete(v),contains:v=>set.has(v)};if(attrs.id)nodes.set(attrs.id,this);all.push(this);}
  set innerHTML(v){this.html=v;parse(v);}get innerHTML(){return this.html||'';}addEventListener(n,f){const before=this.events[n];this.events[n]=e=>{before?.(e);f(e);};}setAttribute(k,v){this.attrs[k]=v;}getAttribute(k){return this.attrs[k];}append(n){this.children.push(n);}prepend(n){this.children.unshift(n);}replaceChildren(){this.children=[];}getBoundingClientRect(){return {width:900,height:700,left:0,top:0};}getContext(k){return k==='2d'?context2d:null;}setPointerCapture(){}focus(){}showModal(){this.open=true;}close(){this.open=false;}click(){if(this.tagName==='A')downloads.push(this.download);this.onclick?.({target:this});}querySelector(s){return query(s);}matches(){return false;}toDataURL(){return 'data:image/png;base64,test';}toBlob(fn){fn(new Blob(['test'],{type:'image/png'}));}
 }
 function parse(s){for(const m of s.matchAll(/<([a-z]+)([^>]*)>/gi)){const attrs={};for(const a of m[2].matchAll(/([\w-]+)="([^"]*)"/g))attrs[a[1]]=a[2];new Element(m[1],attrs);}}
 parse(shell);for(const [id,val]of Object.entries({plane:'xy',gridSize:'10',snap:'true',newColor:'#70b69b',elevation:'0',rotateAxis:'2',rotateAngle:'90',extrudeDistance:'40'}))nodes.get(id).value=val;
 function query(s){if(s.startsWith('#')){let id=s.slice(1).split(' ')[0];if(s.includes(' ')){let key=s;return nodes.get(key)||new Element(s.includes('img')?'img':'button',{id:key});}return nodes.get(id)||new Element('div',{id});}let a=s.match(/^\[([^=]+)="?([^\]"]+)"?\]$/);if(a)return all.find(e=>e.attrs[a[1]]===a[2])||new Element('button',{[a[1]]:a[2]});return new Element(s);}
 function queryAll(s){if(s==='#tools button')return all.filter(e=>e.dataset.tool);if(s.startsWith('[data-')){let key=s.slice(1,-1).split('=')[0];return all.filter(e=>key in e.attrs);}return [];}
 const events={};const sandbox={K:{...K},console,TextEncoder,TextDecoder,Blob,ImageData:class{constructor(data,width,height){this.data=data;this.width=width;this.height=height;}},URL:{createObjectURL:()=> 'blob:test',revokeObjectURL(){}},crypto:{randomUUID:()=> 'id-'+(++seq)},innerWidth:1400,innerHeight:900,devicePixelRatio:1,getComputedStyle:()=>({getPropertyValue:n=>({'--stage':'#eef0e8','--panel':'#ffffff','--ink':'#22372f'}[n]||'#22372f')}),navigator:{},location:{pathname:'/',protocol:'http:',reload(){}},ResizeObserver:class{constructor(fn){this.fn=fn;}observe(){this.fn();}},setTimeout:(fn,ms)=>{let id=++seq;timers.set(id,fn);return id;},clearTimeout:i=>timers.delete(i),localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},document:{querySelector:query,querySelectorAll:queryAll,createElement:t=>new Element(t),body:new Element('body'),addEventListener:(k,f)=>events[k]=f},errors,downloads};sandbox.window=sandbox;sandbox.window.addEventListener=(k,f)=>events['window:'+k]=f;sandbox.window.print=()=>{};const c=vm.createContext(sandbox);vm.runInContext(source,c);return {c,run:s=>vm.runInContext(s,c),nodes,storage,errors,downloads,events};
}

module.exports={environment};
